### ISSUE TITLE
"No handler found for the command bookmarks.toggle"

### ISSUE THREAD

**Issue by chrisdias** [alefragnani/vscode-bookmarks#1]
Running VSCode 0.10.1

To reproduce:
1. install the bookmarks extension
2. open a file
3. invoke the ">Bookmarks: Toggle" command in the Command Palette.

Result:
"No handler found for the command booksmarks.toggle"

In the console i see the following message: 

TypeError: Cannot read property 'document' of undefined

**Comment by chrisdias** [comment]
I cloned the repo and ran it locally, works great!  Maybe the version in the gallery is out of date?

**Comment by alefragnani** [comment]
I can reproduce the error. 

It happens if you open a folder for the first time, so **Code** opens with no active file, and I'm using `vscode.window.activeTextEditor` in activation.

I will fix it and publish the update soon.

Thanks
