### ISSUE TITLE
[Feature request] Bookmark tags

### ISSUE THREAD

**Issue by LeThiHyVong** [alefragnani/vscode-bookmarks#100]
Thanks for your extension.
Currently, Bookmark pane only provide file and line for bookmark list.
But I think that would be better if there is bookmark tags. Sometimes people may mark places by different purposes but on the same source code.
Hope to see it soon.

**Comment by alefragnani** [comment]
Hi @LeThiHyVong ,

Do you mean #76 combined with #88 ?

**Comment by LeThiHyVong** [comment]
@alefragnani yes, that's very close.
I hope it's possible to add multiple tags to each bookmark. I faced to the same reference code is used for many tasks.
An additional filter would be great, too.

**Comment by alefragnani** [comment]
That's great! 

I'll close this issue as a #76 **duplicate** and update its description to reflect the _multi-tag_ and filtering scenarios.

Thanks
