### ISSUE TITLE
Cannot toogle bookmark in large file

### ISSUE THREAD

**Issue by radim-moric** [alefragnani/vscode-bookmarks#101]
Opened file 200 MB with 1,4 million lines, tried to toggle bookmark (at any line) and received message "Open a file first to toggle bookmarks". What is the problem? The size of file or the number of lines?

**Comment by radim-moric** [comment]
So I did some tests and the magic number is 300,000 lines in the moment the file is opened (important). One more line and is not possible to toggle bookmarks. Even if you remove some lines to get below this limit. Even if you save file. The only option is to save and reopen such file with 300k lines or less. On the other hand, if you open file with 300k lines or less and then add some lines exceeding this limit, it's not problem and bookmarks still work.

**Comment by alefragnani** [comment]
Hi @radim-moric ,

This is caused by VS Code limitations, already reported in #31. Unfortunately, it depends on VS Code to update its design to allow extensions to be loaded correctly for large files.

The VS Code team seems to be working hard to improve large file support. Maybe in the future they also improve the extension support for large files.

Hope this helps

**Comment by radim-moric** [comment]
Thanks for your explanation Alessandro! So I will chase VS Code developers cause the current limit 300,000 lines for bookmarks extension is ridiculous... that's the reason I need bookmarks because I'm working with large files.

**Comment by bsevers** [comment]
I'm still having this issue. Has this not been addressed by the VSCode devs yet?

**Comment by alefragnani** [comment]
This wasn’t, and probably won’t be, _fixed_ by the VS Code team. 

They have improved the file size support in some areas in the last few years. It opens larger files and some features like syntax highlight works a lot better. But some of the limitations, like not fully activating extensions on large files are considered _by design_.

Hope this helps
