### ISSUE TITLE
Hide the Bookmarks view when there are no bookmarks

### ISSUE THREAD

**Issue by eamodio** [alefragnani/vscode-bookmarks#103]
I love this extension and use it often, but I don't often keep bookmarks around for long, so it would be great if when there were no bookmarks that the Bookmarks view would hide itself (and re-show once there are bookmarks again).

This should be easily accomplished with a custom context and a `when` clause on the view

Thanks again for a great extension!

**Comment by alefragnani** [comment]
The `bookmarks.treeview.visible` setting remains a `Boolean` value, accepting `false` or `true`. The difference will be on how each value will work.

- If you define `false`, the treeview will never appear _(same as today)_.
- If you define `true` it will be visible, but only if you have a bookmark (at least one) in your project, automatically updating its visibility if you add/remove bookmarks. _(new behavior)_,
