### ISSUE TITLE
Could you add a command: Bookmarks:Mark

### ISSUE THREAD

**Issue by aQuaYi** [alefragnani/vscode-bookmarks#104]
mark the unmark line 
and
do nothing for marked line

I use VSCodeVim to jump to Top/Bottom. Before jumping, I wanna make a bookmark for quickly go back.

**Comment by alefragnani** [comment]
Hi @aQuaYi ,

Thanks for you suggestion

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
