### ISSUE TITLE
Bookmark prevents adding breakpoint

### ISSUE THREAD

**Issue by pakLebah** [alefragnani/vscode-bookmarks#107]
This is a great extension. However, there's a minor flaw that's quite annoying, at least to me. 

It's when I put a bookmark on a line, it's somehow disable the ability to put a debugger breakpoint on the same line. So, I can't put a bookmark *and* a breakpoint on the *same* exact line. Though the workaround is quite simple, I simply move the bookmark one line over or below the breakpoint (because I think breakpoint is more important in programming workflow), it's an unnecessary flaw.

Could you fix this? Thank you.

**Comment by alefragnani** [comment]
Hi @pakLebah ,

Unfortunately, this is a VS Code issue. It was already reported in #56 and you could see the VS Code issue here https://github.com/Microsoft/vscode/issues/5923.

There is no ETA, and maybe you could help upvoting (👍) the issue. If I remember correctly, they use upvoting to decide which issues to pick for newer releases.

Hope this helps

It has already

**Comment by alefragnani** [comment]
Don't need to be sorry. I'm glad to help 👍
