### ISSUE TITLE
Wrong bookmark position on comment line

### ISSUE THREAD

**Issue by mgesmundo** [alefragnani/vscode-bookmarks#108]
Hi,
I noticed a wrong behavior when a bookmark is set to a comment line:

- place a bookmark to a comment line using Alt + Command + K
- move the comment line using Alt + arrow
- the bookmark is not moved consistently

Thank you for your awesome VS Code extension!
All the best.

**Comment by alefragnani** [comment]
Hi @mgesmundo ,

First of all, thank you 😀 

That's really weird. I didn't _detected_ that before. I have noted that sometimes the sticky behavior was failing, but didn't find a _pattern_. It seems that something related to _auto-indentation_ (which came out in VS Code in recent versions) is messing up with the line movement/change detection. I'll probably have to adapt the line movement/change detection for this scenarios too.

Thanks for pointing me out

**Comment by edgardmessias** [comment]
@alefragnani, done with #136
