### ISSUE TITLE
Bookmark list as an icon on the side?

### ISSUE THREAD

**Issue by ashmckenzie** [alefragnani/vscode-bookmarks#109]
It would be great if it were possible to have an icon on the side bar the toggles the bookmark list view!

e.g.

<img width="64" alt="srcgdkgdk-eegitlab gitlabeelibgitlabgeolog_cursordaemon rb gdk-ee workspace 2018-05-02 16-35-25 1" src="https://user-images.githubusercontent.com/9525/39508724-deb61c18-4e26-11e8-9490-c8993adb7530.png">

**Comment by alefragnani** [comment]
Hi @ashmckenzie ,

I remember that in the beginning, this is how the extensions would work. But for some reason, it was changed to add a new _Panel_ in `Explorer`.

Looking for news about it, I found [this issue](https://github.com/Microsoft/vscode/issues/43645) in VS Code repo, and doing a small test, I was able to _move_ the **Bookmarks** panel from the `Explorer`
view to its own view. So, it appear _it is returning_ 😀 . 

But, I still need [this other issue](https://github.com/Microsoft/vscode/issues/48704), which is planned only for **May 2018**. I see the _pros_ and _cons_ of both views, and I would really like to be able to _choose_ which one to use.

Hope this helps

**Comment by Otiel** [comment]
For reference: https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar

**Comment by rbenson** [comment]
I would be in favor  of an activity bar add vs explorer pane, largely to keep explorer more clean, and I tend to use bookmark-list over the`apane

**Comment by alefragnani** [comment]
It appears (based on reactions) that _maybe_ there is need to be able to _choose_ between a Panel in Explorer View _and_ an Bookmarks View _(exclusive),_ am I right? 😄 

So, let's vote?

👍 - Completely move to a new Bookmarks View
👎 - Create a setting to choose between view (wait for https://github.com/Microsoft/vscode/issues/48704)

**Comment by pakLebah** [comment]
I think it'd be better to make it as an option so everyone will be able to choose whichever s/he prefers. Everybody wins. 😊
