### ISSUE TITLE
Can you write in the  readme how to install?

### ISSUE THREAD

**Issue by dotnetCarpenter** [alefragnani/vscode-bookmarks#11]
I actually have no extension in my vscode. I used to use atom where it was always said how to install. Could you add the instructions to the readme?

**Comment by dotnetCarpenter** [comment]
I guess `F1` and then `ext install bookmarks`

**Comment by alefragnani** [comment]
Yes, that's it. Using `F1` and `ext install` is the interface for installing new extensions in **Code**. 

I never worried about adding it to the `readme`, neither in my **Atom** packages, because is something that the app itself documents how to do. But hey, why not :smile: 
 
Thanks for you suggestion, and I hope you enjoy the extension

**Comment by dotnetCarpenter** [comment]
I really do. Only one thing bothers me. Toggle bookmark doesn't actually toggle a bookmark but adds a bookmark. If I want to remove it I have to use remove bookmark. No biggie, just a name confusion.

**Comment by alefragnani** [comment]
Thanks. I decided to use **toggle** for simplification purposes, since you should have the same action to _mark_ and _unmark_ a bookmark. It's similar to **Atom** and **Sublime**.

But is an alternative behavior that I should be interesting to have (via config). I will take a look.

**Comment by dotnetCarpenter** [comment]
Sorry, I think I was confused. I did expect the **toggle** command to *toggle* a bookmark but it didn't work. I've been trying to reproduce but can't. Not sure in what situation it doesn't/didn't work but I'll create a new issue, if I find out.

I really like the current behavior. No reason to change that for my sake. Sorry for the confusion. `vscode-bookmarks` is great.

Example of documenting installation:
https://github.com/atom-minimap/minimap#installation

**Comment by alefragnani** [comment]
Closed in PR #12
