### ISSUE TITLE
Bookmark hot key selection

### ISSUE THREAD

**Issue by jrman523** [alefragnani/vscode-bookmarks#119]
it would be so helpful if we can toggle bookmarks based on a hotkey or a selection of keys and remove them or reset base on the hotkey I pick

**Comment by alefragnani** [comment]
Hi @jrman523 ,

I decided to use a simple _toggle_  command for simplicity. I think it's easier that way, and if I remember correctly, other text editors that I was using at the time, had the similar concept.

By now, I don't intend to change that, but I won't close the issue either. Let's see what others users say about it.

Hope this helps.

**Comment by rickyruiz** [comment]
Just create a keyboard shortcut in `keybindings.json`.

```
{
    "key": "shift+space",
    "command": "bookmarks.toggle",
    "when": "editorTextFocus"
}
```

**Comment by alefragnani** [comment]
If you combine this issue with #104, you will have `Mark/ UnMark` combination. In the end, it's _kind of_ a duplicate. So, I'm closing this issue, and you could keep tracking its evolution in #104.

BTW, In the last weeks I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

Thanks
