### ISSUE TITLE
There is only one bookmark in this file

### ISSUE THREAD

**Issue by balazser** [alefragnani/vscode-bookmarks#120]
I want to select the text from the current position till the placed bookmark. If there is only one bookmark placed I got the following information message and not able to select the text from the cursor point to the bookmark.

> There is only one bookmark in this file

If there are 2 bookmarks placed in a file then I'm able to select the text from the cursor until the first bookmark, then if I wish till to the next one using the Expand selection to the previous command.

**Comment by alefragnani** [comment]
Hi @balazser ,

Yes, this is how it was designed. The initial idea was to select _between bookmarks_ and so, it should have at least two bookmarks.

But, I a agree that the commands could be used even with _one_ bookmark 👍 

Thanks for your suggestion.

**Comment by balazser** [comment]
I'm looking forward to it. this feature would perfectly fit with code jumping.
thank you!

**Comment by alefragnani** [comment]
Hi @balazser ,

Right now I'm focusing on [Milestone 9.0](https://github.com/alefragnani/vscode-bookmarks/milestone/18). I still don't know what I will do for future releases. It will depend on how the community will help me...

Thanks

**Comment by ParkourKarthik** [comment]
Hi @alefragnani ,
I'll take up this issue and try looking into it. Will get back to you in need of assistance.

**Comment by ParkourKarthik** [comment]
Hi @alefragnani, I get errors while downloading the submodules source. Are the repos not active?

**Comment by alefragnani** [comment]
Hi @ParkourKarthik ,

First of all, thank you for your interest in taking the issue 👍 , but right now I'm refactoring the extension's core, and that piece of source is on a private repository. 

It would take at least another week before I finish this refactoring, so I suggest you to wait a bit. I'll let you know...

Hope this helps.
