### ISSUE TITLE
Trim leading whitespace when listing bookmarks

### ISSUE THREAD

**Issue by johnbillion** [alefragnani/vscode-bookmarks#121]
When listing bookmarks, it would be nice if leading whitespace was trimmed so that indentation was ignored, allowing more of the line of code to be visible.

Screenshot:

<img width="610" alt="" src="https://user-images.githubusercontent.com/208434/42168655-3f174488-7e1a-11e8-86a3-43e02cd0e4b1.png">

**Comment by alefragnani** [comment]
Hi @johnbillion ,

The new release (milestone 9.0) already do this. I decided to change that for a better UI for #76 .

Stay tuned

**Comment by johnbillion** [comment]
Cool! 👍
