### ISSUE TITLE
Bookmark to multiple line selected.

### ISSUE THREAD

**Issue by l41lt0n** [alefragnani/vscode-bookmarks#122]
Hi @alefragnani,

Thanks for this nice plugin!

I would like to know if you can add the feature to BOOKMARK all lines cursor.

If I am editing multiples line at the same time, and I press to bookmark the line auto mark all. ( Multi cursor )

The reason?

Sometimes, I am finding for a word and I would like to mark each line to check one by one.

It is very useful!

Thanks.

**Comment by alefragnani** [comment]
Hi @l41lt0n ,

First of all, thanks! I'm glad you like it 😁 .

About the request, I think it's the same as #77 . Am I right?

**Comment by l41lt0n** [comment]
Hi @alefragnani,

Thanks for the reply.
Sorry, I don't see it was created before. Yes. It is the same request.
It is very useful and interesting. please if you can add it for us.
How you can see a lot of users need it :D

Thanks

**Comment by alefragnani** [comment]
No problem, its common to miss this kind of duplicates.

Right now I'm focusing on [Milestone 9.0](https://github.com/alefragnani/vscode-bookmarks/milestone/18). I still don't know what I will do for future releases. It will depend on how the community will help me...

Thanks / Obrigado 😄

**Comment by l41lt0n** [comment]
Opá voce é de floripa :D

Irei da uma olhada depois no source se eu consigo implementar isso por conta.
Irei da uma olhada como isso funciona, nunca mexi com esse plugins somente em outros editores.

Obrigado pela atencao mesmo assim.

**Comment by alefragnani** [comment]
É isso ai 😁 

Sugiro esperar a release 9.0, pois alterei a API para suportar _colunas_ e _labels_, e vai ficar mais fácil adaptar para _receber uma lista_.

Qualquer dúvida é só perguntar

**Comment by l41lt0n** [comment]
@alefragnani 

Ok, irei aguardar. vi que vc tambem é o autor do Project Manager!!
Sao os 2 plugin que mais gosto do vs hehhe 

vlw.

**Comment by alefragnani** [comment]
Sim sim, desse e de outros também 😄 . Mas os mais _"famosos"_ são esses dois.

Valeu 👍
