### ISSUE TITLE
Correct path for gutter icon on mac?

### ISSUE THREAD

**Issue by asilvadesigns** [alefragnani/vscode-bookmarks#123]
Excellent plugin!

I continue to get a "file does not exist" error, when using a new icon file path, such as:
```
    "bookmarks.gutterIconPath": "file:///Users/XXXXXX/Documents/_Icons/book-bookmark.svg",
```

Can you provide an example or perhaps some help?
I opened developer tools, entered the above file url in background-image css rule, as element style and it works... so I'm not sure what I'm doing wrong.

**Comment by alefragnani** [comment]
Hi @asilvadesigns ,

You don't need to start the path with `file:///`. Use only `/Users/XXXXXX/Documents/_Icons/book-bookmark.svg". 

Just remember, MacOS, like Linux, is _case-sensitive_.

Hope this helps

**Comment by alefragnani** [comment]
Hi @asilvadesigns ,

Did work? Were you able to change the icon using my instructions? Or does it still fails?

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
