### ISSUE TITLE
bookmarks.navigateThroughAllFiles No Longer Works

### ISSUE THREAD

**Issue by claytoncarney** [alefragnani/vscode-bookmarks#125]
With today's update to 9.0.0, I find that even though the bookmarks.navigateThroughAllFiles is set to false, the Jump to Next and Jump to Previous commands cycle through all files. In the previous version, this was not the case. Very annoying and not the way I'm accustomed to working. I tried downgrading to versions 0.18.1 and 0.19.1, but those versions no longer seem to work at all.

Using vscode 1.25.1.

**Comment by claytoncarney** [comment]
Here's a screencast demonstrating the issue:

https://drive.google.com/open?id=1YVE5FXPJLHixB4AahWJTFW1XLTfenFW4

**Comment by alefragnani** [comment]
Hi @claytoncarney ,

You are right, I could reproduce the error 👍 .

Thanks for reporting

**Comment by lega911** [comment]
working hot-patch, file **Bookmark.js**:
```javascript
62c62,63
<                         resolve(this.bookmarks[0].line);
---
>                         nextBookmark = this.bookmarks[0];
>                         resolve(new vscode.Position(nextBookmark.line, nextBookmark.column));
85c86,87
<                         resolve(this.bookmarks[this.bookmarks.length - 1].line);
---
>                         nextBookmark = this.bookmarks[this.bookmarks.length - 1];
>                         resolve(new vscode.Position(nextBookmark.line, nextBookmark.column));
```

**Comment by lega911** [comment]
https://github.com/alefragnani/vscode-bookmarks/pull/129

**Comment by claytoncarney** [comment]
Excellent. Hot-patch resolves issue. Thank you!

**Comment by alefragnani** [comment]
Thanks @lega911 👍 🎉

I'll merge your PR and release an update ASAP...
