### ISSUE TITLE
Not working after last vscode update

### ISSUE THREAD

**Issue by nachocab** [alefragnani/vscode-bookmarks#126]
I'm getting `bookmarks.toggle` not found after the last vscode update. None of the other commands work either. I've tried re-installing the extension, but it doesn't work. 
<img width="625" alt="screen shot 2018-07-16 at 13 59 05" src="https://user-images.githubusercontent.com/27538/42757477-8b9fed96-8900-11e8-96e4-e3ca42ebbaec.png">

It's not a shortcut problem because I get the same when going through the menu command (although, instead of a yellow triangle with an exclamation, I get a red circle with an x)

**Comment by nachocab** [comment]
Ok. It appears like this was a workspace problem. I created a new workspace and the problem went away

**Comment by alefragnani** [comment]
Hi @nachocab ,

Good to know it's working now 👍 

Is there a scenario that you could reproduce the error? I mean, an empty workspace/folder, an multi-root workspace, etc?

Thanks

**Comment by nachocab** [comment]
Thanks for the awesome extension!

I still think it's something related to the update because I didn't do anything weird to my workspace. If it happens again, I'll report back. 👍

**Comment by razvan-ciochina** [comment]
Hello,
I had a similar issue with files outside the workspace. In version 11.0.0 of the plugin there's a setting called: **Bookmarks:Navigate Through All Files\Allow navigation look for bookmarks in all files in the project, instead of only the current**.
This fixed any problem for me.
Hope this helps.

**Comment by alefragnani** [comment]
Hi @razvan-ciochina ,

These are two different scenarios. In your case, it’s not an issue, but the _default behavior_. 

When the extension was created, the navigation only supported for the _current file_. So the `Jump to Next` And `Jump to Previous` didn’t look for other files in the project/workspace/session. After a few releases (in 2016 btw #8 ), I added this setting (default `false`) so the navigation will search for any file in your folder/workspace/session. 

There is an open issue #102  to change the _default value_ of this setting to `true` (or even remove the setting and make it the only behavior).

Hope this helps.
