### ISSUE TITLE
Bookmarks List: Cannot jump to bookmarked lines beginning with space(s) / tab(s)

### ISSUE THREAD

**Issue by rousni** [alefragnani/vscode-bookmarks#135]
v9.0.0 v9.0.1 v9.0.2, Windows 10
**Bookmarks List**: Cannot jump to bookmarked lines ‌beginning with space(s) / tab(s)
(except if the bookmarked position is situated after the leading whitespaces).
Same problem if the bookmarked line is empty.

**Comment by alefragnani** [comment]
Hi @rousni ,

Haha.. it works for _all files_ but not for _current file_. Good catch 👍

**Comment by rousni** [comment]
> it works for all files but not for current file.
I hope this means the bug will be easily fixed. Bookmarking is essential for any text editor, and in my opinion this VS Code Bookmarks extension is without alternative.
Thank you, Alessandro Fragnani!

**Comment by alefragnani** [comment]
Yes, it will 👍. 

I hope I could find some time until the weekend. 

Stay tuned
