### ISSUE TITLE
Idea : Toggle Labeled Bookmark automatically inserted Line

### ISSUE THREAD

**Issue by ejabu** [alefragnani/vscode-bookmarks#137]
Hi, @alefragnani  I have an idea 

Instead of separating two Commands, one for Labeled Bookmark and the other one for unLabeled Bookmark.

I have suggest a workflow like this (in my Case, I use Ctrl+B as a shortcut)
1. WIth

1. Simple Bookmark (W/o label)

a. Ctrl + B

this one showed

![image](https://user-images.githubusercontent.com/2019630/43328500-598cacfe-91e8-11e8-9984-91cfe003b70f.png)

b. Ctrl + Space
automatically unlabel the bookmark
will result this 

![image](https://user-images.githubusercontent.com/2019630/43328250-b7d3968e-91e7-11e8-9701-81a02b75009f.png)

2. With Bookmark (With label)

a. Ctrl + B

this one showed

![image](https://user-images.githubusercontent.com/2019630/43328500-598cacfe-91e8-11e8-9984-91cfe003b70f.png)

b. Type the name 

![image](https://user-images.githubusercontent.com/2019630/43328354-f45facf0-91e7-11e8-9882-a3b42e3e4471.png)

c. Enter
will result this

![image](https://user-images.githubusercontent.com/2019630/43328409-1cb00182-91e8-11e8-8f5f-ef45de710081.png)

**Comment by alefragnani** [comment]
Hi @ejabu,

First of all, thank you for your suggestion. I will take note on that 👍 

About the `Labeled Bookmark` UX enhancement, I will try to concentrate the discussion on #124, but to give you an early feedback, I'm still not _convinced_ about using a single command 😄. For me, the labeled bookmark is a _secondary_ option, so it should be an _alternative_ command.

Thanks
