### ISSUE TITLE
Saving deletes bookmars.

### ISSUE THREAD

**Issue by GAZ082** [alefragnani/vscode-bookmarks#139]
Hi there. I bookmark something by toggling it and when i hit CTRL+S, disappears, making the plugin obsolete!

```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64 (Archlinux)
```

![peek 2018-07-31 12-51](https://user-images.githubusercontent.com/100194/43471068-7c045856-94c0-11e8-9023-6b59cbd90f0d.gif)

**Comment by alefragnani** [comment]
Hi @GAZ082 ,

Do you have any _formatter_ installed and configured to run `on save`? I'm asking because it seems that your text is _moving one line up_ at no reason.

Is that your case?

**Comment by alefragnani** [comment]
How does these empty lines are removed? Is it a VS Code setting?

If _something_ is automatically removing empty lines, or if you have any _formatter_ installed, then the Bookmarks will not work. The Bookmarks extension _needs to know_ when changes are made in the editor, so it can move the bookmarks _up and down_, just like when you hit `Return` or `Delete` lines (manually).

If that is your case, you have the same issue as #118 , which unless the _other extension_ or VS Code itself does something about it, like creating some API that I can _listen_, you won't be able to use the extension. I remember a couple of extensions that are also suffering with this kind of _pre/post-saving operations_. Maybe VS Code team will look at this in the future.

**Comment by GAZ082** [comment]
I do think is something related. I close this issue and will keep track of #118
