### ISSUE TITLE
See bookmarks on the scroll bar

### ISSUE THREAD

**Issue by Nimzozo** [alefragnani/vscode-bookmarks#14]
It would be great to see the bookmarks on the scroll bar, like the error / warning marks.

**Comment by alefragnani** [comment]
:+1: 
I already thought about that, but didn't decide the position that this indicator could appear :smile:. It normally have _git_, _find_, and _build warnings_, so I have to pick one that don't override them.

Thanks for your suggestion.

**Comment by Nimzozo** [comment]
Does "Milestone 0.5.0" mean that this feature will be available for the 0.5.0 release ? :question: :smiley:

**Comment by alefragnani** [comment]
That's right :+1: 

I guess it will be available next week. Stay tuned.
