### ISSUE TITLE
Add option to enable highlighting marked line

### ISSUE THREAD

**Issue by lamartire** [alefragnani/vscode-bookmarks#141]
Hello! Thank you for your awesome extension ✨ 
Does it possible to implement highlighting of "marked" line?

![image](https://user-images.githubusercontent.com/13414205/43764051-094f2136-9a35-11e8-9335-86298603f8c7.png)

I means highlighting like current line, but with blue color.
Thank you and have a nice day.

**Comment by alefragnani** [comment]
Thank you @lamartire 👍  ,

I think you are asking the same as #98. There is even a PR #133 for that, but right now, I'm focused on other projects, so it will have to wait a bit. Stay tuned.

Hope this helps

**Comment by lamartire** [comment]
Yeah, that it! Thank you and good luck on your current project ✨
