### ISSUE TITLE
Bookmark explorer needs Collapse All/Expand all

### ISSUE THREAD

**Issue by mbenkmann** [alefragnani/vscode-bookmarks#144]
Bookmark explorer needs a Collapse All/Expand all button. The file explorer has a collapse all but no expand all, so I hope that this is not a restriction in VSCode. The Bookmark explorer should definitely have an Expand all button and probably an option to always start expanded.

**Comment by alefragnani** [comment]
Hi @mbenkmann ,

Thanks for your suggestion. This has already been requested in #92 , so I'm closing it as a duplicate.
