### ISSUE TITLE
Could we show file name before relative path?

### ISSUE THREAD

**Issue by bingozhu0197** [alefragnani/vscode-bookmarks#149]
As the relative path may be deep and similar to each other while the file name is different. If we can show the file name before the relative path, it will greatly help navigation from bookmark explorer.

**Comment by alefragnani** [comment]
Hi @bingozhu0197 ,

Instead of _invert_ filename and folder, I think it would simply show the filename itself, and then, a _hint_ would show the full/relative path.

Thanks for your suggestion

**Comment by jehillert** [comment]
Me again. Yes, this issue looks just about the same as what I raised.  The only distinction may be that I care more about the bookmarks not being nested.  Just an option for a flat list would be great.  VS code is awesome, but I find its interface can be a bit busy compared to Sublime Text, which I started with. A busy UI can really slow me down when I am tired, so the simpler the extensions are that I add to it, the better.  Especially for an extension like yours, where a user who really buys into it as a primary navigation tool could be interacting with it hundreds of times a day. At that point, those extra clicks required to expand a nested list, and those incremental expenditures of brainpower needed to find bookmarks in its more complex structure, all that begins to add up.

**Comment by jehillert** [comment]
Come to think of it, I do have a thought about the file/bookmark names.  Each item in the list below is something I have found over the years to be helpful for reducing the mental load associated with constant file/folder navigation:
- Being able to assign unique font colors to the text of frequently visited files, folders, bookmarks and links 
- Being able to assign custom icons to frequently visited files, folders, bookmarks and links 
- Being able to rename bookmarks and links
- Being able to manually change the order of individual bookmarks/links in a list

Incorporating any of these capabilities into your extension would be awesome. 

Again, this is all just wish-list stuff.  Your extension is great in its current form.  I am just rattling off everything that comes to mind while I've got you on the line, so to speak.

**Comment by Friksel** [comment]
First of all I like this extension a lot! very helpful.
It would be much appreciated if there would be some setting to allow the long filenames with the full path to be diplayed as just the filename (and show the full path in a tooltip when hovering over it or something like that to be able to show the full path).
I also like the suggestion in this request to add the full path AFTER the filename. That way we could have both.

But unfortunetaly the way it is showing filenames now is pretty difficult to use in projects we work on with some pretty deep paths. I often have to open all collapsed items just to recognise which file it is. That's pretty counter intuitive when bookmarking should already make things easier.

So I'm all for it! Thanks in advance and for the great work!

**Comment by alefragnani** [comment]
@jehillert thank you for your suggestions. I didn't have the proper time to answer your comments, but I'll take in consideration in other improvements in the near future 👍 . About custom colors/fonts for the side bar and/or bookmarks itself, unfortunately there is no API available for that, so we are out of luck.

@Friksel thank you. I'm glad to know you like the extension. 

Right now (next release in a couple of days) I'll remove the _relative path_, leaving the _filename_ only. I played a little and didn't miss the relative path, once you have the _full path_ available in _hint_.

Hope this helps.

**Comment by Friksel** [comment]
> Right now (next release in a couple of days) I'll remove the _relative path_, leaving the _filename_ only. I played a little and didn't miss the relative path, once you have the _full path_ available in _hint_.
> Hope this helps.

Thanks a lot! That would definitely help a lot!
Have a nice day
