### ISSUE TITLE
Keyboard shortcut for bookmarks:explorer on workbench

### ISSUE THREAD

**Issue by arjunagl** [alefragnani/vscode-bookmarks#152]
Hello,

Is there a keyboard shortcut I can use for the bookmarks view on the workbench?

Thanks

**Comment by alefragnani** [comment]
Hi @arjunagl ,

No, there isn't. 

But you could customize your own in `File / Preferences / Keyboard Shortcuts`, using this snippet:

```json
{
    "key": "ctrl+shift+b",
    "command": "workbench.view.extension.bookmarks"
}
```

Hope this helps

**Comment by arjunagl** [comment]
Thanks a lot for this, very very useful.
