### ISSUE TITLE
Bookmarks at sidebar with number badge (how many bookmarks)

### ISSUE THREAD

**Issue by LukasPolak** [alefragnani/vscode-bookmarks#153]
It is possible to add badge with number (how many bookmarks) are in the current folder / workspace / project ? It will be really nice feature. 
And thanks for awesome extension! 

![bookmark - badge](https://user-images.githubusercontent.com/17145302/46061574-6d0a8b80-c167-11e8-94e6-457cfd49dc3f.png)

**Comment by alefragnani** [comment]
Hi @LukasPolak ,

That's an interesting idea, but it appears there is no API available for that (yet). 

I will try to find some info, and will update here any news.

Thanks

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/54938

**Comment by alefragnani** [comment]
In fact, it depends on https://github.com/microsoft/vscode/issues/38426, which were mistakenly closed as _duplicate_.

**Comment by alefragnani** [comment]
Now it is being tracked in https://github.com/microsoft/vscode/issues/62783

**Comment by alefragnani** [comment]
The VS Code API is finally on `proposed` status. 
I hope it could be released in a couple of months

**Comment by alefragnani** [comment]
The API has finally landed.
Planned for October 2022 release

**Comment by alefragnani** [comment]
There will be a setting to choose what the meaning of the badge:

* Number of bookmarks in the current window/workspace _(default)_
* Number of files with bookmarks

**Comment by alefragnani** [comment]
@mrcwebdesign this has not been released yet. I'm planning to release an update next month.
