### ISSUE TITLE
FE: Being able to search and add a bookmark to each of the results found.

### ISSUE THREAD

**Issue by ashworthca** [alefragnani/vscode-bookmarks#157]
If I search a file for some random string I would like each line it finds that string to be able to be bookmarked.

For example we have the following file:
```
1 <html>
2 <head>
3 <title>hello world</title>
4 </head>
5 <body>
6 hello world!<br>
7 </body>
8 </html>
```

if I did a "bookmark find all" for the word "hello", it would bookmark line 3, and 6.

**Comment by alefragnani** [comment]
Hi @ashworthca,

This has already been reported in #7, but since no API was released in VSCode core (after 2 years), I decided to close it in favor of #77. 

Feel free to :thumbsup:  #77

**Comment by Gettyk** [comment]
I was also looking for the same feature and I read the #77 but I am not sure I understood it right. Just to be sure, for now, there is no way to do ashworthca ask for? The #77 is in a feature in you TODO list not a real feature, right?

**Comment by alefragnani** [comment]
Hi @Gettyk,

You are not doing anything wrong. The point is that #77 is still open, so you can't do multi-toggle, yet. :smile:

The idea is: VSCode didn't provide an API to intercept search commands (current file or whole workspace), so I decided to use the muti-select feature to achieve _similar results_. Every location you have a cursor would receive a bookmark.

Hope this helps

**Comment by Gettyk** [comment]
Ah ok thank you!
