### ISSUE TITLE
Feature Request : Bookmark groups

### ISSUE THREAD

**Issue by TomYeoman** [alefragnani/vscode-bookmarks#159]
Hi Team,

Awesome product thanks for developing.

I was wondering if I was missing a feature / this is in the pipeline ( I may even consider doing this myself? ).

My idea is for there to exist the ability to have groups of bookmarks in order to map a particular flow for a project.

I think this would be very powerful to document how to perform a particular system task ( I.E the flow from start to finish for adding a new common feature which touches multiple files, Or a complicated maintenance task etc )

I.E could be structured like so in `bookmarks.json`

```
[
  {
    "stepsToImplementNewFeature": [
      {
        "path": "$ROOTPATH$\\src\\file1.js",
        "bookmarks": [
          {
            "line": 40,
            "column": 0,
            "label": "Perform action X"
          }
        ]
      },
      {
        "path": "$ROOTPATH$\\src\\file2.js",
        "bookmarks": [
          {
            "line": 10,
            "column": 0,
            "label": "Perform action Y"
          }
        ]
      },
      {
        "path": "$ROOTPATH$\\src\\file3.js",
        "bookmarks": [
          {
            "line": 0,
            "column": 0,
            "label": "Perform action Z"
          }
        ]
      }
    ],
    "stepsToPerformComplicatedMaintenanceTask": [
      {
        "path": "$ROOTPATH$\\src\\file1.js",
        "bookmarks": [
          {
            "line": 40,
            "column": 0,
            "label": "Perform action X"
          }
        ]
      },
      {
        "path": "$ROOTPATH$\\src\\file2.js",
        "bookmarks": [
          {
            "line": 10,
            "column": 0,
            "label": "Perform action Y"
          }
        ]
      },
      {
        "path": "$ROOTPATH$\\src\\file3.js",
        "bookmarks": [
          {
            "line": 0,
            "column": 0,
            "label": "Perform action Z"
          }
        ]
      }
    ],
  }
]


```

**Comment by alefragnani** [comment]
Hi @TomYeoman ,

First of all, sorry for taking so long to answer you. I was a bit busy taking care of another projects.

About your request, that's an interesting idea, but I think it goes beyond the scope of the extension. This is just a _bookmark_ extension, which allows you to mark position and easily return to that position at any time. What you ask is something like a _wizard/step by step manager_. It seems a new extension to me. 

What do you think?

Alessandro
