### ISSUE TITLE
Commands in context menu

### ISSUE THREAD

**Issue by Nimzozo** [alefragnani/vscode-bookmarks#16]
As for breakpoints, it would be easier to add / remove bookmarks via the context menu if it's doable. :yum:

**Comment by alefragnani** [comment]
Unfortunately, there is no API to customize the context menu _(yet)_.
Maybe in the future:smile:

**Comment by alefragnani** [comment]
An [issue](https://github.com/Microsoft/vscode/issues/3192) was opened on VSCode repo.

**Comment by Nimzozo** [comment]
Nice !

**Comment by alefragnani** [comment]
A new API was released with VSCode 1.3.0 :tada:
