### ISSUE TITLE
Bug: Sidebar Icon Display

### ISSUE THREAD

**Issue by mikeerickson** [alefragnani/vscode-bookmarks#160]
In the latest update, it seems bookmark sidebar icon has an issue (see screenshot)

![image](https://user-images.githubusercontent.com/183153/48738404-c3df8f00-ec05-11e8-8fe0-246592784b3e.png)

**Comment by mikeerickson** [comment]
FYI, I disabled and then enabled the plugin, did a reload and all is good now.  Not sure what caused the issue, but its working so that is good enough for me.

**Comment by mikeerickson** [comment]
Well, this issue has returned.  I think I have tracked down when the problem occurs, but I wont be able to confirm my thoughts until tomorrow.

It seems to occur when upgrading VSCode (I am using the insiders build) so each day when I "Restart" Code to install update, the first launch after update, the problem occurs.

I will report to you tomorrow if my thinking is correct.

**Comment by alefragnani** [comment]
Hi @mikeerickson ,

I also have **Insiders** installed, both at home and at work, but didn't notice this issue. BTW, I just 'restarted' it after the update right now, with no problem.

If the problem occurs again, I suggest you to reinstall (uninstall, exit VSCode and install again) the extension, instead of just disabling. I remember some _weird_ issues happening after updating VSCode or the extensions.

Hope this helps

**Comment by mikeerickson** [comment]
Sounds good, I will do that. It only happens once each morning (when i install updates) so that was the reasoning. It only happens once per day 🤓

**Comment by mikeerickson** [comment]
@alefragnani Well, it is not related to the nightly updates.  I woke up computer this morning from an evenings sleep and I see the following before I apply nightly update.  And of course, after a restart all is fine.   This time, I am going to uninstall and reinstall plugin and see what happens moving forward.

![image](https://user-images.githubusercontent.com/183153/48855227-847d8380-ed68-11e8-8b1f-6e0e5f064dc0.png)

**Comment by raykle** [comment]
Hi, thank you for the plugin, I have the same problem too.

MacOS 10.14.1, VSCode 1.29.1 (1.29.1), using the theme 'One Dark Pro'.

When I change the theme to 'Light (Visual Studio)', the icon just disappeared, but it's still there actually.

![image](https://user-images.githubusercontent.com/3097366/49197161-ce99e100-f3c8-11e8-99df-a89f22901b6b.png)
![image](https://user-images.githubusercontent.com/3097366/49197195-f8eb9e80-f3c8-11e8-952b-237b957b742a.png)

**Comment by mikeerickson** [comment]
@raykle does the issue go away after restart? Also, a new version was available today, did you install the update. I have not been able to reproduce since upgrading

**Comment by raykle** [comment]
@mikeerickson Yeah, it's OK now. I think I forgot to reload the window. Thanks!
