### ISSUE TITLE
Enhancement Request: Per-Branch bookmarks

### ISSUE THREAD

**Issue by mliq** [alefragnani/vscode-bookmarks#162]
It would be awesome if we could have bookmarks be organized / switched by the git branch they are on.

**Use case 1:** Switching among branches, sometimes bookmarks disappear forever when a file does not exist on another branch.

**Use case 2:** This would be a great way to be able to switch branches and easily get back to the relevant code areas for each one.

Thanks for the great extension!

**Comment by alefragnani** [comment]
Hi @mliq ,

First of all, thank you. I'm glad you like the extension 👍 

About your request, I think the `bookmarks.saveBookmarksInProject` would work for you. It will store the bookmarks inside the repo (`.vscode\bookmarks.json` file) and so, whenever you switch between branches, the bookmarks are updated as well.

What do you think?

**Comment by mliq** [comment]
Hi and thanks @alefragnani - I will give that a go!

**Comment by mliq** [comment]
@alefragnani Thanks, that does solve the problem of bookmarks disappearing, but I still have the same set of bookmarks regardless of which branch I am on, since `.vscode\` is in my `.gitignore` (and must be, since I am collaborating with others). 

I suppose the way to implement would be to alter the format of bookmarks.json such that it kept separate lists of bookmarks for each branch name. I could potentially work on it and submit a PR some day if you are open to that.

**Comment by alefragnani** [comment]
That's great 🎉 

Even if `.vscode` folder is in .`.gitignore`, ou could add `.vscode/bookmarks.json` using `git add --force`, being available like any other file. 

I wouldn't change the `bookmarks.json` format/structure to support Git, or any other CVS. These are two separate concepts, and you could end up with a very complicate structure to deal with.

Try this `git add --force` idea. It would probably work for you.

Hope this helps.

**Comment by glaslos** [comment]
Adding just `.vscodebookmarks.json` to git doesn't solve the described problem for the same reason .vscode is ignored.
@mliq did you find another solution for your problem?

**Comment by geecrypt** [comment]
@glaslos I found that using `git add --force .vscode/bookmarks.json` works ok for my needs. I create bookmarks on `branchA`, force add and commit them. You will need to remove the bookmarks from committed changes before pushing to a remote if you don't want to upload your bookmarks. However this means you will need to commit your bookmarks again locally or risk losing them! A simpler way to use bookmarks with this git flow is to keep bookmarks commmited on a `branchA-dev` then merge your changes to a `branchA-deploy` where you will remove the bookmarks and push from.

Not sure if this is a bug, but after switching to `branchB`, the `branchA` bookmarks persists in some vscode cache until you `Reload Window`.
