### ISSUE TITLE
Multicursor issue

### ISSUE THREAD

**Issue by danoffn** [alefragnani/vscode-bookmarks#164]
Hello,
I noticed a wrong behaviour with multicursor:

After put a bookmark in some line and enter some new lines with multicursor before the bookmark, the bookmark doesn't follow the text bookmarked.

![peek 2018-11-30 12-25](https://user-images.githubusercontent.com/17597749/49298063-2d2f8f80-f49b-11e8-98a9-032d2633099a.gif)

**Comment by alefragnani** [comment]
Hi @danoffn ,

The extension is not compatible with multicursor, _yet_. 

This is already being tracked in #77 , but it doesn't say anything about _sticky should also be respected_ so I'll update its description to also work in this scenario.

Thank you for remembering this 👍 

Hope this helps
