### ISSUE TITLE
bookmarks hierarchy view

### ISSUE THREAD

**Issue by holajoyce** [alefragnani/vscode-bookmarks#165]
lt is very nice that bookmarks are listed under each file name and that I can see it as a tree view.  It would also be really nice, if we can be allowed to provide our own type of hierachy to the bookmarks.

Ie.  I have a label called `feature_1`, and to be able to define another sub label under it, such as `sub_feature_a` and that it can display regardless of which file the file label is defined in (in the treeview).

This is a great project, I enjoy using it a lot!

**Comment by alefragnani** [comment]
Hi @holajoyce ,

Thank you, I'm glad you like the extension 👍 .

About your request, I think similar to #159 , and end up being _out of scope_. This kind of _organization_ goes beyond (in my point of view) to the extesion's goal. If you add `sub_feature_a` today, maybe a few weeks later you may want to add another level of organization, and decide to add a `sub_sub_feature_a`.  Just like #159, I think this could be another extension. 

What do you think?

**Comment by Brittank88** [comment]
Heads up: You can kinda do this sort of thing already (provided the bookmarks already follow a linear ordering) just by prefixing the labels with whitespaces (tabs don't seem to work):

![image](https://user-images.githubusercontent.com/24266948/125898939-f4c5ffc4-9268-4c24-a733-a9e1b73dceb1.png)

**Comment by alefragnani** [comment]
Hi @Brittank88 ,

Maybe #254 / #225 , when available, could help. I’m planning to start #254 in upcoming weeks.

Stay tuned
