### ISSUE TITLE
saving file removes all bookmarks, if using crystal lang's vscode extension

### ISSUE THREAD

**Issue by girng** [alefragnani/vscode-bookmarks#169]
hi! i kept wondering where all my bookmarks went! i kept seeing them disappear but couldn't figure out why lol

i finally found out when using this extension for crystal-lang:
https://github.com/crystal-lang-tools/vscode-crystal-lang

and when you save your crystal file, all your bookmarks poof.

i'm on windows 10 64-bit if that matters. if you need any more info please don't hesitate to ask, thanks!

**Comment by alefragnani** [comment]
Hi @girng ,

You may be facing the same problem described in #118 . I have developed a [workaround](https://github.com/alefragnani/vscode-bookmarks/issues/118#issuecomment-442686987), until a proper API is available in VS Code, and my extension is _notified_ about code format.

Add `"bookmarks.useWorkaroundForFormatters": true` to your user settings, and the bookmarks should stop to disappear.

Hope this helps

**Comment by girng** [comment]
wow @alefragnani it seems to work!! thank you so much
