### ISSUE TITLE
Ability to change language (locale)

### ISSUE THREAD

**Issue by inaniyants** [alefragnani/vscode-bookmarks#171]
There is no ability to change language independently from system locale. 
This is not common practice to localize developers tools and commands by default, since it requires developer to switch lang when using tool commands, that are not bounded to hotkey.

My suggestion is next: stop using system locale by default and add a setting, where user could switch this.

**Comment by alefragnani** [comment]
Hi @inaniyants,

The "engine" on how to translate/localize VSCode is defined by VSCode itself, not this extension. I just followed its published API.

If you think VSCode should change how it translate/localize the app please, fill an issue in VSCode repository.

Hope this helps

**Comment by inaniyants** [comment]
Thank you for you attention to a described problem. Now I see, that this is not related to your extension. 
By the way vscode fixed issue with locale in version 1.33, so now all extensions, including yours, are correctly displaying in vscode locale (not system locale as earlier)
