### ISSUE TITLE
Add an option to disable the "What's new" tab

### ISSUE THREAD

**Issue by philippludwig** [alefragnani/vscode-bookmarks#175]
When this extension is updated, it automatically opens a tab to display news - would it be possible to add an option to disable this behaviour? 

I just want to set bookmarks, please don't disturb my work.

**Comment by alefragnani** [comment]
Hi @philippludwig ,

Thank you for your suggestion, but I'll keep the current approach for now. Don't worry, the "What's New" window will appear only on new releases. This is not a nag window.

Hope this helps

**Comment by philippludwig** [comment]
For anyone else with this problem, the solution is to use click the cog wheel in the extension list, select "Install another version" and pick any older version. This will VSCode cause to disable auto updates for this extension and therefore this annoying tabs.

**Comment by felixjb** [comment]
Hi guys,

VSCode itself has an option for that now. Just add the following config to your user settings:

`"update.showReleaseNotes": false`

**Comment by skoshy** [comment]
@felixjb I believe that's just for VSCode's release notes, not for other extensions.

@alefragnani Please reopen this and consider adding an option, seeing the What's new page pop up as it did today is jarring and unwanted for me personally.

**Comment by geraldcombs** [comment]
> Don't worry, the "What's New" window will appear only on new releases. This is not a nag window.

This sort of assumes that I only have one VS Code window open. In my case, every time there's a new Bookmarks release I get blasted with "What's New" tabs in the multiple VS Code windows that are open on my laptop, my desktop, my Windows VM, etc. It is really, truly annoying and I hope that you will reconsider reopening this bug.

**Comment by philippludwig** [comment]
Interesting that this issue still has not been resolved - personally I stopped using this extension long ago because of this.

**Comment by MaffooBristol** [comment]
> This is not a nag window.

Yes it is.

**Comment by skoshy** [comment]
@alefragnani Again the What's New popup has shown up. Please give us the option to disable this, it's interruptive to my workflow.

**Comment by fade2gray** [comment]
Wouldn't it work for you all to just disable `Extensions: Auto Update`?

**Comment by skoshy** [comment]
> Wouldn't it work for you all to just disable `Extensions: Auto Update`?

I don't want to disable updates to all of my extensions, just the What's New popup. No other extensions I have do this (except GitLens, but they have an option to disable it, `gitlens.showWhatsNewAfterUpgrades`).

**Comment by alefragnani** [comment]
I'm sorry to hear this feature bothers some of you so much, but if you like the extension the way it is today, and do not want to receive new features, you have only one alternative. As [commented above](https://github.com/alefragnani/vscode-bookmarks/issues/175#issuecomment-455655466), you can use the **Install Another Version** option, and choose any older version, and VS Code will no longer update the extension.  

But, if you want to receive the cool features, most of them, requested by you the users, and that I developed in my spare time, the **What's New** window is the way you will know about it.

This window only appears on new releases, which doesn’t happen more than once a month, so in the end, it is less frequent than VS Code itself.

I’m thinking on how to _minimize_ its appearance across multiple windows, as [pointed out here](https://github.com/alefragnani/vscode-bookmarks/issues/175#issuecomment-589784296), but not disabling .

Hope this helps

**Comment by LukeOrdelmans** [comment]
The issue (for me at least) is that several extension started doing this, so much that I had to click away an annoying/useless tab every time I started vscode. 
I almost deinstalled vscode, but then decided just to drip al extensions that have this behavior without an option to disable it.
sidenote: I think vscode should provide a global setting to dissallow/block extensions from auto-opening tabs (i'll check if i can put in a feature request).

**Comment by LukeOrdelmans** [comment]
upstream feature request added: https://github.com/microsoft/vscode/issues/112494

**Comment by KapitanOczywisty** [comment]
@alefragnani You are owner so you may do what you want, but I've just removed your extension.

> you can use the **Install Another Version** option, and choose any older version, and VS Code will no longer update the extension.

*and* disable auto-updates for all extensions, which aren't annoying
 
> the **What's New** window is the way you will know about it.

If somebody needs certain feature he'll know, others do not care. I don't even read these tabs. Did you even read changelog to see what new and exciting features you're adding and telling everybody about? People literally couldn't wait for them any longer.

> This window only appears on new releases, which doesn’t happen more than once a month, so in the end, it is less frequent than VS Code itself.

With VS Code Remote development, `What's new` will appear on every machine and sometimes even after restart will appear again. This is deal breaker in my case.

----

I appreciate you're work, but open source is not a place for adware.

**Comment by alefragnani** [comment]
I’m planning to _minimize_ it’s appearance, but it is not going away. I’ve created two issues on my `vscode-whats-new` submodule (which handles the whole What’s New experience), based on feedbacks:

* Avoid displaying the webview on every opened VS Code instance (https://github.com/alefragnani/vscode-whats-new/issues/10)
* Avoid displaying the webview while running on Codespaces and/or installed on remotes (https://github.com/alefragnani/vscode-whats-new/issues/23)

As I said, the idea of this window is to display the new features. The above scenarios wouldn’t change the original idea, but fix these behaviors.

**Comment by alefragnani** [comment]
@KapitanOczywisty ,

> and disable auto-updates for all extensions, which aren't annoying

Installing _another version_  from one extension, doesn’t affect how update works for _other extensions_. If it doesn't work for you, you should open an issue on VS Code itself.

Hope this helps

**Comment by KapitanOczywisty** [comment]
> Installing _another version_ from one extension, doesn’t affect how update works for _other extensions_.

Unless they changed this recently, when new version is published, then even extension with specified version is updated. To prevent this I had to check disable auto-updates. There are other options like install extension from vsix, but It's not worth the effort, especially when using VS Code Remote Development. You should be well aware that people which would disable "what's new" windows, don't even read that, this is only for pure annoyance.

**Comment by waynebloss** [comment]
@KapitanOczywisty lol yeah, I have literally never read one sentence of the Bookmarks "What's New" page.

**Comment by xtqqczze** [comment]
@alefragnani In order to avoid more duplicates such as #632, please reopen this issue.

**Comment by Sundava** [comment]
@alefragnani I fail to see **why** we absolutely need to see this, especially on a whole new tab ?
Most extension do a small notification on the bottom-left side of the screen, which is enough for me to know I can check the changelog **if I want to**.

That would both allow users to be notified of new features, and not interrupt their work at the same time, can you consider this ?

**Comment by NatoBoram** [comment]
@LukeOrdelmans upstream feature request is now there:

* https://github.com/microsoft/vscode/issues/102139

**Comment by roshal** [comment]
`What's New in Bookmarks`

this annoying tab in every open window of which we have several dozen open

a lot of work to carefully read and close each one

excellent mechanism

**Comment by philippludwig** [comment]
Kinda funny how this issue is still going strong, and nobody just forked the Extension and maintains a fork without this feature (its licensed under the GPL after all).

Personally, I don't use VSCode anymore, but I still receive E-Mails and notifications about this.

**Comment by kankaristo** [comment]
To hide the "What's new" window, you can modify VSCode `globalStorage`, and say that the installed plugin version is e.g. 999.0.0, so that the plugin doesn't know when it's upgraded. I might be dumb posting this on here, since the extension author might change the logic to work around this, but anyway...

I use a Bash script to open VSCode (to open multiple windows), so I added this to that script (use at your own risk):
```bash
#
# Hide the "What's new" page for some VSCode extensions.
#
function hideWhatsNew {
    globalStoragePath="$HOME/.config/Code/User/globalStorage/state.vscdb"
    if [ ! -f "$globalStoragePath" ]; then
        >&2 echo "ERROR: Cannot find VSCode globalStorage SQLite file: $globalStoragePath"
        return 64
    fi
    if ! command -v sqlite3 &> /dev/null; then
        >&2 echo "ERROR: Command not found (not installed?): sqlite3"
        return 65
    fi
    
    # alefragnani.Bookmarks
    sqlite3 "$globalStoragePath" \
        "UPDATE ItemTable SET value = json_set(value, '$.\"Bookmarks.version\"', '999.0.0') WHERE key = 'alefragnani.Bookmarks';"
    # alefragnani.numbered-bookmarks
    sqlite3 "$globalStoragePath" \
        "UPDATE ItemTable SET value = json_set(value, '$.\"numbered-bookmarks.version\"', '999.0.0') WHERE key = 'alefragnani.numbered-bookmarks';"
    # alefragnani.project-manager
    sqlite3 "$globalStoragePath" \
        "UPDATE ItemTable SET value = json_set(value, '$.\"project-manager.version\"', '999.0.0') WHERE key = 'alefragnani.project-manager';"
}

# Call the above function before starting VSCode:
hideWhatsNew
```

**Comment by philipbel** [comment]
This "feature" is annoying, and the author's attitude towards users' feedback is rather disappointing.

**Comment by Sundava** [comment]
I switched to another bookmark extension so I don't have a dog in this fight anymore, but I must say that's a weird hill to die on.

**Comment by smktpd** [comment]
> I switched to another bookmark extension so I don't have a dog in this fight anymore, but I must say that's a weird hill to die on.

Which one? Please, link it.
