### ISSUE TITLE
 command 'bookmarks.toggle' not found

### ISSUE THREAD

**Issue by xenefix** [alefragnani/vscode-bookmarks#178]
It seems version alefragnani.Bookmarks-10.2.1 will show the error `command 'bookmarks.toggle' not found` when I install it on a clean vscode installation.

After deleting the install, followed by installing [alefragnani.Bookmarks-10.2.0.vsix](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/alefragnani/vsextensions/Bookmarks/10.2.0/vspackage) the extension seems to work as expected, after which I can upgrade it to 10.2.1 .

My operating system: macos, however I'm able to replicate the exact behaviour on a clean windows VM on Azure with only vscode installed using ninite. Also on this windows machine manually installing 10.2.0, uninstalling and then installing 10.2.1 the usual way makes it work again.

Debug output:
![](https://i.imgur.com/KMJdYQo.png)

**Comment by alefragnani** [comment]
I can confirm that 😞 .
I'll fix it ASAP. I hope a new release later today.

Thanks for reporting

**Comment by YuryTheName** [comment]
Aaand, it's back.

**Comment by alefragnani** [comment]
@YuryTheName it's not the same _root cause_, and is already reported in #395.
