### ISSUE TITLE
Produce error when the bookmarked file is not open

### ISSUE THREAD

**Issue by EddiG** [alefragnani/vscode-bookmarks#18]
Steps to reproduce:
- Open folder
- Open any file and set bookmark in any line
- Close editor
- Press F1 and select Bookmarks: List

VSCode show:

> Error "Running the contributed command:'bookmarks.list' failed."

If file editor has opened, then all works.

_Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:00:07.223Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1_

**Comment by alefragnani** [comment]
Hi @EddiG ,

I could reproduce the problem. I will post a fix in the next release

Thanks :+1:

**Comment by EddiG** [comment]
Thank you for useful extension!

2016-03-02 21:28 GMT+05:00 Alessandro Fragnani <notifications@github.com>:

**Comment by alefragnani** [comment]
The same occurs for the other commands (`toggle`, `jump to next`, `jump to previous` and `clear`)
