### ISSUE TITLE
core repository is private

### ISSUE THREAD

**Issue by Frizi** [alefragnani/vscode-bookmarks#185]
Hi, I can see that you've recentlty changed the project structure to extract some parts of code to external repositories. Those repositories are unfortunately private. I suspect it's not intentional. Could you make it public if it's just a mistake or clarify the situation if it isn't?

**Comment by alefragnani** [comment]
Hi @Frizi ,

Yes, it is intentional.

I'm making some changes to the extension, and it would take a couple of weeks before new releases.

Stay tuned
