### ISSUE TITLE
mark jump one line

### ISSUE THREAD

**Issue by rmlSardinha** [alefragnani/vscode-bookmarks#187]
some lines above a mark, do the following sequence

ctrl + enter
ctrl + enter
ctrl + z

the marking below will skip a line

**Comment by rmlSardinha** [comment]
and if you use several enter, when using the ctrl+z, marking jumps multiple lines

**Comment by alefragnani** [comment]
Hi @rmlSardinha ,

Probably a duplicate of (or related to) #116 . 

Thanks for reporting
