### ISSUE TITLE
Issue when Format Document

### ISSUE THREAD

**Issue by glennmichaelmejias** [alefragnani/vscode-bookmarks#188]
All bookmarks are lost when I use Format Document in Flutter.

**Comment by alefragnani** [comment]
Hi @glennmichaelmejias ,

You may be facing the same problem described in #118 . I have developed a [workaround](https://github.com/alefragnani/vscode-bookmarks/issues/118#issuecomment-442686987), until a proper API is available in VS Code, and my extension is _notified_ about code format.

Add `"bookmarks.useWorkaroundForFormatters": true` to your user settings, and the bookmarks should stop to disappear.

Hope this helps
