### ISSUE TITLE
Jump to bookmark and mark word, if it was marked when the bookmark was created

### ISSUE THREAD

**Issue by jamilraichouni** [alefragnani/vscode-bookmarks#191]
Hi!

First:
Many thanks for this extension!

Second:
Don't know, how to raise a feature request respectively if there's a better place to do so.

Third:
In SublimeText I love the following behaviour:
When one marks (selects) a term or word in the code and then creates a bookmark, the term/ word will also be selected/ highlighted when I later jump to this bookmark. This is quite helpful and it would be highly appreciated if such behaviour was implemented into some future release of your extension.

Many thanks and all the best!

**Comment by alefragnani** [comment]
Hi @jamilraichouni ,

First of all, thank you for your suggestion 👍 

Right now, the extension only stores/restores the `column` position, but doesn’t  _updates_ the value if the line text changes, like it does with the `line` position. So, before adding _selection_ to the bookmark, it would be needed to change that behavior. In fact, it would be necessary to also support _multi-line_ selection, which would turn the bookmark a `Range`, not a `Position`.

Well, right now, I’m focusing in other areas of the extension, so I won’t be able to look at this. But after that, I could take a look and see if something simpler could be done.

Thank you

**Comment by jamilraichouni** [comment]
Hi!

Thanks for your response!

You're right, a bookmarkable region (even if it's just a position = a range with a length of zero) would be fantastic! Good point and I see, that's what bookmarks in SublimeText do, when you jump back to them.

Hope that there will be a day where you'll find the time to make such an improvement.

All best!

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
