### ISSUE TITLE
No commands available

### ISSUE THREAD

**Issue by longv2go** [alefragnani/vscode-bookmarks#192]
I install the bookmarks extension. I click `cmd + shift + p` there is no commands 'bookmarks: *' available.

**Comment by alefragnani** [comment]
Hi @longv2go ,

This is probably some issue with the installation process. Please, reload VS Code and check if the extension appears in the **Extensions** Side Bar. Also, look at `Toggle Developer Tools / Console` and see if there is some error logged.

Hope this helps.

**Comment by callisto2410** [comment]
I think this is due to forced localization, for example, I cannot turn on English localization and therefore commands via "bookmarks" are not available.

Please add an option to select the language of the interface.

**Comment by longv2go** [comment]
> I think this is due to forced localization, for example, I cannot turn on English localization and therefore commands via "bookmarks" are not available.
> 
> Please add an option to select the language of the interface.

It works for me!!!, thanks! I refer to https://code.visualstudio.com/docs/getstarted/locales,  install the Chinese language extension and change display language to 'zh-ch'. The "bookmarks" commands are available.

**Comment by alefragnani** [comment]
@callisto2410 ,

The locale/translation is defined and handled, by VS Code itself. The extensions just have to provide the locale resources (`.nls` files), in this case, the localised texts for each command and setting (messages still not available). 

If you are having issues with VS Code/extension because some extension does not have specific translation, this must be handled by VS Code, because it needs to work even for non-localised extensions. So I suggest you to open an issue in VS Code repo.

Hope this helps

**Comment by callisto2410** [comment]
> @callisto2410 ,
> 
> The locale/translation is defined and handled, by VS Code itself. The extensions just have to provide the locale resources (`.nls` files), in this case, the localised texts for each command and setting (messages still not available).
> 
> If you are having issues with VS Code/extension because some extension does not have specific translation, this must be handled by VS Code, because it needs to work even for non-localised extensions. So I suggest you to open an issue in VS Code repo.
> 
> Hope this helps

Thanks for the advice, but I think I just broke something when I changed the localization settings.

Editing the file "locale.json" solved my problem, I just decided to tell about it when I saw that other people had similar problems.

**Comment by alefragnani** [comment]
Glad to hear it's working. I'll keep the issue _bookmarked_ for future references 👍
