### ISSUE TITLE
Support saveBookmarksInProject option in Workspaces/Multi-root scenarios

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-bookmarks#193]
In #82 (
https://github.com/alefragnani/vscode-bookmarks/issues/82#issuecomment-343691392) I decided that `saveBookmarksainProject` wouldn’t be supported.

This issue is to change that, and make it supported.

The idea is to read/write the bookmarks stored in each root folder contained in the workspace.

**Comment by Pytal** [comment]
Can you point me in the right direction regarding this feature implementation?
