### ISSUE TITLE
Auto-Bookmarks

### ISSUE THREAD

**Issue by mbaas2** [alefragnani/vscode-bookmarks#194]
I would find it useful if I could have an option to specify a regex that would (when found) automatically set a bookmark for the line that matched that bookmark. Maybe we could dream about having "groups" of bookmarks, where "manual" is one and each regex could have a "Group"-attribute that would define the label of the corresponding group.

**Comment by alefragnani** [comment]
Hi @mbaas2 ,

This will be achieved with #77 . 

Instead of _add search functionality_ to Bookmarks, I preferred to _support multi-select_, because this way, you will have all the power VS Code search provides. Also, I will be less limited to the VS Code API, like happened to #7 .

Hope this helps.
