### ISSUE TITLE
Can I automagically set bookmarks on File|Open?

### ISSUE THREAD

**Issue by mbaas2** [alefragnani/vscode-bookmarks#195]
Been thinking of alternative ways to achieve the idea described in#194 and had this idea:
- wouldn't it be nice if File/Open could execute a macro?
- and in that macro I could perform a search for certain regex and for every match
  - jump to the corresponding line
  - extract a description (using regex on the line)
  - set a labelled bookmark for that line.

Unfortunately I'm a VSCode newbie - so I don't know if that is doable at all. If someone with more experience could point out if this is doable (perhaps with some URLs to study relevant techniques) I would appreciate it :-)

**Comment by alefragnani** [comment]
Hi @mbaas2 ,

I think it’s doable, and it probably already have some extension that run “some code” when you open a file.

If you want to try coding this yourself,, the first step is to look at VSCode documentation to understand [how to create an extension](
https://code.visualstudio.com/api) It provides an scaffolding for a hello world.

You will end up registering an event, like 
https://github.com/alefragnani/vscode-bookmarks/blob/6b5d0ef62b0b870ab6f9471998bb6f19e87c71d4/src/extension.ts#L109

Then you add what you want to do when opening a file. You can run your regex and “find” the important pieces of text, and then, call the `Bookmarks: Toggle Labeled` command.

Hope this helps

**Comment by alefragnani** [comment]
I think I have a test extension that does “something like that”. 

I’ll try to find it, and post here, so you could play a little 😁

**Comment by alefragnani** [comment]
Hi @mbaas2 ,

To create your test extension, you should follow [this instructions](https://code.visualstudio.com/api/get-started/your-first-extension). After that, you could add the simple code below. 

```typescript
    // This event executes everytime you open a file
    vscode.workspace.onDidOpenTextDocument(doc => {

        if (!vscode.window.activeTextEditor) {
            return;
        }

        // log some stuff - just to discover what you have available
        console.log(`filename: ${doc.fileName}`);
        console.log(`lineCount: ${doc.lineCount}`);

        // search what you want - naive solution :-)
        for (let index = 0; index < doc.lineCount - 1; index++) {
            const line: string = doc.lineAt(index).text;
            if (line.trim().startsWith("###")) {
                // select the line - moves the cursor to the desired position
                const newSelection = new vscode.Selection(index, 0, index, doc.lineAt(index).text.trim().length);
                vscode.window.activeTextEditor.selection = newSelection;

                // toggle a bookmark (no label) at the selection position
                vscode.commands.executeCommand("bookmarks.toggle"); 
                return;
            }         
        }
    });
```

_It's just that_. 😀 

There is only one issue. The `Toggle Labeled` command does not support `parameters`, so you won't be able to use it as you wanted. I'm not sure if this is _possible_ (I guess it is), but I should have to dig a little deeper in documentations to discover that. If you find anything, please let me know.

Hope this helps
