### ISSUE TITLE
export bookmarks as an image

### ISSUE THREAD

**Issue by compilelife** [alefragnani/vscode-bookmarks#196]
Hi there, any plan to add an function that would export bookmarks as an image, which can be use to show the main outline of a log file?

Something like this
![image](https://user-images.githubusercontent.com/3362269/54910445-4d41fd80-4f27-11e9-9fc6-db7ff5199cc0.png)

> From the image above , we can quickly point out that an anr happened at line 3000, 17:00. And  this anr is caused by long time operation at line 2700, 18:52. Then the others can easily dig into the details base on this "map".

It's very useful for peoples to discussing software errors base on a log file.

**Comment by alefragnani** [comment]
Hi @compilrlife,

Not _yet_. 

I mean, exporting Bookmarks as text appears to be a normal operation, because with that, you may do whatever you want with that information.
Your request is interesting, but I'm wondering its dayly use. To me, that picture appears to be the Minmap, right? Have you seen any other extensions that exports a "visual representation" of the Minimap? I searched at VSCode repo but didn't find anything, unfortunately.

I can't promise you anything, but I'll take a look.

Hope this helps

**Comment by compilelife** [comment]
Thanks for your reply.

> To me, that picture appears to be the Minmap, right?

Yes, It's a minmap.

>  but I'm wondering its dayly use

Yes, Not quite frequent. Usualy needed for reporting log analysis result.

>  exporting Bookmarks as text appears to be a normal operation

Exporting as text would be helpful too.  But  for me, exporting as image would be more straightforward. However, with text exported I could write a seperate tool to convert it to image.

Only problem is exporting single file's bookmarks. Any way could do that ?

**Comment by alefragnani** [comment]
> Only problem is exporting single file's bookmarks. Any way could do that ?

There is no export command _yet_, but there is already an issue #172 asking. Another option is to use `saveBookmarksInProject` option, which will save the bookmarks in `.vscode/bookmarks.json` file. But be aware that this setting does not work for multi-root projects (workspaces)

> Exporting as text would be helpful too. But for me, exporting as image would be more straightforward. However, with text exported I could write a seperate tool to convert it to image.

Would this "separate tool" to be a JS/TS library? If

**Comment by alefragnani** [comment]
I'm closing this issue in favor to the simpler solution, #172, once you wrote you could create a separate tool yourself to generate the image (maybe a contribution in the future 😁 )
