### ISSUE TITLE
[Help] Only show filename in sidebar?

### ISSUE THREAD

**Issue by ddzy** [alefragnani/vscode-bookmarks#204]
## Current Feature
As the **absolute path** may be deep, like this:
![gayhub_issue_1](https://user-images.githubusercontent.com/33921398/55955767-d893f080-5c94-11e9-9637-7b6c95cb1586.png)

## Expected Feature
I want it to display only the **filename** or **relative path**, how can i do?

**Comment by alefragnani** [comment]
Hi @ddzy ,

This is not possible _yet_, and btw, is already being tracked in #149, 

Please, upvote the original issue 😁 

Hope this helps.
