### ISSUE TITLE
bookmarks path do not crossplatform

### ISSUE THREAD

**Issue by scutterry** [alefragnani/vscode-bookmarks#205]
it is NOT work correctly while i saving the bookmarks on project (.vscode/bookmarks.json) crossing the windows and mac. the problem is the PATH. Adding a same bookmark in different system. as follow:
on mac will be this ---"$ROOTPATH$/doc/doc.md"
on windows will be this ---"$ROOTPATH$\\\\doc\\\\doc.md"
every time a need to transform "\\\\" to "/" (on the contrary “/” --> "\\\\") MANUAL

the bookmarks version is 10.4.3

**Comment by alefragnani** [comment]
Hi @scutterry ,

I only have Windows available, so cross platform was never an issue/priority.

Thanks for reporting.
