### ISSUE TITLE
Bookmarks deleted on auto-formatting

### ISSUE THREAD

**Issue by marcellourbani** [alefragnani/vscode-bookmarks#207]
If I save a file with autoformatting on, the bookmarks in that file get deleted

I use code 1.33.1 with the current prettier formatter
Saving without autoformat works fine

![deldetebookmark](https://user-images.githubusercontent.com/2453277/56714412-a373ad80-672c-11e9-82c4-a62bb8100208.gif)

**Comment by marcellourbani** [comment]
PS: this only happens when the autoformatting actually does something.
If your code is already formatted like prettier wants nothing happens

**Comment by alefragnani** [comment]
Hi @marcellourbani ,

This has already been reported (https://github.com/alefragnani/vscode-bookmarks/issues/118), and I have created a workaround. 

You have to add a new setting to you User Preferences (`"bookmarks.useWorkaroundForFormatters": true`). 

Hope this helps.

**Comment by marcellourbani** [comment]
Oh great!
Sorry for the duplication, I did look for it but failed.
Thanks a lot.
Sadly I'm stuck on 9.3+ my patches, but can always backport it ;)

**Comment by alefragnani** [comment]
No need to be sorry. It happens 👍 .

The workaround commit is [this one](https://github.com/alefragnani/vscode-bookmarks/commit/b13e47e42c8474ec327c5aca98e2feec57c96234). It should be easy for you to reapply your patch, until it is merged to the master branch.

Hope this helps

**Comment by marcellourbani** [comment]
Thanks
I already did, although with a small change:
``` javascript
    vscode.workspace.onDidChangeTextDocument(event => {
...
            const preventDelete = vscode.workspace.getConfiguration("bookmarks").get("useWorkaroundForFormatters", false)
            updateDecorations(preventDelete);
...
}, null, context.subscriptions);
...
    function updateDecorations(preventDelete = false) {
...
            let invalids = [];
            if(!preventDelete)
                for (let element of bookmarks.activeBookmark.bookmarks) {

                    if (element.line <= activeEditor.document.lineCount) { 
                        let decoration = new vscode.Range(element.line, 0, element.line, 0);
                        books.push(decoration);
                    } else {
                        invalids.push(element);
                    }
                }
...
}
```
If I got this right it will stop removing bookmarks but still adjust them when it manages to
Didn't look much into it before coding it, might as well have broken something...
Will let you know how it goes
