### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jehillert** [alefragnani/vscode-bookmarks#208]
Hi,
Your extension is awesome. Very clean, very useful. Which is to say this feature request is more "wouldn't it be nice", and less "customer complains about free product"...

It would be great if there was an option to display the bookmarks in the sidebar as a flattened list, instead of being nested by filename. So as an alternative to the nested list:

v  FileA.js
    BM1_code...
    BM2_code...
    BM3_code...
v FileB.sql
    BM4_code...
    BM5_code...
    BM6_code...

A setting would cause the bookmarks to be displayed like so:

  (FileA.js) BM1_code 
  (FileA.js) BM2_code 
  (FileA.js) BM3_code 
  (FileB.sql) BM4_code 
  (FileB.sql) BM5_code 
  (FileB.sql) BM6_code 

To address long filenames and space taken up by file extensions, maybe the filenames could be truncated after a few characters, and/or the file extensions omitted or replaced with color coding (e.g., yellow for javascript, white for C++, etc).: 

  (Long...) BM1_code 
  (Long...) BM2_code 
  (Long...) BM3_code 
  (Short) BM4_code 
  (Short) BM5_code 
  (Short) BM6_code

**Comment by alefragnani** [comment]
Hi @jehillert ,

Thank you for your kind words. I'm glad to know you like the extension.

About your request, a _similar_ issue already exists (#149). What do you think about it?

Hope this helps

**Comment by jehillert** [comment]
Hi, thanks for responding. I will put my feedback about #149 on the #149 page so everything is in one place.
