### ISSUE TITLE
Renaming of File in VSCode results in "ghost" bookmarks

### ISSUE THREAD

**Issue by pwahlmueller** [alefragnani/vscode-bookmarks#209]
When you change the filename in VSCode, the bookmark is still on the old filename. 
It should be changed, so the bookmark will mark the line in the new file. 
It is also not possible to change the filename at the bookmark section.

**Comment by alefragnani** [comment]
Hi @pwahlmueller ,

This was a known issue (already reported in #80), but wasn’t priority at the time.

But, rename a file right from the side bar, on the other hand, wasn’t something that I intended to do 😬 .  Please, fill another issue (Feature Request) for that.

Thanks for reporting

**Comment by alefragnani** [comment]
Should use onDidRenameFiles event, described in https://code.visualstudio.com/api/references/vscode-api#workspace

**Comment by fade2gray** [comment]
Just an FYI: When I encountered this problem, I managed to transfer the bookmarks to the renamed file by editing the file path using an SQLite database editor.

**Comment by alefragnani** [comment]
Hi @fade2gray ,

Yes, that's possible. I used to look (for debugging purposes) at the LocalStorage in the Developer Tools.  Unfortunatelly VS Code team changed that to files in disk 😞 .

But for this fix, I'll have to handle the `onDidRenameFiles` event and update the bookmarks manually.
