### ISSUE TITLE
Default bookmarks.navigateThroughAllFiles to true

### ISSUE THREAD

**Issue by JVimes** [alefragnani/vscode-bookmarks#21]
I expect bookmarks to behave like in Visual Studio, so bookmarks.navigateThroughAllFiles should default to true. I'm not sure if this even needs to be configurable.

**Comment by alefragnani** [comment]
Hi @JVimes ,

I understand, but I prefer to keep the same behavior of previous version when new features are added. Unfortunately there is no way to the user to know what's new in extensions updates, so you end up being forced to go to the `readme. Thinking about it, I try to put all the information about each released version, so you can see how it is evolving.

Thanks.
