### ISSUE TITLE
Bug: Ctrl + Alt + L jumps to only to bookmarks in current file... won't jump to bookmarks in other files

### ISSUE THREAD

**Issue by milost1982** [alefragnani/vscode-bookmarks#210]
Ctrl + Alt + L or Ctrl + Alt + J won't jump to bookmarks that are outside file currently active in VS Code tab. I thought and expected that jumping to next/prev bookmarks will work no matter in which file bookmarks are and no matter which file is currently open/active?

**Comment by alefragnani** [comment]
Hi @milost1982 ,

It support this behavior, but you have to change one setting:

```json
"bookmarks.navigateThroughAllFiles": true
```

After that, the bookmarks navigation will go outside the current file.

There is already an issue (#102) to change the default behavior to be `true`. 

Hope this helps
