### ISSUE TITLE
Explorer setting?: See only bookmarks of the current file in focus

### ISSUE THREAD

**Issue by timgatzky** [alefragnani/vscode-bookmarks#211]
Hi there,
thanks for this super useful extension! 
Maybe I missed a setting already existing but I miss a toggle for the explorer between seeing all bookmarks in the workspace (current state) or just of the file in focus / current file editing.
Is there a setting available?

Thanks in advance, Tim

**Comment by alefragnani** [comment]
Hi @timgatzky ,

There is no such setting. The **Side Bar** always shows all bookmarks from the opened _workspace/folder_. 

If you want to see only the bookmarks from the current file only, you should use the `Bookmarks: List` command, which will show the bookmarks in the **Command Palette** not the **Side Bar**.

I think you are asking something like the **Outline** panel, recently added in VS Code, which shows the Symbols from the current file. This panel however, is shown in **Explorer** view, not on its own Side Bar. If that's the case, it's a **new feature**.

Hope this helps

**Comment by timgatzky** [comment]
Hi there,
thanks for your support.
I'm switch from Coda2. In Coda there is a so called Navigator - pretty much the Outline panel. 
In Coda you can define custom "anchors" per File, just like your bookmarks, by typing a "!" in a command e.g. // !bookmark
This is very handy when working with a lot of bookmarks/anchors over a lot of files. I like your Explorer better because mixing programming language stuff and booksmarks are two pair of shoes. But when working with a lot of files and a lot of booksmarks the explorer get's packed pretty fast. That why I'm asking.

Maybe it can be archived in an upcoming version. Would be awesome to have a setting to toggle that.
Also a simple inline-tag like Coda would be cool when working with other people sharing the same file. We used that a lot for pointing out important notes between each other.

**Comment by alefragnani** [comment]
Hi @timgatzky .

I think you are asking something like #128. If that's the case, I suggest you to look at the extensions that I suggested there.

Otherwise, if it's just and **File Bookmark** panel in **Explorer** Side Bar, it still could be added in the future.

Hope this helps

**Comment by timgatzky** [comment]
Yes. Bookmarks from comments is pretty much it. That would help a lot, especially when switching workspaces but working on the same file.

**Comment by alefragnani** [comment]
I'm closing the issue because the original request was solved, as you commented above, by using other extensions listed in #128. 

I kept the issue open because I thought about adding a **File Bookmark** panel in **Explorer** Side Bar, but in the end, it didn't receive any 👍 , so I guess it's not not as useful as I thought 😄 .
