### ISSUE TITLE
Add 'Jump to previous' bookmark independent of open file

### ISSUE THREAD

**Issue by nikitavoloboev** [alefragnani/vscode-bookmarks#216]
Currently both `Jump to next` and `Jump to previous` actions will jump to a bookmark only when you are in the file with the bookmark.

I often like to mark a line I am working on now in a project and go view definition of things in some file, jump around. I then want to press a hotkey and instantly go to my last placed bookmark (anywhere in the project).

Can you please support this use case? 

Thanks.

**Comment by nikitavoloboev** [comment]
I see there is search bookmarks across all files so I believe it should be possible to implement an instant jump to last bookmark placed (globally).

**Comment by alefragnani** [comment]
Hi @nikitavoloboev ,

It does not support _jump to the last bookmark_ like a Stack, but it supports to jump to bookmarks on _other files_ (even closed files), if you a change one setting:

```json
"bookmarks.navigateThroughAllFiles": true
```

There is already an issue (#102) to change the default behavior for this setting to be `true`. 

Hope this helps

**Comment by nikitavoloboev** [comment]
Thanks
