### ISSUE TITLE
bookmarks tells me to "open file" in an open file

### ISSUE THREAD

**Issue by aplatypus** [alefragnani/vscode-bookmarks#220]
I have just installed Bookmarks 10.

I wen to set a book mark in an open text file (see screenshot).  I wanted to book mark the line showing "OUT_OF_SYNC" as shown.

All I seem to get are messages telling me to "Open a file to toggle bookmark".

![image](https://user-images.githubusercontent.com/67028/59578067-ce192b80-9109-11e9-93a9-e575490a3c6c.png)

I have closed VS Code and restarted.  The file is open and my cursor is on the line I wanted to bookmark.  I can edit the line for example.

This is the first time I've used this extension -- Or tried to use it.  Since it is currently unusable.  The log file I'm looking at never existed before this hour.  So there is no 'history' or options that might be set to make prevent this feature working.

Either the error message is a mistake or I need to know about some kind of setting to "enable" the bookmark feature.

How can I get this plugin to work?

Also EVERY book mark type command I give gives me the same problem -- open a file to do "operation".  

There are several instances of thi serror reported previously they are all closed.  The earliest I saw is 2017 -- This is now 2019.

*  Open a file first to toggle bookmarks #68
*  "Open a File First to toggle bookmarks" #44
*   Unable to open all file bookmark list #50 

I stopped recording them 

**VSCode version**

    Version: 1.35.1
    Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
    Date: 2019-06-12T14:27:31.086Z
    Electron: 3.1.8
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 5.0.7-050007-generic

**Comment by alefragnani** [comment]
Hi @aplatypus ,

I have noted your file has more than 299,296 lines, so I suppose you are facing the **large file** issue, reported a few times (#44, #31, #68, etc). 

Unfortunately, this is a VS Code limitation, as reported in https://github.com/Microsoft/vscode/issues/3147 and updated in https://github.com/Microsoft/vscode/issues/6474#issuecomment-285010621. If the file is larger than _the defined limit_, VS Code simply does not _activate_ the extension properly, and things like that happens.

If that is the case, there is nothing I can do in the extension to _fix_ the issue. Sorry.

Hope this helps
