### ISSUE TITLE
Configurable keyboard shortcuts

### ISSUE THREAD

**Issue by unl1ght** [alefragnani/vscode-bookmarks#228]
The default keyboard shortcuts for toggling bookmarks and jumping between bookmarks are not compatible with some Linux distributions. In my case (Ubuntu + KDE) these shortcuts are used by the OS to lock the user session or switch keyboard layouts. Would it be possible to make the shortcuts configurable through settings?

**Comment by alefragnani** [comment]
Hi @unl1ght ,

Yes, you can configure different shortcuts for each command. You just have to use the `Preferences / Open Keyboard Shortcuts` command from VS Code. 

Please, follow [this instructions](https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts) from VS Code documentation.

Hope this helps
