### ISSUE TITLE
[dev question] How do you make that "What's new" page? 

### ISSUE THREAD

**Issue by felixjb** [alefragnani/vscode-bookmarks#229]
I am also developing a VSCode extension, [Testify](https://github.com/felixjb/testify), and I want to make a "What's new" page pop up when I release a new version. The problem is that I can't find anywhere in the VSCode docs how to do this.

Please help a dev friend :sweat_smile:

**Comment by alefragnani** [comment]
I just answered you by e-mail :-)
Hope I have helped you...
