### ISSUE TITLE
Running the contributed command:'bookmarks.toggle' failed

### ISSUE THREAD

**Issue by GaryFurash** [alefragnani/vscode-bookmarks#23]
do you know why it would do that. I had developer's console on but that's all it said.

**Comment by alefragnani** [comment]
Hi, 
Which OS and VScode version are you using? Also, does any other `bookmarks` command works?

Let's try to figure out what's going on.

**Comment by GaryFurash** [comment]
Sorry for giving you so little information!

Actually, I think I figured it out. it was an unknown file type. As soon as i tried using it in something else (e.g., ".bat") file it worked fine! Sorry

**Comment by alefragnani** [comment]
No need to be sorry :smile: Good to know that it is working now.

But, what do you mean about _unknown file type_? It should work for every file, no matter the _file type_ (extension), _unsaved_ (untitled) nor _preview_ (one click in treeview).

If you still can reproduce the problem, just gives me the steps to reproduce, or record a video/animateg gif.

Thanks in advance
