### ISSUE TITLE
Support Remote Development 

### ISSUE THREAD

**Issue by delperugia** [alefragnani/vscode-bookmarks#230]
Hi,

when editing a remote file using Remote Development (at least with WSL, SSH/container not tested), the bookmarks are not shown but navigation is working. The minimap shows them.

Tested with version 10.5.0 on two different computers. FYI: same problem exists with Numbered Bookmarks 6.2.1.

Attached a capture with two VSC, one connected to WSL (Ubuntu), the other local. Both editors with bookmarks set on lines 3 and 6.

Regards

![capture](https://user-images.githubusercontent.com/45607421/63327794-2f8a9000-c32f-11e9-9b9c-9ce3ebf1dd2a.png)
[vsc_version.txt](https://github.com/alefragnani/vscode-bookmarks/files/3519251/vsc_version.txt)

**Comment by alefragnani** [comment]
Hi @delperugia ,

Yes, the extensions (both) still does not fully support Remote Development. It’s on _radar_ but no ETA yet.

Thank you for reporting.

**Comment by alefragnani** [comment]
I just noted that installing the extension on the remote (at least docker variation - `devcontainer.json`) the extension works. 

But my intention is to bring Bookmarks to the Host, with no need to _install_ on remote
