### ISSUE TITLE
Support keyboard shortcut make [jump to next/previous] cross files

### ISSUE THREAD

**Issue by Dkra** [alefragnani/vscode-bookmarks#233]
When I use the shortcut to move between bookmarks, it limited in the currently active file.

Could this support navigate between files?

**Comment by alefragnani** [comment]
Hi @Dkra ,

It support this behavior, but you have to change one setting:

```json
"bookmarks.navigateThroughAllFiles": true
```

After that, the bookmarks navigation will go outside the current file.

There is already an issue (#102) to change the default behavior to be `true`. 

Hope this helps

**Comment by Dkra** [comment]
@alefragnani, Awesome!
Thanks for the reply!
