### ISSUE TITLE
bookmarks.json does not ignore when added to .gitignore

### ISSUE THREAD

**Issue by capegreg** [alefragnani/vscode-bookmarks#234]
bookmarks.json does not ignore when added to .gitignore

 !.vscode/bookmarks.json

Visual Studio Code

**Comment by alefragnani** [comment]
Hi @capegreg ,

The `bookmarks.json` will not be ignored (if you mean by that, _be created_) when defined in `.gitignored`. Instead, will not be _recognized_ by Git.

I simply added this pattern (`bookmarks.json`) in `.gitignore` file and the `.vscode/bookmarks.json` file stopped from being recognized by Git.

Hope this helps
