### ISSUE TITLE
Use selected text as current label

### ISSUE THREAD

**Issue by ogamal** [alefragnani/vscode-bookmarks#239]
Is it possible to use selected text as label for new bookmarks (if selected text is a one-line)? Such feature would allow faster bookmarking of functions, classes, .. etc.

Suggested use-case:
1. Select function/class name
2. Press "Ctrl + Alt + k" to bookmark and instantly use the selected text as label

Old use case:
1. Select function/class name
2. Press "Ctrl-C" to copy name
3. Press bookmark short cut "Ctrl + Alt + k" to bookmark
4. Click on bookmarks icon in activity bar
5. Find the bookmark, right click it, and choose "Edit label"
6. Paste the function/class name

New flow makes it easier to bookmark with meaningful labels while focusing on code. Specially when the beginning of the line isn't very meaningful text. For instance you can come through a long line like that in C++ file:
`std::unordered_map<unsigned int, std::vector<std::vector<int>> ClassName::FunctionName()`

It becomes essential to rename this bookmark to "FunctionName" to be able to spot it easily in the bookmarks sidebar.

**Comment by alefragnani** [comment]
Hi @ogamal ,

Thank you for your suggestion 👍 . I don’t use labeled bookmarks, but I agree it’s a great improvement.

But, I wouldn’t change the _default_ `Toggle` bookmark command to use the selected text, but instead, make the `Toggle Labeled` to use it. BTW,  I’m not sure you know about it, because in your _Old use case_ scenario, you used the Side Bar to label the bookmark. Also, it would have a setting to define this behavior (default on).

Hope this helps

**Comment by ogamal** [comment]
@alefragnani I didn't know about `Toggle Labeled`. That's useful in my use-case and saves few steps. It would be great if it is possible to make it default and even better if it can populate from selected text.

Thanks,

**Comment by alefragnani** [comment]
> @alefragnani I didn't know about Toggle Labeled. That's useful in my use-case and saves few steps

That’s great!

>  It would be great if it is possible to make it default and even better if it can populate from selected text.

That’s the idea. In fact, I’m thinking about:

- Don’t use (like today)
- Suggest (as you asked)
- Use (automatic)

It would fulfill _any_ scenario 😬

**Comment by ogamal** [comment]
@alefragnani Sounds great!

**Comment by marveloo** [comment]
My two cents on how it could be implemented:

- `Toggle Labeled` should prefill the label's textbox with the selected text if there is any. 
- `Toggle Labeled` should prefill the label's textbox with the code of the current line if nothing is selected. 
- And in both of the cases above the prefilled text in the textbox should be preselected so that I could start entering my own new custom label in case I am not interested in the prefilled text.

**Comment by alefragnani** [comment]
Based on your feedback, I designed 4 possible suggestions. Choose the one better fit your needs, and define it in `Preferences: Settings`

  * `dontUse`: Don't use the selection (original behavior - default value)
  * `useWhenSelected`: Use the selected text _(if available)_ directly, no confirmation required
  * `suggestWhenSelected`: Suggests the selected text _(if available)_. You still need to confirm.
  * `suggestWhenSelectedOrLineWhenNoSelected`: Suggests the selected text _(if available)_ or the entire line (when has no selection). You still need to confirm

```json
    "bookmarks.label.suggestion": "useWhenSelected"
```

This feature should be released this weekend. 

Stay tuned

**Comment by nvdl** [comment]
For some reason, `"bookmarks.label.suggestion": "useWhenSelected"` in user settings does not work for me. I select some text through double click and press "Ctrl+Alt+k" but it still chooses the whole line as the label. Any suggestion?

VSCode information:

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 4.15.0-204-generic snap
Sandboxed: No

**Comment by alefragnani** [comment]
Hi @nvdl ,

The <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>K</kbd> shortcut is, by default, defined for the `Bookmarks: Toggle` command. The `Bookmarks: Toggle Labeled` command, on the other hand, has no shortcut. Unless you have changed the shortcut to be for the _labeled_ command, I suppose you are mixing the concepts here.

The default `Bookmarks: Toggle` has no label, and will always display the entire line _as a preview_. The `Bookmarks: Toggle Labeled` command, which uses the `bookmarks.label.suggestion` setting, displays the selected/typed label _instead_ of the line, as the preview.

By the way, the only setting that _automatically uses the suggestion_ is `useWhenSelected`. The other values will simply _suggest_, and you will have to confirm the label displayed in the input box.

Hope this helps

**Comment by nvdl** [comment]
OK, overriding the default behavior worked in user's JSON.

`
 {
        "key": "ctrl+alt+k",
        "command": "bookmarks.toggleLabeled",
        "when": "editorTextFocus"
    }
`

But, I can't toggle the label off via the shortcut.
I have to delete it from the list.
If I invoke the shortcut again on a bookmarked line, it asks me for a label again and if I clear the suggestion, it does not clear the bookmark.

Shouldn't it be to use whatever suggestion mode the user has specified for toggling on.
But if a bookmark is already there, it should be removed.

**Comment by alefragnani** [comment]
If you want to _remove_ the bookmark, labeled or not, you should use the `Bookmarks: Toggle` command.

The `Bookmarks: Toggle Labeled` command, when invoked on an already bookmarked line, will always ask for the label.

Hope this helps
