### ISSUE TITLE
Automatically bookmark lines matching predefined regex

### ISSUE THREAD

**Issue by hookxs** [alefragnani/vscode-bookmarks#241]
(Enhancement) Allow defining a regular expression (or better yet list of regular expressions) so that every line matching any of the regex will get a bookmark (unless it already has one). This way you can automatically and easily bookmark e.g. all function definitions, all section beginnings in LaTeX etc without having to open one file after another in an existing project and toggle bookmarks by manually. Also, it doesn't matter as much if such bookmarks are lost due to some issues with code sharing between multiple users/computers because these bookmarks would be re-created automatically.
Ideally, such automatically added bookmark would be removed if the regex no longer matches the line - i.e. this type of bookmark would be solely depended on the regex. I suppose this last bit may create some issues.

**Comment by alefragnani** [comment]
Hi @hookxs ,

The idea behind the Bookmarks extension is that _you define the positions_ which you think to be important, and to do that, you have to be there. 

An alternative to this _regex_ feature, is to allow **multi-cursor/selection** while defining bookmarks, which is being tracked in #77. So, you could search for any text/regex and _all your positions_ could be bookmarked at once.

I remember seeing a few extensions that uses regex to _find text_ in your worskace. If I remember correctly, mostly using the ToDo concept. I think these could help?

* https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
* https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus

Hope this helps
