### ISSUE TITLE
[Feature Request] Customizable shortcut keys

### ISSUE THREAD

**Issue by user9713** [alefragnani/vscode-bookmarks#244]
Instead of the default `ctrl` + `alt` + `j` / `k` / `l`, allow us to customize the shortcut keys

Why: those shortcut keys interfere with default windows programs (`ctrl` + `alt` + `l` for magnifier, in my case).

Thank you.

**Comment by alefragnani** [comment]
Hi @user9713 ,

Yes, you can configure different shortcuts for each command. You just have to use the `Preferences / Open Keyboard Shortcuts` command from VS Code. 

Please, follow [this instructions](https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts) from VS Code documentation.

Hope this helps
