### ISSUE TITLE
[Feature Request] Alt + left click gutter to add bookmark

### ISSUE THREAD

**Issue by jrm06c** [alefragnani/vscode-bookmarks#245]
It would be nice if holding the ALT key while left clicking the gutter would add a bookmark rather than a breakpoint.

**Comment by alefragnani** [comment]
Hi @jrm06c ,

I agree with you, and a similar issue has already been reported in 2016 #24, but I closed in 2018 because the VSCode team still didn’t released an API.

Please, upvote there https://github.com/microsoft/vscode/issues/5455.

Thank you
