### ISSUE TITLE
Support contributes.colors

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-bookmarks#246]
As described here https://code.visualstudio.com/api/references/contribution-points#contributes.colors

**Comment by alefragnani** [comment]
For now, I'll only add the `line background` (replacing `backgroundLineColor` setting - no migration), `line border` and `overviewRuler` to `contributes.colors`. 

In the future, I would like to update the `gutterIcon` as well, but first I need to update the bookmark svg.

**Comment by alefragnani** [comment]
This new feature will deprecate the `bookmarks.backgroundLineColor` setting, which were introduced  in version 9.3.0, via PR #133, being requested in #141 and #98 .

I thought about _automatically migrate_ the setting, but I don't like to _touch_ on user settings, specially when you have User, Workspace and Folder settings to take care of. Unfortunately, there is no API do know if a `ThemeColor` is defined, or which value it has, so I'm out of luck to know if the user has defined the color itself.

I'm thinking about _simply ignore_ the deprecated setting, and just use the `workbench.colorCustomizations` value (if available). This will force users which currently use the deprecated setting, to move to the new one. 

Since you, @lamartine @edgardmessias @Otiel, did participate in the original issues/PRs, do you have any comments?

**Comment by Otiel** [comment]
> I'm thinking about _simply ignore_ the deprecated setting, and just use the `workbench.colorCustomizations` value (if available). This will force users which currently use the deprecated setting, to move to the new one.

This is reasonable IMO.

**Comment by mbomb007** [comment]
Can you provide an example of what this would look like (changing a color using `workspace.colorCustomization`)? I can't find any examples.

**Comment by alefragnani** [comment]
Hi @mbomb007 ,

I'm not sure when it was released in VS Code, but you have a sample here: https://code.visualstudio.com/updates/v1_40#_themable-window-border

Instead of:

```json
    "bookmarks.backgroundLineColor": "#00FF00"
```

It will be: 

```json
    "workbench.colorCustomizations": {
        ...
        "bookmarks.lineBackground": "#00FF00"
    },
```

And two more colours will be added:

```json
        "bookmarks.overviewRuler": "#FF000022",
        "bookmarks.lineBorder": "#0000FF",
```
