### ISSUE TITLE
Bookmarked line moves if you add text above that bookmark

### ISSUE THREAD

**Issue by worsethannetbeans** [alefragnani/vscode-bookmarks#247]
For a long file (where the developers didn't know how to split their logic to different classes), let's say I add a bookmark on the line saying `public function somename() {`. Then I go to somewhere else in the file above there and start adding lines of code. Then I want to go back to the bookmark to refer to the `somename` function. The bookmark has moved position to some unrelated line of code. It doesn't stay on the line I originally bookmarked e.g.

![Screen Shot 2019-11-04 at 10 35 57 AM](https://user-images.githubusercontent.com/56943775/68092335-f3f37100-feee-11e9-8122-5832bc03d3e1.png)

Unfortunately this makes this bookmark feature for VS Code nearly useless. If I compare it to Netbeans, the bookmarks stay on the line where I put them, even if I make modifications to other lines in the file above or below.

**Comment by alefragnani** [comment]
Hi @worsethannetbeans ,

You may be facing similar issues as reported in #116 or #168. If you use a formatter (or Prettier) maybe it could be related to #118 too. 

It's on the radar, but no ETA yet, sorry. I hope I could revisit these in the comming weeks.

Hope this helps
