### ISSUE TITLE
Bookmarks set but do not list or jump

### ISSUE THREAD

**Issue by evanwellens** [alefragnani/vscode-bookmarks#248]
Bookmarks set but do not list or jump.. Similar issue with numbered bookmarks . Guessing the same problem is at hand. Let me know if there is something I can provide to help troubleshoot.

**Comment by alefragnani** [comment]
Hi @evanwellens ,

Sorry to hear about that. To help me to understand what's going on, could you provide a bit more information?

- Current OS
- Current VS Code release (stable or Insiders)
- Project kind (single file, single folder, multi-root folder, remote folder)

BTW, do you see the bookmark icon in the gutter? Are you able to navigate using `Jump to Next/Previous`? Console log from `Developer Tools` would also help.

Thank you

**Comment by evanwellens** [comment]
Thanks for getting back to me... 
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

I guess you would call our project single root... It's an angular app , within a workspace that uses a library folder , and an app folder .. Hopefully that makes sense.

I do see the icon. 
No navigation works. I can go to the command palette and select the command but it does nothing.

In VS Code I set output to extensions but see no logging .. Not sure how to get the console output to help. A quick google didn't shed any light on the matter.

**Comment by alefragnani** [comment]
Well, that's weird. It's the first time I see this. 😕  

The normal behavior (when the `Toggle` command don't work) is you seeing a warning message saying that the command is not registered, or something like that. But it never _didn't do anything_. The same for the `Jump` commands. You could try to call the `Bookmarks: What's New` command, to check if it does anything.

The _console log_ that I'm talking is shown using the `Command Palette`. You should do:

1. Open the `Command Palette` (`Ctrl + Shift + P`)
2. Type the command `Developer: Toggle Developer Tools`. It will open the _Chromium developer tools_)
3. Click on `Console` tab

Hope this helps

**Comment by evanwellens** [comment]
I get no output in the console when creating and trying to jump to a bookmark. I do for other unrelated activity.

**Comment by alefragnani** [comment]
Unless you are accessing _remote development scenarios_ like WSL, Docker, Shared Folders, or something alike, it's the first time someone reports this _strange_ behavior. 

Do you face similar issues with other extensions?

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
