### ISSUE TITLE
Group bookmarks by projects in workspace (multi-folder) scenarios

### ISSUE THREAD

**Issue by joaoeduardo** [alefragnani/vscode-bookmarks#249]
Is it possible? When I have many projects open in my workspace, the bookmarks panel gets confused.

**Comment by alefragnani** [comment]
Hi @joaoeduardo ,

Unfortunately no, at least not right now. All bookmarks (no matter which root folder) are displayed together. But I see your point, and it would be a good addition to the Side Bar.

Thanks for your suggestion.

**Comment by alefragnani** [comment]
I updated the issue's description

**Comment by EricRSouza** [comment]
It would be good if you could sort the folders on the sidebar by yourself as well (with drag and drop). And don't get stuck to the folder order in which the bookmarks were created

**Comment by alefragnani** [comment]
Hi @EricRSouza ,

Unfortunately, there is no API available for Drag & Drop yet. There is an open issue (https://github.com/microsoft/vscode/issues/32592) in VS Code repo, but no ETA.

**Comment by deltoss** [comment]
I also find such a feature useful for large codebases. Used it in Visual Studio.
