### ISSUE TITLE
Feature Request: Show saved bookmark note when hovering over the gutter icon

### ISSUE THREAD

**Issue by link834** [alefragnani/vscode-bookmarks#250]
Hi,

This isn't super important feature request to complete, but sometimes I add notes to my bookmarks and I find myself trying to hover over the bookmark icons in the gutter expecting a tool tip to come up that displays the note that I left

If someone could add to the bookmark settings an option that allows the user to hover over the gutter icon as a way to view a tooltip of the note added to the bookmark, that would be awesome

**Comment by alefragnani** [comment]
Hi @link834 ,

If I understand correctly, you mean the _Bookmark Label_, right? This is indeed a great addition, thanks for reporting 👍 

Unfortunately there is no API available in VS Code yet, but there is already an [open issue](https://github.com/microsoft/vscode/issues/28080) in VS Code repo.

Hope this helps

**Comment by link834** [comment]
Yes, I did mean Bookmark Label :)

Thank you for referencing the open issue for VSCode, that does look promising.  I hope it gets completed someday

**Comment by alefragnani** [comment]
I'm closing this issue because the VS Code issue that it depends on has no update from VS Code team members for more than an year. It's planned on "Backlog" Milestone, but it does not appear to be released soon.

I'm subscribed to both issues, so if/when it is closed, I'll be notified.
