### ISSUE TITLE
Cannot have a breakpoint and a bookmark on the same row

### ISSUE THREAD

**Issue by Zingam** [alefragnani/vscode-bookmarks#251]
I'd like to be able to click on the gutter and set a breakpoint, I also would be like to be able to click on the gutter and set a bookmark. Unfortunately currently whenever there is a bookmark, I am unable to set a breakpoint on that row.
It would be marvelous if breakpoints and bookmarks are made compatible and possible to be toggled via a mouse click.

**Comment by alefragnani** [comment]
Hi @Zingam ,

This has already been reported in #56 and #24 but both depends on VS Code fixing/supporting APIs, but unfortunately, none of them has been delivered until now 😢 . Both issues are closed (here) but I’ve subscribed the VSCode issues, to be notified if something new happens.

Hope this helps.
