### ISSUE TITLE
[Feature request] Counter of bookmarks

### ISSUE THREAD

**Issue by inoyakaigor** [alefragnani/vscode-bookmarks#255]
…like that
![изображение](https://user-images.githubusercontent.com/1235286/69547028-e4bf8a80-0fa5-11ea-9a07-66bb03d47420.png)

My typical scenario is 
* start solving issue
* set bookmarks in a important places
* after resolving check bookmarks that I haven't forgotten do something important

In this scenario after bookmarks count became 0 I can be sure that everything done.

**Comment by alefragnani** [comment]
Hi @inoyakaigor ,

This has already been requested in #153, but it’s “on hold” because there is no API available yet. Please, upvote the related issue in VS Code repo (https://github.com/microsoft/vscode/issues/54938), to make it easier to be seen :smile:

Hope this helps
