### ISSUE TITLE
Bookmarks not saved

### ISSUE THREAD

**Issue by zvit** [alefragnani/vscode-bookmarks#256]
I place a bookmark. When I reopen the file, the bookmark is gone.

**Comment by alefragnani** [comment]
Hi @zvit ,

Could you please provide more details? 

* Which OS/Version are you using
* How is your workspace? Single or Multi-root folders?
* Are you using any formatter extension?
* Are you using Remote Development scenarios?

Thank you

**Comment by zvit** [comment]
Hey @alefragnani,

Below is the information you sked for.

_Which OS/Version are you using_
Win10 Pro v1909

_How is your workspace? Single or Multi-root folders?_
Single

_Are you using any formatter extension?_
No

_Are you using Remote Development scenarios?_
No

**Comment by alefragnani** [comment]
In this case: 

* Are you seeing any message/warning when you open the folder, or activate a bookmark? 
* Are you able to toggle a new bookmark when you reopen the folder? 
* Is the folder _local_. In your machine, or is a _network folder_?

Just to be clear, the bookmarks are stored “per session”, which means if you open folder `C:\FolderOne\SubFolderA` and toggle a bookmark in file `x.txt`, it will be available if you reopen folder `C:\FolderOne\SubfolderA` In VS Code. But if you open `C:\FolderOne` and navigates to file `SubFolderA\x.txt` it wont’t be any bookmark. 

Hope this helps

**Comment by zvit** [comment]
_Are you seeing any message/warning when you open the folder, or activate a bookmark?_
No.

_Are you able to toggle a new bookmark when you reopen the folder?_
Yes.

_Is the folder local. In your machine, or is a network folder?_
Local

Not sure what you mean about the navigation. I don't use VS to navigate folders. In Windows Explorer I right click an ahk file and choose "edit with VS"

**Comment by alefragnani** [comment]
> Not sure what you mean about the navigation. I don't use VS to navigate folders. In Windows Explorer I right click an ahk file and choose "edit with VS"

In this case (editing single file), the bookmark won’t be there too, because there is no “VS Code session” to store the information. Also, if you already have a VS Code window open (no matter in which folder) and you open a single file in Explorer, it will be opened in the latest focused VS Code window, which will be “another session”, and then, will have a different bookmarks storage

The Bookmarks are available only if you open `Folders` in VS Code 

Hope this helps

**Comment by zvit** [comment]
Ok, thank you.
I will look for a plugin that embeds bookmarks into the file itself, much like Photoshop embeds photos into the .psd file.

**Comment by alefragnani** [comment]
Sure, no problem 👍 

I remember seeing some extensions that creates bookmarks “on the fly” based on regex/tokens, like `TODO`. 

Hope this helps

**Comment by apj68** [comment]
@alefragnani - I'm trying to slowly convert to VS Code from Emacs.  One feature of emacs that I use constantly is bookmarks.  A key element to the way bookmarks work in emacs is that they are global.  It's possible to bookmarks files, folders, as well as locations in files.  This allows for the bookmarks to be a super-index of anything that you may be working on.  If I understand your plugin functionality correctly each session has its own set of bookmarks and you can't create a bookmark to folders, only files.  Do I understand correctly?  Much like the OP, I use VS Code to pop open various folders and files, which are permanent files but not associated with a project or a persistent session.  Would you consider adapting the design to persist bookmarks in some kind of global fashion?

**Comment by alefragnani** [comment]
Hi @apj68 , commented on #287 😬
