### ISSUE TITLE
Remove Bookmarks from the List via Backspace

### ISSUE THREAD

**Issue by fabb** [alefragnani/vscode-bookmarks#257]
I'm used to the Bookmarks feature of IntelliJ, and a small feature that I use a lot there is deleting bookmarks directly from the bookmarks list using the Backspace (or Delete, or Toggle Bookmark) key. Would be awesome if this could be added!

**Comment by alefragnani** [comment]
Hi @fabb ,

I'm not sure, but if I remember correctly, the Tree View API does not support custom keyboard shortcuts, yet. I'll take a look

Thank you for your suggestion 👍

**Comment by alefragnani** [comment]
Hi @fabb ,

I may be missing something, but I didn't find any reference to accomplish your scenario. I tried a few thing, learned a few APIs, no success. So, unless you are able to do it using `Keyboard Shortcuts`, I would say this is not possible. 

Let me know if you find a way

**Comment by fabb** [comment]
Thanks for trying!
