### ISSUE TITLE
Cannot jump to bookmark when scrolling with mouse

### ISSUE THREAD

**Issue by wangsensei** [alefragnani/vscode-bookmarks#26]
Not sure if this is an issue or a feature that hasn't been implemented yet...

1. Set a bookmark
2. Scroll down/up until bookmark is not in the current window
3. Try to jump to the bookmark, nothing happens, unless the text cursor is not on the same line as the bookmark

**Comment by alefragnani** [comment]
Hi @wangsensei ,

In fact, it is a _bug_. It's caused by a code to _avoid unnecessary move/scroll_ if the cursor is already at the only bookmark in the file.

I will try to detect if the cursor is visible (scrolling window), otherwise I can simply remove this check.

Thanks for reporting
