### ISSUE TITLE
Release vsix files

### ISSUE THREAD

**Issue by mirekphd** [alefragnani/vscode-bookmarks#260]
Can you please release vsix extension files? A good example would be here:
https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by alefragnani** [comment]
Hi @mirekphd ,

What's the idea/need about releasing `.vsix` files in the repo?

You are able to install _any_ version of any extension, using VS Code built in command `Extensions: Install Specific Version of Extension...`

Hope this helps

**Comment by mirekphd** [comment]
I agree that manually with access to the internet it would be easier to use the Market place. But our use case is batch installation (docker containers) for an offline environment (on air-gapped servers). So it's necessary to automate all packages updates, including VS Code and its extension . Only Github is open enough to provide an API service and a client (git) that allow us to monitor for version changes and trigger automatic container rebuilds. Repos like PyPI are so much more standardized than Github precisely to make such automation easier - here we have to count on developer benevolence:)

**Comment by alefragnani** [comment]
That's exactly what I was thinking 😀 

I'm not so familiar with GitHub releases (did it once/twice a long time ago), so I have to recap how it works/laborious is. Let's see..

Hope this helps

**Comment by CoreyVidal** [comment]
:+1:

**Comment by nhooyr** [comment]
@alefragnani Should be as simple as clicking create new release, entering the version and attaching the .vsix file.

**Comment by alefragnani** [comment]
I've just published the latest version (v11.4.0) on GitHub releases https://github.com/alefragnani/vscode-bookmarks/releases. Starting from now, every new release should be published as well.

Just to be clear, I didn't test the extension on code-server or any other VSCode alternative (VSCodium, Eclipse Theia, etc), so I don't know if/how it will work. I'm not sure how you (code-server) handles extension's compatibility on code-server, but feel free to open new issues, and we could talk about it.

Enjoy
