### ISSUE TITLE
Bookmarks don't shift with line breaks when they're done with multiple cursors

### ISSUE THREAD

**Issue by juancpgo** [alefragnani/vscode-bookmarks#261]
When I'm using input with multiple cursors and then hit the **Enter** key for line breaks, every bookmark below that line doesn't track those line breaks: the bookmarks stay in the same line number, while the character content of the line naturally gets shifted two lines down.

I'm surprised there aren't already issues raised here for this, since it seems obvious and problematic enough. Could it be happening only with me?

Ps: Using VS Code on macOS Mojave 10.14.6. Only a handful of extensions installed on VS Code, tried disabling them already.

**Comment by alefragnani** [comment]
Hi @juancpgo ,

This happens because the extension does not support _multi-cursor_, yet. See #77 for more details.

Hope this helps.

**Comment by juancpgo** [comment]
Thanks for the reply, Alessandro. Since multi-cursor is for me is a basic functionality I use all the time, this bookmark displacement whenever I use multi-cursors feels like a bug to me 😬. Other than that, the extension is great. There seems to be no other VS Code extension for bookmarking, so I'll have to cope with the “bug” if it feels worthwhile.

**Comment by alefragnani** [comment]
Some would say _undocumented feature_ 😆  .
