### ISSUE TITLE
Error trying to clone the repo

### ISSUE THREAD

**Issue by cbeltrangomez84** [alefragnani/vscode-bookmarks#262]
Hi, I'm trying to clone this repo but the submodules are not found (vscode-bookmarks-core is needed), Does anybody know why?

**Comment by alefragnani** [comment]
Hi @cbeltrangomez84 ,

The submodules are private for now, because I'm refactoring how the extension works, and also merging some pieces with my other **Numbered Bookmarks** extension. So, for now, you won't be able to manually build it, sorry.
