### ISSUE TITLE
[Feature Request] Multi notes/line and choosing icon color based on label

### ISSUE THREAD

**Issue by mohammedalqassar** [alefragnani/vscode-bookmarks#264]
This is a great extension, thanks for your work.

I use it to mark changes (and to find and track such changes) that I made to code lines. Some times I need to write two or more separate changes on the same line of code, where the changes are for different unrelated features or tasks. It would be nice to be able to add more than one bookmark (each with their separate label) to the same line. And even to select different icon color based on the label. I am thinking of something similar to the email "Categories" in Microsoft Outlook.

**Comment by alefragnani** [comment]
Hi @mohammedalqassar ,

The multi-color bookmark is already being tracked in #243, so you could upvote there :+1.

To be able to have multiples bookmarks per line, it would require a bit of reengineering, because much of the features are _related to the line_, like the _preview_ of the line, shown in Command Palette and the Side Bar. 

How would this _preview_ work if you have multiple bookmarks per line? Would the preview:

* Start at bookmark position, until it finds another bookmark
* Start at bookmark position, until the end of the line

Thank you

**Comment by mohammedalqassar** [comment]
I +1 #243, thank you for directing me to that post.

As for how the preview would work with multiple bookmarks, I think showing contents from bookmark location until it finds another bookmark is more appropriate. But most likely, using multiple bookmarks on the same line will go hand in hand with labels.

As another approach, instead of having multiple bookmarks on the same line, one can have single bookmark but with multiple tags, and these tags can be displayed on a second line underneath the line preview (or underneath a label if a label exists, though I personally will use either the label or tags). Or may be the label itself can be used instead of tags by allowing the bookmark to have more than one label?

Thank you again for your time and effort.

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding

**Comment by akinokonomi** [comment]
Not sure about colours, labels, etc., but it would be nice to have experience similar to Sublime Text, where it is possible to have multiple bookmarks on the same line. 

Oh well, seems like it is not so popular as I thought. Regardless, thank you for considering it!

**Comment by alefragnani** [comment]
Hi @akinokonomi ,

I’m sorry to say, but with not enough upvotes/support from the community, I wouldn’t update the extension to support this scenario, mostly because it requires a bit of reengineering on how the extension works.

Thank you
