### ISSUE TITLE
Bookmark count badge

### ISSUE THREAD

**Issue by Kevinwuu** [alefragnani/vscode-bookmarks#268]
I think it will be nice to show bookmark count badge on the sidebar icon, to remind us that we still have bookmark in our project and maybe it's unnecessary now.

**Comment by alefragnani** [comment]
Hi @Kevinwuu ,

This is already being tracked in #153, and as you can see, _depends on_ the VS Code team to release proper API (https://github.com/microsoft/vscode/issues/54938). 

It's on their `Backlog`, but no ETA yet.

Hope this helps
