### ISSUE TITLE
List/Clear bookmarks from all files

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-bookmarks#27]
_Based on the review in the marketplace_

> If the Bookmarks List command can list all the bookmarks in all files, not just the current file, and the Bookmark Clear can clear all the bookmarks in all files, then it will be awesome.

**Comment by Aukstkalnis** [comment]
Yes. I missed that to :)

**Comment by alefragnani** [comment]
Just published a new release. Update and enjoy 😄
