### ISSUE TITLE
Support same project opened in multiple workspaces

### ISSUE THREAD

**Issue by zchen3000** [alefragnani/vscode-bookmarks#273]
I have multiple workspaces using the same project/folder.  I hve bookmark.saveBookmarksInProject=true, so they share the same <projectFolder>/.vscode/bookmarks.json file.

If I added bookmarks from the different workspaces, the bookmarks are overwritten by each other. and clicking BookMark refresh button would not show the new bookmarks from the different workspace.

Basically I'd like a mode by project only, and not by sessions, so I can share the bookmarks across different workspaces.

**Comment by alefragnani** [comment]
Hi @zchen3000 ,

Yes, right now the `saveBookmarksInProject` setting is not supported in workspace/multi-root scenarios, so I guess you are asking the same as #193.

I'm not sure how complex it would be to support this, so I can't say for sure when it would be released.

Hope this helps.

**Comment by alefragnani** [comment]
Please, upvote issue #193 so I can identify which issues to prioritize 👍
