### ISSUE TITLE
[feature] Peek

### ISSUE THREAD

**Issue by nvirth** [alefragnani/vscode-bookmarks#275]
Please make possible to peek the bookmarks, like peek references:
![Video_2020-03-20_131918](https://user-images.githubusercontent.com/11088526/77163085-a77b8d00-6aad-11ea-8e56-74221c8ae3a5.gif)

**Comment by alefragnani** [comment]
Hi @nvirth ,

How do you think it could work? I mean, the `Peek` command let’s you _peek things_ located somewhere else, based on the current word/symbol/identifier. Bookmarks itself _are those things_, and they don’t refers to _other things/locations_, so what would it peek?

Unless you would like to _peek all bookmarks_ from the current file, no matter where the cursor is. Just like the `List` command. Is that it?

Thank you

**Comment by nvirth** [comment]
Hi,

Actually, I borrowed the idea from JetBrains' Rider IDE:
![Video_2020-03-26_121706](https://user-images.githubusercontent.com/11088526/77642025-4811f700-6f5d-11ea-9fa6-7bdf74129ed6.gif)

This is the [Show Bookmarks](https://www.jetbrains.com/help/rider/Navigation_and_Search__Bookmarks.html#b3b97e59) (peek) window on the gif.
There are 6 bookmarks in the above example at the left side of the window.
You can select a bookmark and peek its content in the right side of the window.

So I meant to peek the content (file and line) the bookmarks refer to, just like in Rider's Show Bookmark window.

**Comment by alefragnani** [comment]
Well, this is more like Bookmarks **View** than **Pick**, but I get the idea.

Unfortunately, there is no API available for Custom Peeks. There is an open issue https://github.com/microsoft/vscode/issues/3220 in VS Code repo, but no ETA yet (just tagged as `Backlog`).

Maybe this could get enough attention by the VS Code team, and we could see it landing in the upcoming releases.

Hope this helps

**Comment by alefragnani** [comment]
I’m closing this issue because it depends on a VS Code API, and the linked issue did not receive an update from the team for a long time.

I have subscribed to that issue, so I’ll be notified if they release the API sometime in the future.

Thanks for your understanding.
