### ISSUE TITLE
A middle-click on a file does not open it in "keep open" mode

### ISSUE THREAD

**Issue by yann-papouin** [alefragnani/vscode-bookmarks#276]
Opening a file using a middle-click does not open it using the "keep open" mode.
That does not respect the builtin vscode explorer beahviour.

**Comment by alefragnani** [comment]
Hi @yann-papouin ,

The files in the Side Bar are used to _group_ the bookmarks it contains, not to _open the file_ itself. It works just like Folders (and its files), in the builtin explorer view.

I'm not sure there is an API for that in the TreeView API (probably not, just like Ctrl/Cmd + Click don't have), but if yes, this could be added in the future.

Hope this helps.

**Comment by alefragnani** [comment]
After a few attempts, I didn’t find any API that could add this behavior to the Side Bar. It seems to be the default/expected Treeview behavior.

I’m closing the issue because it isn’t doable. Sorry about that.
