### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by chestozo** [alefragnani/vscode-bookmarks#277]
Bom dia Alessandro =)
I was trying to modify something in the code.
But I could not setup my local copy because of the git submodule https://github.com/alefragnani/vscode-bookmarks-core that is removed or it is a private one.

What would be the right way to create PRs to this repo?
Thanks in advance

**Comment by alefragnani** [comment]
Hi @chestozo ,

Thank you for your interest, but right now the `core` repo is private, and you are unable to contribute. 

I started refactoring the extension, to share pieces with my other Numbered Bookmarks extension, but it took more time/effort that I though, so I’m still thinking on the better model to re-open the extension to contributions.

Thank you

**Comment by javalight** [comment]
@alefragnani why? I would love to add features.
