### ISSUE TITLE
Unknown character edited while moving to bookmark using shortcut

### ISSUE THREAD

**Issue by Hemz23** [alefragnani/vscode-bookmarks#278]
Issue Type: <b>Bug</b>

Hello team,

I've installed bookmarks extention. I've saved my file and my cursor is at the begining of file. 

While moving to a bookmark using shortcut "Ctrl + Alt + L", my file goes into edited mode and an unknown character shows up like below.

Before: "import pdfkit" 
After moving to bookmark: "̥import pdfkit"
The change is made in "i" symbol and this happens wherever the cursor was positioned before bookmark.

Screenshot 1 shows cursor position and line to which I've added bookmark.

![s1](https://user-images.githubusercontent.com/32325938/78223051-dfd68e80-74e3-11ea-9558-0242fb68f474.PNG)

Screenshot 2 shows changes made in first line automatically.
![s2](https://user-images.githubusercontent.com/32325938/78223056-e2d17f00-74e3-11ea-8bf7-0db8f07d1786.PNG)

Extension version: 11.0.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alefragnani** [comment]
Hi @Hemz23 ,

You may be facing the sabe error as #240, which leads to a problem with keyboard layouts.

Try using the commands in the `Command Palette`. If the command work then I know for sure it’s a _duplicate_.

Hope this helps.

**Comment by Hemz23** [comment]
Hi Alefragnani,

I'll check out your recommended option.

Thanks for your help.

Regards,
Hemal Pitroda

**Comment by alefragnani** [comment]
Hi @Hemz23 ,

Any news? Did it work using from the `Command Palette`?

**Comment by Hemz23** [comment]
Hi there,

Yes, using command palette its working fine.

The shortcut *Ctrl + Alt + L* is causing the error.

Is there any other option rating than changing the shortcut?

**Comment by alefragnani** [comment]
I remember sometime ago someone asking on VS Code repo how to detect conflicts/missing keyboard shortcuts, but I didn’t find the issue. I just found [this documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts) which may help. If you need more details, I suggest you to look directly in the VS Code repo.

The extension itself does have any control about how the keyboard shortcut are detected or executed. The extension _just registers_ them.  So, I suggest you to define an alternative (free) shortcut.

Hope this helps
