### ISSUE TITLE
Ctl+Alt+l Does not respond

### ISSUE THREAD

**Issue by bobhancock** [alefragnani/vscode-bookmarks#281]
Ctl+Alt+j works just fine, Ctl+Alt+l does nothing. I've checked and is not mapped to another key on the system level.

Ctl+p and selecting Jump to Next works.

This is on a Debian Linux system.

Is there debug information I can provide?

**Comment by alefragnani** [comment]
Hi @bobhancock ,

I remember other Linux users saying that `Ctrl + Alt + L` locks the screen (at least #79 and #259), but I don't know which distribution/window manager they use. 

The extension itself don't care which keyboard shortcut is being used. It just registers in VS Code and waits to be called. So, I suggest you to change the keyboard shortcut to any combination that best fit your needs. To do this, just follow [these instructions](https://code.visualstudio.com/docs/getstarted/keybindings) from VS Code documentation. 

Hope this helps.
