### ISSUE TITLE
vscode-bookmarks-core gives 404

### ISSUE THREAD

**Issue by apj68** [alefragnani/vscode-bookmarks#282]
I was just trying to browse the code but vscode-bookmarks-core seems to be unavailable (404 error).  Is that a github issue or is that source not shared?

**Comment by alefragnani** [comment]
Hi @apj68 ,

Right now the core repo is private, and you are unable to access. I started refactoring the extension, to share pieces with my other Numbered Bookmarks extension, but it took more time/effort that I though, so I’m still thinking on the better model to re-open the extension to contributions.

Thank you

**Comment by nhooyr** [comment]
This is preventing us from adding this extension to the code-server marketplace. 

See https://github.com/cdr/code-server/issues/1711#issuecomment-632761726

Is it possible you can publish a `.vsix` with GitHub releases?

**Comment by alefragnani** [comment]
Hi @nhooyr ,

The `.vsix` publishing was already requested in #260. Please upvote the issue, so I can keep track of the requests.

Hope this helps

**Comment by nhooyr** [comment]
Awesome, thanks, upvoted!

**Comment by aarighi** [comment]
As of today, I am still regeiving a 404 on [vs-bookmarks-core](https://github.com/alefragnani/vscode-bookmarks-core/), despite the changelog of the extension saying that #523 is closed.

<img width="820" height="245" alt="Image" src="https://github.com/user-attachments/assets/f83893f2-3555-4f19-a7a6-10c3b0ff9793" />

Is there something I'm missing?

Thanks

**Comment by alefragnani** [comment]
Hi @aarighi ,

It is not required anymore, as I removed the submodule dependency, and moved the source to here.

Simply `pull’ the latest changes from this repo to reflect that.

Hope this helps

**Comment by ghost** [comment]
Sure, it now lives here but there is no way to check what the code looked like while it was private. Does not help with security reputation.

**Comment by JaffaKetchup** [comment]
That is indeed a little worrying.
