### ISSUE TITLE
Docs talk about WHAT is possible, not HOW to do it

### ISSUE THREAD

**Issue by philchillbill** [alefragnani/vscode-bookmarks#286]
I installed this but have no clue how to use it. The docs list feature after feature but do not list HOW to do those things. Am I the only person experiencing this?

**Comment by alefragnani** [comment]
Hi @philchillbill ,

What do think is missing? Which feature weren’t you able to use?

I mean, all the  available commands are listed, and their names are almost self explanatory. The settings are also listed, with explanation and samples. And there are also a few screenshots and gifs showing how the Bookmarks/Side Bar are presented.

Hope this helps

**Comment by philchillbill** [comment]
Thanks for the fast response. What I mean is the list of keyboard shortcuts to e.g. set a bookmark and then jump to it. I eventually figured out that I can open the command palette with Ctrl-Shift-P and search for commands beginning with Bookmarks: and then I will get to see

![image](https://user-images.githubusercontent.com/45945278/79439932-b59dca00-7fd5-11ea-939f-45b84eac7a57.png)

That may be obvious to people used to VS Code but not to newbies.

**Comment by alefragnani** [comment]
Glad to see you find out!

So, in the end, your issue was on how to use VS Code itself, not the extension 😬 . It’s a different paradigm (Keyboard centric), I know, but you get used.

Enjoy the extension
