### ISSUE TITLE
[Feature request] Go to particular bookmark by pressing shortcut

### ISSUE THREAD

**Issue by vsashyn** [alefragnani/vscode-bookmarks#288]
Hello smart people! Thanks for the extension. 

Let's say I want to add bookmark and mark it as resolved by number `1`.Then I add another bookmark and assign to it number '2'. After, using simple shortcut (ex. `Ctrl+1`, `Crtl+2`) I'm able to move back and forth. The same functionality is provided in WebStorm bookmarks out of the box. 
Does it make sense?

**Comment by alefragnani** [comment]
Hi @vsashyn ,

Yes, it does make sense, and I have used that for years with Delphi. 

But, to accomplish that I have created another extension, it’s called [Numbered Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks&ssr=false#overview) 😁 

It’s doesn’t have all the same features as this one, like Side Bar, Labels or Selection commands, but it’s planned for future releases.

Hope this helps
