### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Raju** [alefragnani/vscode-bookmarks#289]
- Issue Type: `Bug`
- Extension Name: `Bookmarks`
- Extension Version: `11.1.0`
- OS Version: `Linux x64 5.4.0-24-generic`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Raju** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7,
		"activateCallTime": 2,
		"activateResolvedTime": 578,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "alefragnani.Bookmarks",
				"_lower": "alefragnani.bookmarks"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by alefragnani** [comment]
Hi @Raju ,

Could you give more details about how this error happened? What were you doing? Which command did you try to use?

Thank you

**Comment by Raju** [comment]
It just occurred randomly now a days, especially when live share is on. Both have the extension enabled.

**Comment by alefragnani** [comment]
Hm, if it was random, it will be hard to identify and fix. Next time it occurs, please try to get more details.

BTW, the extension still doesn't support Live Share, so it won't work (share data between Host and Guest). But as you said it is installed on both sides, I wouldn't be a problem.

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
