### ISSUE TITLE
Feature Request: Fold bookmarked regions

### ISSUE THREAD

**Issue by Diogo-Rossi** [alefragnani/vscode-bookmarks#291]
Is it possible to add a setting to choose using the bookmarked lines as "**Level 1 fold head**" to fold regions in VS Code?

It could be useful to collapse all the code between bookmarked lines.

Bellow there is a example for how it would looks like:

- **Code with bookmarked lines**:
![image](https://user-images.githubusercontent.com/57204023/79940253-91a81180-8437-11ea-875f-ac543b961e79.png)

- **Code with "folded regions" (collapsed) between bookmarked lines**:
![image](https://user-images.githubusercontent.com/57204023/79940263-98368900-8437-11ea-97d0-263bb4453c2b.png)

**Comment by alefragnani** [comment]
Hi @Diogo-Rossi ,

VS Code does not support this kind of customisation in folding. It only allows two different so called _strategies_, which are `indentation` and `language` (recently added). So, there is no way to create new _folding points_ to achieve such behaviour. I'm sorry

BTW, I wonder how the folding would work, if defined by a Bookmark. I mean, a Bookmark in a single spot, and a folding depends on two spots (begin - end), even with the `indentation` strategy. In this case, it uses the next line with the same indentation level.

Thank you for your suggestion, but unfortunately there is no way to add this feature.

Hope this helps

**Comment by Diogo-Rossi** [comment]
Hi @alefragnani, thank you for your attention.

I recently discover the `#region` comment ([Here](https://code.visualstudio.com/updates/v1_17#_folding-regions)) that allows to fold entire regions of code, which was my intention. . .

> BTW, I wonder how the folding would work, if defined by a Bookmark. I mean, a Bookmark in a single spot, and a folding depends on two spots (begin - end), even with the indentation strategy. In this case, it uses the next line with the same indentation level.

Exactly, I was thinking it could be possible to fold regions **between** two defined bookmarks.
If only one bookmark is available, it could fold from it to the end of file (as the last region).

But it is ok for now. Thank you again for your attention.

It's a great extension. Good work!
