### ISSUE TITLE
Cannot use this without ADO.NET mssql

### ISSUE THREAD

**Issue by KoolKeith** [alefragnani/vscode-bookmarks#293]
Hi.
So, there seems to be an undisclosed dependency for ADO.NET and/or mssql. When I click the Plus, to add a bookmark, VSCode pops up a promt, where it persits to have me enter some DB connection.

![image](https://user-images.githubusercontent.com/10271212/80436727-15fb0880-8900-11ea-966f-f9fd032303eb.png)
The "ad-hoc fixing console" from VS Code did some work which I could not capute. I've read something about "mssql". I restarted. Still get the prompt whenever I click "+" for a bookmark.

I don't feel like installing fat DB stuff right now.

**Comment by KoolKeith** [comment]
Some new insight... So I do have the extension "mssql" installed, but it does not work.
![image](https://user-images.githubusercontent.com/10271212/80437330-9ec67400-8901-11ea-99d8-c91fe5ffe01a.png)

**Comment by alefragnani** [comment]
Hi @KoolKeith ,

I’m don’t know what is happening, but I can say the extension doesn’t need/requires ADO.NET. Unless VS Code itself already depends on it. I think the bookmarks you are trying to add are relative to other extension. Maybe MSSQL itself.

Another reason I believe to be the case, is when you said:

> Still get the prompt whenever I click "+" for a bookmark.

There is no “+” click/button/command to add Bookmarks. The only way to add a bookmark is using the `Bookmarks: Toggle` command, which you can use either in the `Command Palette`, `Context Menu` or via Keyboard Shortcuts

BTW, Based on the latest print you provided, it appears you appear you are using an older version of the extension. But for you issue, it wouldn’t make any difference.

Hope this helps

**Comment by KoolKeith** [comment]
Thank you for helping me, Alessandro.
I should have RTFM 🤦‍♂️ 
Whatever the + is for, I don't need it.
Have a great day !

![image](https://user-images.githubusercontent.com/10271212/80534718-fb786c00-899f-11ea-8f82-0567d723525f.png)

**Comment by alefragnani** [comment]
This has never been added to the extension!

I guess you are using a modified version, from someone else, or another extension is _using_ my Side Bar.

Have you installed from the Marketplace, or via `.vsix` file? Which version, and release date, does it show?

**Comment by alefragnani** [comment]
I guess the  issue is with MSSQL extension itself. 

Look what I’ve found found

* Issue https://github.com/microsoft/vscode-mssql/issues/1470
* Fixed with this PR https://github.com/microsoft/vscode-mssql/pull/1456/files

**Comment by alefragnani** [comment]
Update the extensions, and you should be Ok.
