### ISSUE TITLE
How to disable release note on vscode startup

### ISSUE THREAD

**Issue by serenedu** [alefragnani/vscode-bookmarks#297]
Like this extension, hope there's a way to turn release note off.

**Comment by skoshy** [comment]
Agreed, this has been mentioned here (https://github.com/alefragnani/vscode-bookmarks/issues/175). Please allow us to have an option to disable these popups from showing up when the extension is updated.

**Comment by alefragnani** [comment]
I’m glad to know you like the extension, but I’m closing this issue as a duplicate of #175 . As described there, this window only appears on updates (not patches).

I’ll post some comments there latter, so if you are interested in follow the subject, I suggest you to subscribe/comment there.

Thank you
