### ISSUE TITLE
Add git commit id in bookmarks.json

### ISSUE THREAD

**Issue by thatcashcow** [alefragnani/vscode-bookmarks#298]
Helpful when lot of code changes in a file.

**Comment by alefragnani** [comment]
Hi @thatcashcow ,

Please, could you please provide more details about how it work? 

I mean, what’s the purpose to have `commit id` in `bookmarks.json`? How it would affect on Bookmarks behavior?

There is another issue asking something related to Git (#177). Have you seen it?

Hope this helps

**Comment by thatcashcow** [comment]
Commit ID would help when a bookmark for a file is too old. Something like this can be done:
```git checkout <hash> -- file1/to/restore file2/to/restore```
The user can read the commit ID from the bookmarks.json file.
Until this can be automated by the extension itself. I believe adding commit hash for each bookmark will do.

**Comment by thatcashcow** [comment]
Ok looks like the solution to this is to simply add bookmarks.json file with each ```git commit && git push```. Also ```.vscode/bookmarks.json``` file should simply reflect the file in the git root. Any reason why this is not being done currently?

**Comment by alefragnani** [comment]
Isn’t doing because the extension never had no intention to be tied/support Git or any other SCM 😄 .

If you need bookmarks assigned to some point in time (Git commit), adding it to that commit, as you pointed out above, is your best alternative, until #177 is released.

Hope this helps.
