### ISSUE TITLE
Rename "Explorer" panel to "Bookmarks"

### ISSUE THREAD

**Issue by SailorMax** [alefragnani/vscode-bookmarks#300]
If move "Explorer" panel from "Bookmarks" tab to "Explorer" tab, we have 2 panels with name "Explorer"

**Comment by alefragnani** [comment]
Hi @SailorMax ,

That’s one of the ideas behind #283 , but as the panels customization is still in _preview stage_, it will have to wait.

I guess VS Code will make it in _stable API_ in the next release (I’m being optimistic). Just after that I will take a look on the API, and how I could add it to the extension.

Thank you
