### ISSUE TITLE
Bookmarks overlap with breakpoints

### ISSUE THREAD

**Issue by DerekCresswell** [alefragnani/vscode-bookmarks#302]
I've noticed a few problems between breakpoints and bookmarks.
Ubuntu 20.04, VS Code 1.45.1

If you have a breakpoint set and then use `ctrl + alt + k` to make a bookmark on the same line the icons overlap. The bookmark is underneath the breakpoint.

If a bookmark is set, you cannot set a breakpoint on the same line with the mouse, only with a hotkey.
Similar, if there is a breakpoint and bookmark on the same line you cannot unset the breakpoint.

Not a high priority but does get annoying every once and a while.

**Comment by alefragnani** [comment]
Hi @DerekCresswell ,

This has already been reported in #56, but it’s a VS Code issue, and I’m still waiting for them to fix/properly support.

Unfortunately, no ETA from VS Code team.

Hope this helps

**Comment by DerekCresswell** [comment]
I assume that there's an issue open about that on VS Code then?

**Comment by alefragnani** [comment]
Yes, a few. Just follow the issue and you will be able to see how old and spread across the repo it is. A lot of reports, but still not on their Backlog.

**Comment by safield** [comment]
If someone knows the open issue in vscode that relates to this bug, please link it here so future people can follow the breadcrumbs.

**Comment by alefragnani** [comment]
Hi @safield 

It is already linked in the original issue (#56). It's https://github.com/microsoft/vscode/issues/5923
