### ISSUE TITLE
Change keyboard shortcut bindings

### ISSUE THREAD

**Issue by reciosonny** [alefragnani/vscode-bookmarks#304]
Are there any support to change keyboard shortcut bindings? I have problem in using ctrl+alt+k because my kindle app on Windows is occupying that keyboard shortcut although I tried to remove the keyboard shortcut for kindle but still persisted.

**Comment by alefragnani** [comment]
Hi @reciosonny ,

Sure you can. VS Code allows you to customize any command, native and from extensions.

Just follow [its official documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor), and choose your preferred keyboard shortcut.

Hope this helps
