### ISSUE TITLE
[Feature-Request] Display Filter

### ISSUE THREAD

**Issue by BoomRaccoon** [alefragnani/vscode-bookmarks#305]
I write latex and add every section as a bookmark to navigate easier in the file. At the beginning it was great but I have a lot of bookmarks now and it's hard to find the thing I need.
I know it's not made for this but I think a lot of people would benefit from a display filter.

**Comment by alefragnani** [comment]
Hi @BoomRaccoon ,

I think you request is similar to #254 , which brings the idea to "activate" a set of bookmarks. I have some ideas on how this _sets_ should look like (still "on board"), but I would like to hear more ideas from the users.

Please, keep track on #254 and add commends/suggestions on how you think the set/display filter should work

Hope this helps
