### ISSUE TITLE
Change shortcuts

### ISSUE THREAD

**Issue by jmasiak** [alefragnani/vscode-bookmarks#312]
Hi! Is there any way to change keyboard shortcuts for commands? I'm using a Polish keyboard and shortcut Ctrl+Alt+L makes letter ł.

**Comment by alefragnani** [comment]
Hi @jmasiak ,

Sure you can. VS Code allows you to customize any command, native and from extensions.

Just follow [its official documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor), and choose your preferred keyboard shortcut.

Hope this helps
