### ISSUE TITLE
Problem with comfy work by bookmarks

### ISSUE THREAD

**Issue by ManPython** [alefragnani/vscode-bookmarks#313]
1. Why we can't add bookmark by righ clik on the col in IDE code LOC counter and delete this bookmark by right click?
2. Why the NOC numer is on right side not left? 
- the true about bookmarks is that I using more often #TODO list not bookmark : )
3. I think we need some icon "+" on dock belt from bookmarks to add bookmark as current line aditionaly
4. Need searching by bookmarks elements from bookmarked line in code and by labels if added

**Comment by alefragnani** [comment]
Hi @ManPython ,

> Why we can't add bookmark by righ clik on the col in IDE code LOC counter and delete this bookmark by right click?

Because VS Code doesn’t exposes API for that (see #24)

> Why the NOC numer is on right side not left?

Because the line/column became a _detail_, not the main info. In fact, as you can see, #143 asks To _remove_ them (via setting). You could open another issue to swap the positions.

> the true about bookmarks is that I using more often #TODO list not bookmark : )

I use as a todo too, but if you need _automatic bookmarks_, you are using the wrong extension. You should look for  https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

> I think we need some icon "+" on dock belt from bookmarks to add bookmark as current line aditionaly

Good idea (y).

> Need searching by bookmarks elements from bookmarked line in code and by labels if added

The `Command Palette` supports both ways. The Side Bar doesn’t have filter because again, VS Code doesn’t exposes API for that (see https://github.com/alefragnani/vscode-project-manager/issues/213)

Hope this helps

**Comment by alefragnani** [comment]
I see two possible new features, so please, if you would like to see it in new releases, split them in separate issues for better tracking.

Thank you

**Comment by yume-chan** [comment]
I believe the side bar does support filtering, see Microsoft/vscode#50062

![image](https://user-images.githubusercontent.com/1330321/85151041-e0322a80-b285-11ea-9bb9-522f4a9fc3dc.png)

However all tree views shares the same filter mode (controlled by `workbench.list.keyboardNavigation`), maybe it worth another feature request on Code itself (I think it's ok).

**Comment by ManPython** [comment]
Thx for answers. I using Todo Tree like bookmaks. I'm confused with this, soo I decided to do some research and sugest solve all.
I often doing some biger issues. I hope that VSC can support some solutions for this EXT to do improvments in whole GUI.
Some of ideas are related with https://github.com/alefragnani/vscode-numbered-bookmarks
In facts I hate VSC console. In my option it's not good to rember many comands. It's in oposition with GUI, icons and view. Many VSC ext are like scripts or something, using VSC like LNX os. I long term this made wrong corelation in mind like interface to app :dagger: 
The plus icon is minimal now to improve adding bookmakr.

@yume-chan how you caling the filtering?

**Comment by alefragnani** [comment]
Hi @yume-chan ,

First of all, thank you for point that to @ManPython . I hope it works. Personally, I hate this filtering 😞 . What I need is an input field to type, but the VS Code team already closed a lot of request. So, I wouldn’t bother to open another request for something that I personally don’t like.

@ManPython , the idea behind VS Code is exactly that, a code editor focused on keyboard operations (like Sublime). It’s not an IDE and the team already reported they avoid a lot of “normal GUI elements”. I remember they had that description somewhere on the website. 

Just recentlythey had opened a few “visual elements APIs“, like the Side Bar and WebViews, and they are planning WebView also on Side Bar. No ETA yet
