### ISSUE TITLE
Cannot clone recursively: submodule vscode-bookmarks-core can’t be cloned

### ISSUE THREAD

**Issue by jankeromnes** [alefragnani/vscode-bookmarks#315]
Hello! Trying to recursively clone this repository currently fails with:

```
git clone --recurse-submodules https://github.com/alefragnani/vscode-bookmarks
[...]
Cloning into '/tmp/repository/vscode-bookmarks-core'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: clone of 'https://github.com/alefragnani/vscode-bookmarks-core.git' into submodule path '/tmp/repository/vscode-bookmarks-core' failed
Failed to clone 'vscode-bookmarks-core'.
```

Also, visiting https://github.com/alefragnani/vscode-bookmarks-core gives me a 404 page.

**Comment by jankeromnes** [comment]
Same issue while trying to recursively clone https://github.com/alefragnani/vscode-project-manager

**Comment by alefragnani** [comment]
Hi @jankeromnes ,

Both extensions are being refactored, and right now, can’t be fully cloned, sorry.

Hope this helps
