### ISSUE TITLE
Hovering the mouse over bookmark should display the label

### ISSUE THREAD

**Issue by thatcashcow** [alefragnani/vscode-bookmarks#318]
<img width="113" alt="label" src="https://user-images.githubusercontent.com/53687035/86090290-6b51c280-bac7-11ea-8b71-7f68e748ba4a.png">

**Comment by alefragnani** [comment]
Hi @thatcashcow ,

That’s an interesting idea, but unfortunately VS Code doesn’t provide any API for that. The gutter is very limited.

Based on other _still opened and/or closed_ requests, specifically about the gutter, I wouldn’t open a one.

If they provide something in the future, I would reopen your issue

Hope this helps
