### ISSUE TITLE
Show line numbers for bookmarks in the Side Bar

### ISSUE THREAD

**Issue by cateyes99** [alefragnani/vscode-bookmarks#321]
Currently in the Side Bar's `Bookmarks Explorer`, no line numbers are shown for bookmarks. It'd be more informative & convenient to have the line number shown in front of each bookmark.

**Comment by alefragnani** [comment]
Hi @cateyes99 ,

The Side Bar shows both, line and column number, for each bookmarked line. 

It is displayed as a _detail_ on each line, following the line content/bookmark label.  

_Icon + LineContent/BookmarkLabel + (Ln X, Col Y)_ 

![Screen Shot 2020-07-09 at 17 16 55](https://user-images.githubusercontent.com/3781424/87086492-0d7c5380-c208-11ea-8de8-38fe2dd00366.png)

Hope this helps

**Comment by cateyes99** [comment]
ic. It turned out that if the length of the line bookmarked is very long then the line & column info has not room to display which is not good. For instance, in your screenshot, the bookmark in the **CHANGELOG.md** file doesn't show the line & column info. 🙄

**Comment by cateyes99** [comment]
i would say it's a bug then. @alefragnani

**Comment by alefragnani** [comment]
> It turned out that if the length of the line bookmarked is very long then the line & column info has not room to display which is not good

That’s how VS Code works. The same happens on other native views, like the Search view, when you search for text. It displays the file path as a _detail_, but if the file name is long and the panel is not wide enough to, you won’t see the file path.

I understand it’s not _that good_, but if you think it is a bug, I would say it’s a VS Code bug. You should report that on VS Code repo

Hope this helps

**Comment by cateyes99** [comment]
hmm. if it's a limitation from **VSCode**, what about placing the line number info at the beginning instead of at the end then?

**Comment by alefragnani** [comment]
Because I think the line contents/bookmark label are more important than its position.

But, there is however, issue #145, which requests "customizable line". So, it would allows each developer decides the info it finds more importantly be seen.

Feel free to upvote/comment if you think it would fit your scenario.

Hope this helps

**Comment by cateyes99** [comment]
If there are many bookmarks in a file, I'd say the line info is very convenient (the column info isn't though). But i vote for #145 then.
