### ISSUE TITLE
Can release the old versions?

### ISSUE THREAD

**Issue by NeptuneZhang** [alefragnani/vscode-bookmarks#322]
In company's computer, VS code is forbidden to upgrade due to IT policy. New version of bookmark plugin is not compatible.

**Comment by alefragnani** [comment]
Hi @NeptuneZhang,

When I update the extension with a bump in the minimum VS Code version, it's mainly because it requires a new API, available only on that VS Code version.

So, newer releases of Bookmarks won't work on older VS Code releases. I'm sorry.
