### ISSUE TITLE
Auto format

### ISSUE THREAD

**Issue by ProtocolLive** [alefragnani/vscode-bookmarks#323]
There is an error: when I use the Alt + Shift + F shortcut to automatically format the document, the markers go elsewhere or disappear

![1](https://user-images.githubusercontent.com/39626142/87851886-5fda0600-c8d3-11ea-93df-093ce63cbe6d.jpg)
![2](https://user-images.githubusercontent.com/39626142/87852140-b5afad80-c8d5-11ea-8481-9552dcbbdfcc.jpg)

**Comment by alefragnani** [comment]
Hi @ProtocolLive ,

The extension still doesn't support Formatters properly. Sometimes the bookmarks moves, and sometimes, are removed, sorry.

I have added a _workaround_ sometime ago, until the proper support is added. Just set `"bookmarks.useWorkaroundForFormatters": true`. You can see more details in #118 .

The downside? You lose the Bookmark's _sticky_ behaviour. It means the bookmarks will be tied to the line _number_, not the line _of code_. So, if you add new lines above a bookmark, it will not be _moved down_.

Hope this helps
