### ISSUE TITLE
Dead Link for Submodule 

### ISSUE THREAD

**Issue by javalight** [alefragnani/vscode-bookmarks#330]
Seems the [vscode-bookmarks-core@765c6db](https://github.com/alefragnani/vscode-bookmarks-core/tree/765c6db5003ef2cc0d20e8965c68e4e97ce4c5e2) submodule link is broken. Cant clone submodules.

**Comment by javalight** [comment]
Seems core repo is private, is it possible to open it to public?

**Comment by alefragnani** [comment]
Hi @javalight ,

That's correct, right now the core repo is private,

I started refactoring the extension, to share pieces with my other Numbered Bookmarks extension, but it took more time/effort that I though, so I’m still thinking on the better model to re-open the extension to contributions.

Thank you
