### ISSUE TITLE
Jump to next shortcut not working anymore :( 

### ISSUE THREAD

**Issue by Shahor** [alefragnani/vscode-bookmarks#331]
Hello 👋 

Thank you very much for this extension, huge improvement on vscode <3

Sadly, as of late I've noticed the `cmd + alt + l` for `jump to next` doesn't work anymore :'(
This just stopped working and to my knowledge I don't have apps overriding that shortcut. 

Bookmarks version: 11.3.1
Vscode: 1.49.0

Let me know if I can provide any more helpful informations

**Comment by alefragnani** [comment]
Hi @Shahor ,

Thanks for your kind words. I’m glad to know the extension helps you 👍 

You are probably facing a _shortcut conflict_ with other **extension**, or VS Code itself. I know Linux uses this shortcut as well.

You could check for conflicts using the `Preferences: Open Keyboard Shortcuts` command. Then, just type `Ctrl Alt L`, and VS Code will show all commands with this keyboard shortcut.

Hope this helps

**Comment by Shahor** [comment]
![image](https://user-images.githubusercontent.com/204561/93073472-48c15580-f683-11ea-84b5-2ee6c50134d1.png)

I have conflicts indeed, but vscode doesn't make it easy knowing where those come from 🤔 
They don't seem linked to an extension though 🤔

**Comment by alefragnani** [comment]
Yep, it’s not that easy. I think the user should be notified when this happens (at least a warning message) but it doesn’t.

If it’s not related to some extension, it must be _native_ (VS Code itself). Probably added in recent releases.
