### ISSUE TITLE
[Feature] Make bookmark Quick Pick (List From Files) display as stack of last bookmark jumps.

### ISSUE THREAD

**Issue by javalight** [alefragnani/vscode-bookmarks#334]
Would be great if the quick pick remembered the last location jumped, displaying bookmarks as a list of last location jumps, instead of the not very useful file location order.

**Comment by alefragnani** [comment]
Hi @javalight ,

There is already an open issue for that #183. Please, upvote that issue so it's easier for me to keep track of the requests.

Hope this helps
