### ISSUE TITLE
[QUESTION / FEATURE] - How to create a command that saves a bookmark directly into a fixed label ?

### ISSUE THREAD

**Issue by njoppi2** [alefragnani/vscode-bookmarks#336]
Hello! I use a extension very similar to vim, which lets me configure my keys to execute commands with just one click, like moving around, copying, selecting, etc. And one thing that i'm trying to find like crazy is a bookmark extension that lets me save a bookmar with a particular index/label with just one command (in your extension we need to execute bookmarks.toggleLabeled, and then write the number up there), is there a way do to somenthing like bookmarks.toggleLabeled2, and then a bookmarks.jumpTo2? Or like this { "command": "bookmarks.toggleLabeled", "args": "2" }? This would be AMAZING, seriously, for everyone that uses a vim-like extension and wants fast bookmarks.

**Comment by alefragnani** [comment]
Hi @njoppi2 ,

I don't use Vim myself, but _I heard stories about those peoples_ 😆 , and I understand what you are trying to achieve.

You could try to play with `bookmarks.label.suggestion` setting. It allows you to define if the `Toggle Labeled` command would _suggest_ a label to you:

* `dontUse`: Don't use the selection (original behavior)
* `useWhenSelected`: Use the selected text (if available) directly, no confirmation required
* `suggestWhenSelected`: Suggests the selected text (if available). You still need to confirm.
* `suggestWhenSelectedOrLineWhenNoSelected`: Suggests the selected text (if available) or the entire line (when has no selection). You still need to confirm

This setting give you just the `Toggle` side of the story. For `Jumping`, maybe #325 would be a good solution too

Another idea is to use my other [Numbered Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) extension, but it only gives you 10 bookmarks _per file_

Hope this helps

**Comment by njoppi2** [comment]
@alefragnani About your other extension, it is PERFECT, it exactly what I need without only one thing, which is the reason that I'm using this extension and not that one: It jumps to the beggining of the line, not were the cursor was :(, this single thing makes it unusable for me as a pseudo-vim user. Because I use your bookmarks for very fast things, like toggling the line, going up 5 lines, and jumping back (loooots of times), and if it goes back to the begging, it's not very useful for me :/
So I think this would be a feature request for your other extension, can you put a setting there like a boolean, anything, that let's me chose to use that extension with inline cursor saving?

**Comment by alefragnani** [comment]
Yep, that's one of the missing features when you compare both. This feature, in fact, already has an issue on the repo https://github.com/alefragnani/vscode-numbered-bookmarks/issues/14. But no ETA, for now.

My intention is to "upgrade" the **Numbered Bookmarks** to receive all features you see today on **Bookmarks**

Hope this helps

**Comment by alefragnani** [comment]
Hi @njoppi2 ,

The https://github.com/alefragnani/vscode-numbered-bookmarks/issues/14 feature will be available in the next release of **Numbered Bookmarks**, planned for the [February](https://github.com/alefragnani/vscode-numbered-bookmarks/milestone/17).

Hope you enjoy 😁

**Comment by njoppi2** [comment]
Awesome!!

**Comment by alefragnani** [comment]
Hi @njoppi2 ,

Just released version 8.0 of the [Numbered Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) extension. It contains a lot of great features, including [that one - #14](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/14)

### Added
- Improvements on multi-root support (issue [#92](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/92))
- Multi-platform support (issue [#94](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/94))
- Support Remote Development (issue [#63](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/63))
- Support Column position (issue [#14](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/14))

The Bookmarks extension, with similar features, is planned (https://github.com/alefragnani/vscode-bookmarks/milestone/38) to be released this weekend.

Enjoy
