### ISSUE TITLE
Undo breaks the bookmark

### ISSUE THREAD

**Issue by sergiubacioiu** [alefragnani/vscode-bookmarks#337]
I just installed the vscode Bookmarks extension but I found a bug in the first minute.

When you create a new bookmark if you add a new line before the bookmark by mistake and you press Ctrl+Z to undo that the bookmark jumps a few lines down.

![Bookmarks Bug](https://i.imgur.com/q6qgz6T.gif)

**Comment by alefragnani** [comment]
Hi @sergiubacioiu ,

Yes, unfortunately it happens sometimes. Still needs proper fix.

This is already being tracked in #116, and I'm planning to take a better look on this on the upcoming releases.

Hope this happens
