### ISSUE TITLE
[FEATURE] - Expand All

### ISSUE THREAD

**Issue by cateyes99** [alefragnani/vscode-bookmarks#345]
I'm analysing a big project, so have set up a lot bookmarks for this. Later after I clicked the `Collapse All`, I found that there is no way to expand all, as there is no `Expand All` button at all. So I tried to reload and reopen the project both, all bookmarks are still collapsed (even if all bookmarks were expanded after reloading/reopening, it'd be still not ideal as I might not want to reloading/reopening the project at that moment just because of this). That's quite inconvenient now in this situation, I had to manually click on each file to expand them one by one ...

**Comment by alefragnani** [comment]
Hi @cateyes99 ,

This is already being tracked in #267. 

I'm planning the roadmap for upcoming releases, and I guess this one could be available soon.

Hope this helps
