### ISSUE TITLE
[FEATURE] - remove additional files (from git submodules) while packaging the extension

### ISSUE THREAD

**Issue by KevinBuchs** [alefragnani/vscode-bookmarks#355]
- Extension version: 11.4.0
- VSCode version: 1.51.1
- OS version: Ubuntu 20.04

**Steps to reproduce**

1. Install extension
2. Find in the extension directory ~/.vscode/extensions/alefragnani.bookmarks-11.4.0 these subdirectories: vscode-bookmarks-core and vscode-whats-new. Each of these contain files named ".git". In the first one, that is all that is in the directory. 
3. These files are messing up my application that backs up git working directories, because these look like they might be. I can't imagine what use these files are.

**Comment by alefragnani** [comment]
Hi @KevinBuchs ,

These `.git` files appears to be from the _git submodules_ that the extension uses. It appears the tool used to build/package extensions (`vsce`) doesn’t support git submodules.

I’ll take a look if this could be added to the tool, or if the extension itself must ignore those files.

Thanks for reporting

**Comment by alefragnani** [comment]
The VS Code team already updated `vsce` to ignore git submodule related files. It will be available in upcoming November release. 

Update the extension after that

**Comment by KevinBuchs** [comment]
OK, thanks!

Kevin Buchs, Senior Engineer, New Context Services <https://newcontext.com>
kevin.buchs@newcontext.com  507-251-7463  St. Cloud, MN

**Comment by alefragnani** [comment]
Tested with vice 1.83 and it works.

Closing as there is nothing to do. The next publishing will work as expected
