### ISSUE TITLE
[BUG] - bookmark move

### ISSUE THREAD

**Issue by webrod** [alefragnani/vscode-bookmarks#356]
**Environment/version**

- Extension version: 12
- VSCode version:  1.51.1
- OS version: Windows 10

**Steps to reproduce**

1. bookmark a line, e.g line 10 which map to "echo $foo"
2. insert a blank line before. so ""echo $foo"" is now line 11 and the bookmark is now on that line 11 (OK)
3. press CTRL-Z (to cancel the inserted line).  my line "echo $foo" has moved back to line 10, but bookmark is still on line 11!! so wrong line

**Comment by alefragnani** [comment]
Hi @webrod ,

Thanks for reporting. This error is already being tracked in #116 .

Closing as duplicate
