### ISSUE TITLE
[FEATURE] - Add customization for OverviewRullerLane (size/placement)

### ISSUE THREAD

**Issue by robross0606** [alefragnani/vscode-bookmarks#357]
The indicators in the overview ruler are a bit overpowering compared to other indicators which don't take up the whole line.  It would be nice to be able to control the color (transparency, etc.) and placement (left, middle, right, full).

**Comment by alefragnani** [comment]
Hi @robross0606 ,

It is already possible to define the transparency. You just have to provide the required value after the `RGB`, like: 

```
"workbench.colorCustomizations": {
    "bookmarks.overviewRuler": "#ff0000ee",
}
```

More details in VS Code docs https://code.visualstudio.com/api/references/theme-color#color-formats.

About the _placement_, yes, it could be customizable.

Thanks for the suggestion

**Comment by robross0606** [comment]
Thanks, where is this color property covered in the documentation?  I must’ve missed it.
