### ISSUE TITLE
Show "What's New in Bookmarks" page somtimes when i make a new vscode window

### ISSUE THREAD

**Issue by haishen121** [alefragnani/vscode-bookmarks#358]
Issue Type: <b>Bug</b>

As described in the title. When i make a new vscode windows from start menu,it will open the page. Not every time, but very often

Extension version: 11.2.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-193-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4100 Quad-Core Processor             (4 x 3624)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|17.98GB (7.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.4.0-193-generic|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3900)|
|Memory (System)|7.69GB (0.79GB free)|
|VM|0%|
</details>

**Comment by alefragnani** [comment]
Hi @haishen121 ,

The **What's New** window only appears when a new version is installed. The idea is to have a monthly release cycle, at minimum.

What may have happened in your case, is that VS Code downloaded the new version and when you created a New Window, that New Window received the updated version. VS Code doesn't update all instances at once.

Hope this helps

**Comment by haishen121** [comment]
I have confirmed that all are the latest version, but it still appears, even if i restart the computer

**Comment by alefragnani** [comment]
If you see the window when you restart your computer, it seems VS Code is not being able to save/load its _global state_. Just like a **clean state** every time you start VS Code.

The extension uses this _global state_ to store the _installed version number_, so when VS Code updates the extension, the _new version_ is greater than the _installed version_.

Hope this helps

**Comment by haishen121** [comment]
It's ok after reinstalling it
