### ISSUE TITLE
Hi Alessandro, your extension is so helpful but i experment tag messing around (tag jump to over line) as soon as i reopen vs code so i have to manually relabel each line which is a bit annoying and time wasting[BUG] - 

### ISSUE THREAD

**Issue by DamienAlb** [alefragnani/vscode-bookmarks#359]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1. 
2.

**Comment by DamienAlb** [comment]
Hi Alessandro, your extension is so helpful. Unfortunately I am currently experiencing tags messing (tag jump to over line messing with label) as soon as I re-open vs code so I have to manually relabel each line which is a bit time consumming. Do you have heard aboput this issue already ? - 
Extension : V 12.0.0
VS Code : V 1.51.1
OS : Elementary OS 5.1.7 Hera

**Comment by alefragnani** [comment]
Hi @DamienAlb ,

I'm not sure I understand your scenario. Are you saying the **Labeled** bookmarks are losing its **Labels** when you reopen VS Code? But the bookmark position (line and column) remains correct?

If that is the case, no, I never heard about it.

If not, could you provide more details about the issue?

Hope this helps

**Comment by DamienAlb** [comment]
Hope this be more explicit, a bookmark attach to a comment for example doesn't stick in a ccs file to the comment when a bunch of code is added meaning that i hace to remove and retag bookmark to the correct line.

**Comment by alefragnani** [comment]
You are probably facing a Formatter related issue.

If you have Formatters like Prettier, or anything that runs _on save_, the extension doesn't recognizes _all the changes_, so until properly handled, you should try to use the workaround defined in #118 (`"bookmarks.useWorkaroundForFormatters": true`)

The downside, the bookmarks will be glued to the _line number_, not the _line content_.

Hope this helps

**Comment by alefragnani** [comment]
If you don't use Formatters, maybe you are facing a undo issue, reported in #116.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
