### ISSUE TITLE
[BUG] - Bookmark icon in editor margin disallow for enable/disable breakpoints

### ISSUE THREAD

**Issue by uselessscat** [alefragnani/vscode-bookmarks#365]
**Environment/version**

- Extension version: 12.0.0
- VSCode version: 1.53.0-insiders
- OS version: W10 pro 20H2 19042.685

**Steps to reproduce**
There are two cases of this problem, 
 - When you create a bookmark and then you want to mark a line as a breakpoint in the editor margin
   1. Create a bookmark in some line
   2. Try to mark the line as a breakpoint
   ![image](https://user-images.githubusercontent.com/15332878/102791643-10b66680-4386-11eb-8c27-1cdb75dd5426.png)
 - When you toggles a line as a breakpoint and then you want to disable it after marking as a bookmark
    1. Create a breakpoint using the editor margin
    2. Use rigth click to toggle a bookmark
    3. Try to disable breakpoint from the margin
    ![image](https://user-images.githubusercontent.com/15332878/102791813-583cf280-4386-11eb-8b44-0e9dbaf8c0e4.png)

**Comment by alefragnani** [comment]
Hi @uselessscat ,

This is caused by VS Code, which still doesn't properly handle both icons. It has been already reported in #56, but the VS Code issue is still open. The original VS Code issue is https://github.com/microsoft/vscode/issues/5923

Hope this helps
