### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by brianking** [alefragnani/vscode-bookmarks#374]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the Eclipse Publisher Agreement on or before January 8, 2021. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is explained in the Wiki (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

If you are the project maintainer, we urge you to claim the namespace for your extension(s). To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by brianking** [comment]
@appelgriebsch Bringing this issue to your attention as you have not seen it, and you published this extension in the registry.

**Comment by Kreijstal** [comment]
If the mantainer doesnt want to sign, can someone sign a fork up?

**Comment by brianking** [comment]
> If the mantainer doesnt want to sign, can someone sign a fork up?

If the license permits, this is possible. I'd be wary that it is not a one-time deal, however, meaning that whatever version that is added is maintained and kept up to date.

@alefragnani What do you think?

fyi more about Open VSX here:
https://www.eclipse.org/community/eclipse_newsletter/2021/january/1.php

**Comment by mclang** [comment]
I wish this could be done rather soon than later :pray: 

Missing auto-updates of this great extension right now :/

**Comment by alefragnani** [comment]
Just claimed the namespace https://github.com/EclipseFdn/open-vsx.org/issues/2445

**Comment by alefragnani** [comment]
The namespace claim was assigned. Ready to publish.

**Comment by alefragnani** [comment]
Hi,

I just published the new [release 13.5.0.](https://github.com/alefragnani/vscode-bookmarks/milestone/50) to Open VSX.

Thank you for your patience.
