### ISSUE TITLE
Bookmark title on hover?

### ISSUE THREAD

**Issue by ernal69** [alefragnani/vscode-bookmarks#375]
Is it possible to make the name of the bookmark appear (tool tip type bubble) when you hover over the bookmark in the code editor?
It would be extremely handy to be able to quickly scan bookmarks this way.

**Comment by alefragnani** [comment]
Hi @ernal69 ,

This has been already requested before in #250 and #318, but it depends on VS Code APIs, which doest not exists today, nor has been planned (https://github.com/microsoft/vscode/issues/28080).

I'm subscribed to that issue, so if/when the VS Code team releases the API, I could add to the extension.

Hope this helps
