### ISSUE TITLE
[FEATURE] - drag & reorder in side bar

### ISSUE THREAD

**Issue by LighghtEeloo** [alefragnani/vscode-bookmarks#378]
Drag the side bar files and reorder as in the vscode explorer.

Possible implementation: read from the json file, find the src index, find des index, pop and insert.

Significance: This is very convenient for sorting out the bookmarks.

**Comment by alefragnani** [comment]
Hi @LighghtEeloo ,

Unfortunately, this is no API available for drag and drop. There is an open issue asking for this on VSCode repo https://github.com/microsoft/vscode/issues/32592, but no ETA.

Hope this helps

**Comment by LighghtEeloo** [comment]
Thank you @alefragnani .

Sorry I didn't expect it to be such an impossible task. >_<   
I guess we'll have to wait then.

But this extension is still very helpful, I've been enjoying it. Thanks!

**Comment by alefragnani** [comment]
No need to be sorry. I agree it is an unexpected limitation, but I think it would be available somewhere in the future.

I’m glad to know you like the extension. It’s one of my favorites 😬 

Thank you

**Comment by alefragnani** [comment]
Hi @LighghtEeloo ,

Instead of drag and drop, wouldn’t sorting (#435 ) or grouping (#159 ) be  alternatives?

**Comment by LighghtEeloo** [comment]
I agree. That can be a solution.

Tired of waiting for vscode team to get the drag and drop done, I think the alternatives aren't bad.

Feel free to close. If anything new happens to the API, I'll consider open again. Thank you :-)

**Comment by alefragnani** [comment]
That's great! I'm planning both features for upcoming releases.

Stay tuned.

**Comment by AgainPsychoX** [comment]
Bump? Is the drag & drop API available now? https://github.com/microsoft/vscode/issues/145577
