### ISSUE TITLE
[BUG/QUESTION] - Repository 'vscode-bookmarks-core' not found.

### ISSUE THREAD

**Issue by drizbit** [alefragnani/vscode-bookmarks#379]
**Environment/version**
- Extension version: 12.1.4 (14ab8df4f09b7569fb89df4ffcebd58f7cb4f562)
- VSCode version: 1.52.1
- OS version: Windows 10 Education - Version 20H2 - Build 19042.746
    - Development container - `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-buster`

**Description**
It appears that the `vscode-bookmarks-core` repo/submodule you use has been made private or removed, and thus this extension cannot be properly build in a development environment.

I found reference [here](https://gitmemory.com/issue/alefragnani/vscode-numbered-bookmarks/54/490299497) that you are currently refactoring this repo. However, would it still be possible to keep this repo public while you are performing the refactor, so public contributions can continue?

**Steps to reproduce**
```
$ git clone https://github.com/alefragnani/vscode-bookmarks.git
$ cd vscode-bookmarks
$ git submodule init
$ git submodule update
```

**Comment by alefragnani** [comment]
Hi @drizbit ,

Thank you for your interest, but I’ll keep it close until the refactoring is finished.

**Comment by elesbb** [comment]
> Hi @drizbit ,
> 
> Thank you for your interest, but I’ll keep it close until the refactoring is finished.

It's been 2 years and its still closed.. any chance in opening it up? I tried to make changes to solve my issue here: #595 
But I can't test it cause I can't build it..

**Comment by vino4all** [comment]
@alefragnani do you have any plans to open the `vscode-bookmarks-core` submodule?
