### ISSUE TITLE
Jumping to next bookmark opens a new buffer when same buffer is open in another split panel

### ISSUE THREAD

**Issue by steelsojka** [alefragnani/vscode-bookmarks#38]
OS: Linux and MacOS
version: 0.9.2

Steps to reproduce:
1. Open to files and split them vertically
2. Create a book mark in each file
3. Focus one buffer and jump to next tag

Expected:
The cursor should jump to the buffer in the split.

Actual:
A new buffer was open with the file in the current split.

Here's a video of the reproduction:
![bookmarks-issue](https://cloud.githubusercontent.com/assets/2062154/18914658/a5791308-8553-11e6-8d90-ac5780431005.gif)

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/13639

**Comment by alefragnani** [comment]
Now depends on https://github.com/Microsoft/vscode/issues/15178

**Comment by edgardmessias** [comment]
Working fine on VSCode 1.25.1, Bookmarks 9.0.1

**Comment by alefragnani** [comment]
I'm closing this issue because the VS Code issue that it depends on, has no update from VS Code team members for more than a year. It is also not planned on any Milestone, so it appear it will not be released soon. 

I'm subscribed to that issue, so if/when it is closed, I'll be notified.

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.
