### ISSUE TITLE
Please change the activation policy for the welcome page so that the welcome page of Bookmark does not pop up every time you open VS Code

### ISSUE THREAD

**Issue by scienceplus** [alefragnani/vscode-bookmarks#380]
Please modify the activation strategy of the welcome page, so as not to pop up the welcome page of Bookmark every time you open vscode, it's really annoying, thank you

**Comment by alefragnani** [comment]
Hi @scienceplus ,

The What's New page is not displayed every time you open VS Code, but only when a new version is installed. Unless you are referring to **Codespaces** and/or **Remotes**. For this scenarios, there is already an open issue on the repo responsible for the What's New feature (https://github.com/alefragnani/vscode-whats-new/issues/23).

There is also another issue referring to extensions installed via the new Settings Sync feature on VS Code #377.

This issues are planned for the next release.

Hope this helps
