### ISSUE TITLE
[BUG] - bookmarks are deleting with adjoining blocks

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [alefragnani/vscode-bookmarks#389]
**Environment/version**

- Extension version: v13.0.1
- VSCode version: 1.53.2
- OS version: Windows 10

**Steps to reproduce**

1. Add some lines to saved file (bookmarks don't work with unsaved files)
2. Add a bookmark to a line in the middle
3. Select two or more lines before the bookmarked line ending selection on the previous line to the bookmarked one
4. Delete the block by hitting 'Del' or "BkSpace" key
5. A bookmark will disappear

**Comment by alefragnani** [comment]
Hi @SergeyBeloglazovRL ,

It seems you are facing the same issue as #168 and/or #116 . I'm planning to work on this, and hopefully make some improvements, on the next release.

Hope this helps
