### ISSUE TITLE
[BUG] - Bookmarks on deleted/missing files breaks jumping

### ISSUE THREAD

**Issue by yigalirani** [alefragnani/vscode-bookmarks#390]
setting bookmarks.wrapNavigation =True doesn't seems to have any effect
version 13.0.01

**Comment by alefragnani** [comment]
Hi @yigalirani ,

I just tested the `wrapNavigation` setting as `true` and `false`, combined with `navigateThroughAllFiles` also as `true` and `false`, and it appear to be working. But, I found an issue, and maybe it is your scenario.

Do you remember if you have added bookmarks to some _Untitled_ or _deleted_ file? In both cases, no error message is displayed, but the `Jump` does work.  

Could you please open the `Developer Tools` and look at `Console` tab for errors? If that's the case, you may see something like:

```
Error: cannot open file:///Untitled-1. Detail: Unable to read file '/Untitled-1' (Error: Unable to resolve non-existing file '/Untitled-1')
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
stack trace: Error: cannot open file:///Untitled-1. Detail: Unable to read file '/Untitled-1' (Error: Unable to resolve non-existing file '/Untitled-1')
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:109144
```

Thank you

**Comment by yigalirani** [comment]
hi @alefragnani
I just checked with the developer tools, and I did see lots of errors regarding a deleted file. I deleted the bookmark that i had there and now its working again, thanks!
Here is the message:
`console.ts:137 [Extension Host] stack trace: Error: cannot open file:///c%3A/Users/YigalIrani.AzureAD/yigalprod/beast/layers.js. Detail: Unable to read file 'c:\Users\YigalIrani.AzureAD\yigalprod\beast\layers.js' (Error: Unable to resolve non-existing file 'c:\Users\YigalIrani.AzureAD\yigalprod\beast\layers.js')    at file:///C:/Users/YigalIrani.AzureAD/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:109144`

**Comment by alefragnani** [comment]
Hi @yigalirani ,

That’s great to see you could update the bookmarks and returned to work. And that the error is the one I suspected.

It should be fixed soon.

Thank you

**Comment by bolinfest** [comment]
This is not working for me as I would expect. I can confirm this is what I have in `settings.json`:

```
  "bookmarks.wrapNavigation": true,
  "bookmarks.navigateThroughAllFiles": true,
```

I only have one [remote] file open, and when I do **Bookmarks: List from All Files**, I see the two bookmarks in the file I have open, as expected.

However, I have to use both **Jump to Next** and **Jump to Previous** whereas I would expect to be able to use just one of the shortcuts and cycle between my two bookmarks.
