### ISSUE TITLE
Large file support(?)

### ISSUE THREAD

**Issue by mjhilt** [alefragnani/vscode-bookmarks#392]
I was excited to try this extension to mark some lines in a large log file (~156MB). When I try to mark a line, it pops up a dialog that says "Open a file first to toggle bookmarks".

Marking other source files (of reasonably small size) seems to work. It is a pure guess as to why this particular file isn't working. It is named, and I've closed/opened it several times + restarted VS Code.

**Comment by alefragnani** [comment]
Hi @mjhilt ,

This has been discussed a few times, but unfortunately, it’s a VS Code limitation, and there is nothing I can do to fix. 

VS Code does not properly activates extensions when you open large files, and in the end, the extension does not know a file has been opened. That’s the reason for that message. More info in #31 . 

Hope this helps
