### ISSUE TITLE
Bookmark toggle doesn't work if document doesn't change

### ISSUE THREAD

**Issue by Lsystems** [alefragnani/vscode-bookmarks#393]
All went well until yesterday, I use F2+Space after to toggle a bookmark, and it used to work perfectly.
Now I have to change something on the document to activate the bookmark.
It doesn't do more with direct command, same symptom.

Was in VSC 1.51, update to 1.53.2 to fix the problem, doesn't change anything.
And one thing I remark : 
![image](https://user-images.githubusercontent.com/6932869/108239611-602ccf00-714a-11eb-9c4b-ee314308cf5b.png)

**Comment by alefragnani** [comment]
Hi @Lsystems ,

This is an error related to Untlitled documents, and is being tracked in #391. 

Thanks for reporting
