### ISSUE TITLE
[BUG] - command 'bookmarks.toggle' not found error in V13.0.1

### ISSUE THREAD

**Issue by retrevino** [alefragnani/vscode-bookmarks#395]
Hi Alessandro, good job with this Extension, I like so much, thanks for it!

**Environment/version**
Windows

- Extension version: 13.0.1
- VSCode version: 1.53.2 - Installed as [Portable Mode](https://code.visualstudio.com/docs/editor/portable)
- OS version: Windows 10 - 20H2

**Steps to reproduce**

1. Open VSCode
2. Open a Workspace that I already have; The workspace has many files open from various folders, using the _File / Open File ..._ menu option.
3. On any line, type Ctrl + Alt + K
4. Show error _command 'bookmarks.toggle' not found_

**Bookmark works fine if I open a single file or a Workspace from a Source Control, I don't use the _Open Folder_ option.**

The `saveBookmarksInProject` setting is off.

I read the issue [#387](https://github.com/alefragnani/vscode-bookmarks/issues/387), and followed the steps to uninstall and reinstall the extension, but it still won't activate for this particular case.

I've been using VSCode in [Portable Mode](https://code.visualstudio.com/docs/editor/portable) for several versions of VSCode, just like this extension (Bookmark), and it was working all right.

Regards.

**Comment by alefragnani** [comment]
Hi @retrevino ,

Thanks for your kind words. I'm glad to know you like the extension 👍 .

About the issue, if VS Code version is not an issue, could you check for errors on the console? Call `Developer Tools` and select `Console`

Do this right after you open VS Code, and follow the opening of your workspace. Let's see if the extension raises some error, like #390.

I have found a fix for the `Untitled` files issue, and I guess "missing" files would follow a similar approach, but I still need to make it save/load the bookmarks, so it would be properly stored/restored when you reopen VS Code.

Hope this helps

**Comment by retrevino** [comment]
Thanks for your prompt response.

I followed the steps you show me.
1. I started the VSCode, which by default loads the Workspace that was open the last time the VSCode was closed.
2. I opened the Developer Tools.
3. In the file shown by default, in which I was working, I selected a line and pressed Ctrl + Alt + K, and it showed the error, _command 'bookmarks.toggle' not found_.

I add the Log that the Console generated for the _Bookmarks_ Extension.

```
/C:/PortableApps/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:1734 Activating extension 'alefragnani.Bookmarks' failed: Cannot read property 'uri' of undefined.
_logMessageInConsole @ /C:/PortableApps/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:1734
/C:/PortableApps/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:60 [Extension Host] Initialized vscode-mssql storage.
workbench.desktop.main.js:738 Command 'Bookmarks: Toggle' resulted in an error (command 'bookmarks.toggle' not found)
onDidChangeNotification @ workbench.desktop.main.js:738
(anonymous) @ workbench.desktop.main.js:738
fire @ workbench.desktop.main.js:55
addNotification @ workbench.desktop.main.js:740
error @ workbench.desktop.main.js:1604
accept @ workbench.desktop.main.js:646
async function (async)
accept @ workbench.desktop.main.js:646
(anonymous) @ workbench.desktop.main.js:623
fire @ workbench.desktop.main.js:55
(anonymous) @ workbench.desktop.main.js:560
fire @ workbench.desktop.main.js:55
(anonymous) @ workbench.desktop.main.js:560
```

**Comment by samli111** [comment]
I also experienced this issue yesterday. After adding an empty folder to the workspace, it works for me now. Previously the workspace did not have any folder.

**Comment by retrevino** [comment]
> I also experienced this issue yesterday. After adding an empty folder to the workspace, it works for me now. Previously the workspace did not have any folder.

Hi samli111!  Thanks for your workarround.

I have many workspaces where I don't use folders, just selectively open files. How can I open an empty folder in a workspace that I already have, without closing all my files? Doing this only leaves the Workspace with the folder empty.

**Comment by retrevino** [comment]
> I also experienced this issue yesterday. After adding an empty folder to the workspace, it works for me now. Previously the workspace did not have any folder.
 
Hi samli111! Thanks for your workarround. This worked for me too.

Greetings.

**Comment by samli111** [comment]
Hi @retrevino  You can create an empty folder, and then with your current workspace open, click VS file > add folder to workspace.
Hope it works for you.

**Comment by alefragnani** [comment]
Hi @retrevino,

Thanks for the log. I'll dig on it to find out if it matches the scenarios I found

Just out of curiosity, when you say _loads the Workspace that was open_, are you referring to a VS Code Workspace (`something.code-workspace` file with multiple root folders) or is just some VS Code window, with random files (no folder at all)?

Could you show a print screen of your `Explorer` tab?

Thank you

**Comment by alefragnani** [comment]
Hi @samli111 , 

Thanks for your help 👍 

Btw, could you provide the details on how your _workspace_ is? Is it a `something.code-workspace` multi root folder, or a VS Code window with random files (no folder at all)?

Thank you

**Comment by retrevino** [comment]
Hi @alefragnani!

I don't use the workspace with folders, I use it with randomly opened files (no folders at all) and save it as something.code-workspace.
I also use the VS Code with GitHub projects. In this scenario, Bookmarks does work.
I attach an image with the Explorer tab of a Workspace where I only have random files.

![WorkspaceBookmarks](https://user-images.githubusercontent.com/70597871/109039999-0d47a000-7693-11eb-9621-45227d1d68f1.jpg)

**Comment by retrevino** [comment]
Hi @alefragnani!

I did the following exercise.
1. I opened a new instance of VS Code.
2. I added files from a folder, dragging them, I put several Bookmarks in several files, I saved the Workspace with the name Test.
3. I closed the VS Code
4. I opened another instance of VS Code.
5. I opened the Test Workspace.

From here I checked how this turned out.

What I detected is that in certain files it does show the Bookmarks marks, but in others it does not, although it does have registered which files and lines are marked.

![Prueba2](https://user-images.githubusercontent.com/70597871/109042911-56e5ba00-7696-11eb-9aa1-5a1a1f495bcc.jpg)

But in other cases it has a mark where it was not registered in the Bookmarks panel.

Hope this helps you.

Greetings and thanks for your great work.

**Comment by samli111** [comment]
> Hi @samli111 ,
> 
> Thanks for your help 👍
> 
> Btw, could you provide the details on how your _workspace_ is? Is it a `something.code-workspace` multi root folder, or a VS Code window with random files (no folder at all)?
> 
> Thank you

Hi @alefragnani, again this bookmarks extension is very useful and thanks for the great job.

My workspace is `something.code-workspace`. It only contained some files, no folders.
Today I added an empty folder to the workspace and the issue disappeared.

**Comment by alefragnani** [comment]
Hi @samli111 ,

Thanks for your kind words. That's always great to know the extension is useful 👍 

TBH, I didn't know you could have a `code-workspace` with files only (no folder). I'm not sure how it works, because when you open `Workspace Settings` it does not show the file list, but only an empty `folders` entry. Anyway, I could reproduce the issue and I think the reason is only because of the _random files_ scenario, when you you _upgrade_ the extension (saved with v12 and opened in v13). If you _create/save_ the bookmarks with v13 and load with 13, it works. It appears to be a _migration_ issue (unsupported scenario).

I'm working on this, and I hope to release a fix ASAP. Since you found a workaround (add an empty folder on your workspace), I suggest you to wait for the fix.

**Comment by alefragnani** [comment]
Hi @retrevino ,

That's really weird 😕 . Showing bookmarks on the Side Bar, but not in the document is something that I didn't experienced.  Could you please expand the side bar and double check the line/column it displays on details (just to be sure it's the you you expect)?

Thank you

**Comment by alefragnani** [comment]
Just published v13.0.2, which should fix the issue.

Feedbacks are welcome 😬

**Comment by samli111** [comment]
Hi Alessandro, the issue can be reproduced with v13.0.2 as follows,

Environment/version: Windows 10
Extension version: 13.0.2
VSCode version: 1.53.2

Steps to reproduce,
1. At VSCode, uninstall bookmarks extension. Close VSCode.
3. Open VScode, install bookmarks extension (13.0.2). Close VScode.
4. Open VScode, open a txt file
5. Save workspace as test.code-workspace
6. On any line, type Ctrl + Alt + K 
Show error command 'bookmarks.toggle' not found

**Comment by alefragnani** [comment]
Hi @samli111 ,

Couldn't reproduce the error with the steps you provided. 

Just to be clear, the error I detected (and fixed) only happened when you _upgrade_ the extension. I mean, the error occurred when your _workspace with random files_ had bookmarks from v12 and you did upgrade to v13. In this case, the _migration_ process was failing (uncovered scenario).

Otherwise, if you start a new VS Code window, opening random files and toggling bookmarks, it is working, at least on my tests, bot on MacOS and Windows (the only I have available).

Could you pleas open the `Developer Tools / Console` to better detect _when_  the error occurs?

Hope this helps

**Comment by samli111** [comment]
Hi @alefragnani, 
Please see attached screen shot.
<img width="960" alt="toggleError" src="https://user-images.githubusercontent.com/28811093/110139755-60aba380-7da1-11eb-9e24-8e75b07d50b7.png">

**Comment by samli111** [comment]
Hi @alefragnani,
Please see attached screen shot.
<img width="960" alt="toggleError" src="https://user-images.githubusercontent.com/28811093/110141651-61ddd000-7da3-11eb-875b-69d7e3b4d59a.png">
