### ISSUE TITLE
Suggestion: Support more functions on bookmarked/unmarked lines

### ISSUE THREAD

**Issue by VictorBarrantes** [alefragnani/vscode-bookmarks#41]
Nice extension BTW. Are you considering to extend it to include functions like those found in Notepad++?

- Cut Bookmarked Lines
- Copy Bookmarked Lines
- Paste to (Replace) Bookmarked Lines
- Remove Bookmarked Lines
- Remove Unmarked Lines - leave only Bookmarked lines
- Inverse Bookmark
- Find based Bookmark (find <criteria> and mark the lines where <criteria> is found)

Just a suggestion, the extension is great already.

**Comment by alefragnani** [comment]
Hi @VictorBarrantes, thanks for your kind words :smile: 

I didn't know some of this commands from Notepad++, but you already can accomplish some of them if you combine with the newly created `Bookmarks (Selection): Select Lines` command. At least these:

- Cut Bookmarked Lines
- Copy Bookmarked Lines
- Paste to (Replace) Bookmarked Lines
- Remove Bookmarked Lines

The other commands are a bit different:

- Remove Unmarked Lines: I don't remember if there is a `Revert Selection` command in VSCode, or in any other extension, but that should be a way
- Inverse Bookmark: Honestly, it seems weird to me. Do you have any use case to share?
- Find based Bookmark: Isn't it like `Bookmarks (Selection): Select Lines`?

Hope this helps

**Comment by ADTC** [comment]
> Find based Bookmark (find and mark the lines where is found)

@alefragnani this is what I really miss from Notepad++ after moving to macOS. Basically, I can put a search term in the Mark dialog of NP++, and select "Also bookmark lines", and every line that is marked with that search term is also bookmarked.

Then I can cut/copy/remove bookmarked or unmarked lines so I can focus better on what's left. This is really useful for logs and such. Does your extension support this function already?

_(Thanks for bearing with me as I dig up an old issue.)_
