### ISSUE TITLE
[BUG] - Bookmarks doesn't work with 'Remote FS' extension

### ISSUE THREAD

**Issue by wojfr** [alefragnani/vscode-bookmarks#412]
You can create bookmarks, but you can't delete them because of error:
Error running command _bookmarks.deleteBookmark: Running the contributed command: '_bookmarks.deleteBookmark' failed.. This is likely caused by the extension that contributes _bookmarks.deleteBookmark.

**Comment by alefragnani** [comment]
Hi @wojfr ,

Could you run `Toggle Developer Tools` and select the `Console` tab, and provide the messages that are displayed?

I suppose you are able to `Toggle` bookmarks, on and off, directly in the editor, right? Or is it failing too?

I don't use `Remote FS` environments. The only _remote_ development scenario I have is via Docker, but I suppose both would handle files/resources fairly similar.

**Comment by wojfr** [comment]
![Screenshot 2021-03-13 225551](https://user-images.githubusercontent.com/80601432/111050867-6cf1c980-844f-11eb-8b06-8d65c15ed13e.gif)

**Comment by wojfr** [comment]
It's interesting that 'clear' (all bookmarks) works when 'allow bookmarks to be saved locally ...' is set to 'no', but when set to 'yes' it clears the list of bookmarks but dooesn't really delete them and bookmarks reappears after opening workspace again.

**Comment by alefragnani** [comment]
Just out of curiosity, do you have any _external (not inside the opened folder/workspace)_ or `Untitled` file, with bookmarks? 

There was an issue while trying to add bookmarks to `Untitled` files, which was partially fixed today (just released a patch one hour ago).

Hope this helps

**Comment by wojfr** [comment]
Any _external_ or _untitled_ files. Adding bookmarks works fine, The problem is with _delete_ and _edit label_. I have no local folders nor local files in workspace - maybe this is the reason. When _save bookmarks in project_ is ON external file _.vscode/bookmarks.json_ is created, and modified after adding new bookmark, but after clearing all bookmarks (no errors) or after deleting bookmark (with errors) doesn't change.

**Comment by wojfr** [comment]
After clearing all bookmarks _bookmarks.json_ doesn't change, but after setting new bookmark the file is correct - old entries deleted, and new one inserted. Hope this helps find the problem.

**Comment by alefragnani** [comment]
Hi @wojfr ,

I suppose this may had been fixed in release 13.4.2, with #645. Could you validate that?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
