### ISSUE TITLE
[FEATURE] - bookmarks classification  by  topic that is a callstack or a issue analysis or a function flow

### ISSUE THREAD

**Issue by sensornew** [alefragnani/vscode-bookmarks#415]
when need to read code for a issue ,  you would want to mark something to record your actions
then you can give it a name , ex: signal sequence etc.  ,  vs code can use this name to create a file which can include all the marks you will create.  you can save it to a file, and spread it to others colleague, they can load it and use it as they created by themselves

and , you can search your marks by a search window.

this idea comes from the difficulty of read a lot of code that you are not familiar, then the marks  can help remember.

**Comment by alefragnani** [comment]
Hi @sensornew ,

So you are asking for something like an **Export** feature, which would create a file with all your bookmarks in it?

**Comment by sensornew** [comment]
not only the Export feature,  mainly the **Classification** or **Group**  Feature,   and the **Search** Feature

**Comment by alefragnani** [comment]
Well, all these features has already been requested, so I suggest you to upvote those issues:

* Export: #172 
* Classification/Group set: #225 and #254
* Search: #325 

So, I’m closing it as a _duplicate_

Hope this helps
