### ISSUE TITLE
[FEATURE] - Create folders for bookmark organization

### ISSUE THREAD

**Issue by ariyo-live** [alefragnani/vscode-bookmarks#419]
We can continue the existing ui where the bookmarks are listed under files.  However, in creating a folder organization system, it allows developers to create folders for different development modes.  When working in one mode (e.g. information/resource development), the developer can access a folder with the bookmarks in the files associated with that mode (e.g. xml, json, txt, ...).  When working in code development mode, the developer can switch to using a different folder with different bookmarks associated with code files.  When switching to a testing mode, the developer can use another folder.  This would greatly enhance productivity on complex projects where developers have to wear many different hats (i.e. work in different modes).

**Comment by alefragnani** [comment]
Hi @ariyo-live ,

This is exactly what #225 and #254 asks, and the idea is to merge both on a single feature.

Hope this helps
