### ISSUE TITLE
Cannot manage breakpoints from gutter when bookmark is set

### ISSUE THREAD

**Issue by shadysamir** [alefragnani/vscode-bookmarks#420]
Issue Type: <b>Bug</b>

Set a bookmark on a line. Try to click the gutter to set a new breakpoint or manage an existing one. The bookmark icon gets in the way and I can't open the breakpoints submenu.

Extension version: 13.0.4
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-67-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.34GB (0.41GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id dae14284-8dd9-4b1a-94c5-d1680f539102|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by alefragnani** [comment]
Hi @shadysamir ,

Similar issues has been reported a few times (#107 , #218 , #251 ), but unfortunately it is caused by VS Code itself, which doesn’t click events properly when there are other _decorators_ on the gutter. At first the icons weren’t drawn correctly (which now partially works) but clicks are still an issue. 

The VS Code team is aware of the issue, and it is on their backlog to fix

Hope this helps
