### ISSUE TITLE
[BUG] - Undo will not adjust the bookmark to its target line

### ISSUE THREAD

**Issue by soletude-canada** [alefragnani/vscode-bookmarks#421]
- Extension version: v13.0.4
- VSCode version: 1.55.0
- OS version: Windows_NT x64 10.0.19041

**Steps to reproduce**

Here's a short video showing the bug in action, https://youtu.be/Q2M4LjGaGes

1. First, I copy paste a chunk of code (one or multiple times)
2. If I use the undo command, the bookmark won't track its target line properly.

**Comment by alefragnani** [comment]
Hi @soletude-canada ,

This is already being tracked in #116 and #168
