### ISSUE TITLE
[BUG] - Last project bookmark cannot be removed

### ISSUE THREAD

**Issue by ciscoheat** [alefragnani/vscode-bookmarks#422]
- Extension version: 13.0.4
- VSCode version: 1.55.0
- OS version: Win 10

**Steps to reproduce**
1. Set `"bookmarks.saveBookmarksInProject": true`
2. Add bookmarks
3. Remove them

What happens: The last bookmark is still kept in `bookmarks.json`. According to the panel, no bookmarks exists, but when closing and opening VS Code, the last one appears again.

**Comment by alefragnani** [comment]
Hi @ciscoheat ,

First of all, sorry for the delay. It's been a busy period these days.

I could reproduce the error. It also happens not only using the `Delete` command in the Side Bar, but also with the `Clear`command in the `Command Palette`. Really weird to be failing on this scenario.

I'll take a look and hopefully fix this for the next release

Thank you for reporting

**Comment by ciscoheat** [comment]
Hi, no problem, I understand completely about busy times! Thanks for fixing the problem and thank you for a great extension!

**Comment by alefragnani** [comment]
Thank you for your understanding. I'm glad you like the extension 👍
