### ISSUE TITLE
[BUG] - MacOS Darwin: bookmarks: toggle command not found

### ISSUE THREAD

**Issue by samkam** [alefragnani/vscode-bookmarks#423]
upon installing the extension, bookmarks do not appear, and Instead I get the following error message when attempting to bookmark ``Command 'Bookmarks: Toggle' resulted in an error (command 'bookmarks.toggle' not found)```

issue is present in 13.0.0 but not in 12.1.4

**Environment/version**
- Extension version:
13.0.0
- VSCode version: 
Version: 1.50.1
- OS version:
 Darwin x64 20.3.0
**Steps to reproduce**

1. install bookmarks 13.0.0 from marketplace in vs code
2. highlight text in open file 
2. open command palette, select `Bookmarks: Toggle` 
3. toast pop up with following error message appears: ```Command 'Bookmarks: Toggle' resulted in an error (command 'bookmarks.toggle' not found)```

**Comment by elder-n00b** [comment]
Extension 13.0.4 (2021-03-13)
VSCode 1.55.2
macOS 10.11.6 (Darwin x64 15.6.0)
Everything fine here.

**Comment by alefragnani** [comment]
Hi @samkam,

Is it still happening if you update to version 13.0.4? The four updates fixed a few scenarios, and it should be working now. Otherwise, could you please provide more details about the file/folder/workspace you are facing the issue?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.
