### ISSUE TITLE
[FEATURE] - Use vscode-style default bookmark

### ISSUE THREAD

**Issue by 4086606** [alefragnani/vscode-bookmarks#431]
The default blue bookmark is simple, BUT it looks 👀  when I'm using a dark theme.
~~It seems tree icons also custom SVG?~~

Since this extension was published, there is now [`ThemeIcon`](https://code.visualstudio.com/api/references/vscode-api#ThemeIcon) and `$(icon) label` so use native codicons in extension?

**Comment by alefragnani** [comment]
Hi @4086606 ,

Are you talking about the icon in the editor (which you see in the gutter) or the one in the Side Bar (Treeview)? VS Code only supports `codicon` in the Side Bar, not the Editor

BTW, I guess it is the Side Bar, right? 😄

**Comment by alefragnani** [comment]
You _"could"_ replace the icon in editor gutter up until the latest VS Code release, using the `bookmarks.gutterIconPath` setting. But in the latest release, VS Code is blocking extensions from loading resources _outside_ its sandbox, which is part of their _sandboxing_ effort (tracked in #411).

I'm still not sure I'll create a workaround for this, or simply remove the setting 😞

**Comment by 4086606** [comment]
Are you open to changing the blue icon? Replacing it with the border icon in my screenshots?

If not can we have a light and dark `gutterIconPath` in your replacement?

**Comment by alefragnani** [comment]
Hi @4086606 ,

Thanks for your interest, but no, at the moment.

About the icon, if the `bookmarks.gutterIconPath` will be really blocked by VS Code API, I'll probably use something like I did on my other Numbered Bookmarks extension, where the user can decides the color of the icon and the SVG is created dynamically. Will see how it goes.

**Comment by 4086606** [comment]
Sounds good, in the meantime I can locally modify
