### ISSUE TITLE
[BUG] - I can't add more than 1 bookmark

### ISSUE THREAD

**Issue by yudazdk** [alefragnani/vscode-bookmarks#434]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @yudazdk , 

Couls you provide more details? 

Which kind of project/workspace have you opened (local/remote, multi-root, random files)
Any error/message displayed?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
