### ISSUE TITLE
[BUG] - can't run "npm i"

### ISSUE THREAD

**Issue by cognominal** [alefragnani/vscode-bookmarks#437]
can't run npm i. Apparently, some hardcoded path is specific to the
author

<img width="858" alt="Capture d’écran 2021-05-27 à 10 46 03" src="https://user-images.githubusercontent.com/16176/119796078-5816c500-bed9-11eb-9630-9ee5845a0e73.png">

<img width="298" alt="Capture d’écran 2021-05-27 à 10 52 56" src="https://user-images.githubusercontent.com/16176/119796786-f440cc00-bed9-11eb-9ecb-3173565c55bf.png">

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1. Run npm i in the terminal

**Comment by alefragnani** [comment]
Hi @cognominal ,

Not sure why this happened on `package-lock.json`, because that package is available on npm. 

The extension, on the other hand, is not totally open. There is a core package which is still closed, as described in #330 . No ETA to be reopened, yet.

Hope this helps
