### ISSUE TITLE
"Open a File First to toggle bookmarks"

### ISSUE THREAD

**Issue by GaryFurash** [alefragnani/vscode-bookmarks#44]
I have the latest version. When I try to toggle bookmarks i get the message "Open a File First to toggle bookmarks."

Windows 7, x64
Latest VS Code

**Comment by alefragnani** [comment]
Hi @GaryFurash ,

Are you loading *large files*, and by *large* I mean more than 5 Mb? If yes, you have the same problem as https://github.com/alefragnani/vscode-bookmarks/issues/31, which unfortunately, there is no fix available (for now).

Hope this helps

**Comment by alefragnani** [comment]
Hi @GaryFurash , 

Was this your scenario (_large files_)? If not, could you post any details how could I reproduce the issue?

Thanks in advance

**Comment by alefragnani** [comment]
I'm closing because didn't receive any info since report. Probably related to _big files_.

**Comment by GaryFurash** [comment]
Yes, sorry, this is probably because it's a large file.

**Comment by alefragnani** [comment]
Don´t worry 😄 

BTW, it seems the VSCode team is thinking about to [increate the limits](https://github.com/Microsoft/vscode/issues/6474#issuecomment-285010621). 

It's not on the roadmap yet, but they know this is an issue that needs to be addressed.

**Comment by rollsch** [comment]
Is there an update on this? I regularly work with large disassembled (1 million line) files of assembly code.
