### ISSUE TITLE
[BUG] - `bookmarks.toggle` causes exiting diff editor

### ISSUE THREAD

**Issue by wenfangdu** [alefragnani/vscode-bookmarks#440]
**Environment/version**

- Extension version: v13.0.4
- VSCode version: v1.56.2
- OS version: Windows 10

**Steps to reproduce**

![test](https://user-images.githubusercontent.com/28700378/121279591-63211a80-c907-11eb-9513-5940c6931dd8.gif)

**Comment by alefragnani** [comment]
Hi @wenfangdu ,

This happens because when you `toggle` the bookmark, the extension makes the document to enter the _edit mode_ (originally added in #30).

I'm not sure I'm able to detect if the editor is in _diff_ mode (probably is), so it would be ignored in this case.

Thanks for reporting
