### ISSUE TITLE
[BUG] - Toggled Bookmark first visible after edit

### ISSUE THREAD

**Issue by FilipRychnavsky** [alefragnani/vscode-bookmarks#441]
**Environment/version**

- Extension version:
- VSCode version: 1.56.2
- OS version:

**Steps to reproduce**

1. Write a line
2. Toggle a bookmark
3. Bookmark is not visible
4. Make an edit in the line
5. Bookmark ist visible, but not in the explorer
![toggle bookmark](https://user-images.githubusercontent.com/11429663/121314171-63211a80-c907-11eb-806e-12a71380cda5.jpg)

**Comment by alefragnani** [comment]
Hi @FilipRychnavsky ,

Could you please provide more details about the the file/workspace/folder you have opened? I mean, is it a _newly created_ file? Is the file located in the same Windows drive then the folder you have opened?

I'm wondering if you are having the same issue as #397 or #328.

Thank you

**Comment by FilipRychnavsky** [comment]
Hi @alefragnani ,
I have created a new workspace _scratch2.code-workspace_ and the problem has been gone.

the old erroneous workspace _scratch.code-workspace_ had following items:
* all files and folders had been on my C:\ drive 
`		{
			"name": "Filip @ 5a47fbe",
			"uri": "gitlens://5a47fbe/c:/Users/FRychnavsky/source/repos/Filip?{\"path\":\"/c:/Users/FRychnavsky/source/repos/Filip\",\"ref\":\"5a47fbe0506d2fa0c9a0051fc9425d2d73aed0c9\",\"repoPath\":\"c:/Users/FRychnavsky/source/repos/Filip\"}"		
		}
`
* I had received gitlense file system providers error message. I could not even save a new demo text file.

But everything works fine now.

Thanks for your extension. It helps me parse large code files.

Filip
