### ISSUE TITLE
Bookmarks are cleared after closing VS Code

### ISSUE THREAD

**Issue by dprietoc** [alefragnani/vscode-bookmarks#45]
Hi, @alefragnani 

I'm not really sure if it is a bug or maybe a feature, but once VS Code is closed I loose all of my bookmarks. It would really be nice to have them saved cross code's sessions.

Keeping this aside, I think this plug-in is a must and should be included in the core of the editor. Nice work!!! Thanks you.

**Comment by alefragnani** [comment]
Hi @dprietoc ,

First of all, thanks for your kindy words :+1: 

You must add this to your Settings: `"bookmarks.saveBookmarksBetweenSessions": true`. So, every bookmark will be remembered when you reopen VSCode.  You should take a look at `README.md`, for other useful settings, like `bookmarks.useStickyBookmarks`. Give it a try :smile: 

Hope this helps
