### ISSUE TITLE
[FEATURE] - Grouped bookmarks

### ISSUE THREAD

**Issue by rndware** [alefragnani/vscode-bookmarks#455]
As I user I would like to create custom groups for my bookmarks in the Side Bar.

I want to be able to add and remove bookmarks form these groups and give them a custom label e.g `feature/MP20/foo-feature`.

This would be very useful when working on multiple features at the same when they use different groupings of bookmarks.

**Comment by alefragnani** [comment]
Hi @rndware ,

This is already being tracked in #254. Feel free to upvote. I’m planning to start in the next weeks.

Stay tuned
