### ISSUE TITLE
[FEATURE] - Idea for a vs code extension

### ISSUE THREAD

**Issue by Nisthar** [alefragnani/vscode-bookmarks#459]
Hi, 

This is not related to the bookmarks features. But I have this new idea for a vs code extension.
It could be a lot helpful to a lot of developers i think. It should be easy to implement too.

its basically an extension that instead of commenting out codes in your project files.
you can just select the code that you want to comment and use the extension to remove the code and put like a pin (with label) in the sidebar where you can restore it later if you want.

This would minimizes a lot of unwanted codes and also you can review and restore codes later from the sidebar.

**Comment by alefragnani** [comment]
Hi @Nisthar ,

Do you mean something like the **Folding** feature in VS Code? It doesn't _hide_ the source code (the source code is still there), but simply collapses the lines in the editor where the Folding refers too. Depending on the language you use, it may be defined by _comment like_ syntaxes.

But, what do you mean about _new idea for a vs code extension_? Are you willing to develop and need some help/guidance, or do you need someone to do it?

Hope this helps

**Comment by Nisthar** [comment]
Hi @alefragnani 

Yeah its similar to code folding. But with the ability to completely remove the code and restore it whenever the author wants to from the sidebar. 

I think this is better than commenting out code which makes the code unreadable and hard to manage. I hope someone else who are passionate about the idea to work on it.

**Comment by fade2gray** [comment]
It sounds like you want something like a clipboard manager that can remember the file and exact location to restore the clip, regardless of any further changes you make to your code.

**Comment by alefragnani** [comment]
Thanks @fade2gray , I totally agree. A Clipboard Manager seems the perfect concept, because you want to _complete remove the code_, not _hide_, like folding.

A quick search at Marketplace (https://marketplace.visualstudio.com/search?term=clipboard&target=VSCode&category=All%20categories&sortBy=Relevance) reveals a few Clipboard related extensions. I suggest you to look at those to find out which one better works for you. Maybe it's already available.

Hope this helps

**Comment by alefragnani** [comment]
If you don't find any, maybe we could chat...
