### ISSUE TITLE
On "List from All Files" clicking outside of list closes active file

### ISSUE THREAD

**Issue by kenhowardpdx** [alefragnani/vscode-bookmarks#46]
When navigating the list by keyboard arrows each file is loaded in "preview" mode until the next bookmarked file is loaded (preview mode transfers to next file, previous file is pinned).

Clicking off the list (click into the file body) closes the preview (of currently selected bookmark in list) and returns the user to the last bookmark of the previous file pinned.

There are two issues really. 1) clicking in the document that is previewed closes the document, 2) previous documents get pinned causing a pile-up of documents to be opened.

**Comment by kenhowardpdx** [comment]
![vscode-bookmarks-bug](https://cloud.githubusercontent.com/assets/1892667/21578300/b7003cde-cf2f-11e6-8406-11656ec67c72.gif)

**Comment by alefragnani** [comment]
I think the problem is beacuse the _preview_ should not pin the files, only preview them. I don't remember an API for that but I'll take a look.

**Comment by kenhowardpdx** [comment]
I looked at how Visual Studio does it (without extensions) doesn't list all your bookmarks but navigates to next/previous. All files are open, not preview. I like that I can pick the bookmark... just wish it was possible to select it with keyboard.

**Comment by alefragnani** [comment]
>  just wish it was possible to select it with keyboard.
You can, if you use `RETURN` in the pick list

I found the reason, and it's not about _preview_, It only happens if you close _all files_ prior to using the command to list all bookmarks. Otherwise, it will keep _all files_ opened, no matter if you click outside the list, or hit `ESCAPE`.

Stay tuned for the fix.

**Comment by kenhowardpdx** [comment]
Interesting! I stepped through the code last week but never found the silver bullet. Good sleuthing.
