### ISSUE TITLE
[BUG] - Relabeling a bookmark from a remote SSH session fails

### ISSUE THREAD

**Issue by carlitorendon** [alefragnani/vscode-bookmarks#460]
Error running command _bookmarks.editLabel: Running the contributed command: '_bookmarks.editLabel' failed.. This is likely caused by the extension that contributes _bookmarks.editLabel.

**Environment/version**

- Extension version: v13.1.0
- VSCode version: 1.59.0
- OS version: Windows 10 20HH1

**Steps to reproduce**

1. Have a remote workspace with bookmarks being saved to the workspace (in the configuration)
2. From a remote workspace IDE session, create a bookmark (this is fine)
3. Try to re-label it, you get this error: 

`Error running command _bookmarks.editLabel: Running the contributed command: '_bookmarks.editLabel' failed.. This is likely caused by the extension that contributes _bookmarks.editLabel.`

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by carlitorendon** [comment]
Hello @alefragnani I also apologize for the late reply. Yeah I agree, let's close it for now and if this gain traction we can revisit. Thank you for this good plugin

**Comment by alefragnani** [comment]
That's ok, no need to apologize 🤝 

Thank you
