### ISSUE TITLE
[FEATURE] - New **Sticky engine**

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-bookmarks#463]
## New Sticky engine available

A new **Sticky engine** has been created, and will be available as the default engine starting in August 2021 release (v13.2.0).

### Fixes

The new engine should fix all current open issues:

* #116
* #168
* #446 
* #457 

### Improvements

The original engine had limitations on some areas. With the new engine, these areas are starting to be supported

* **Formatters:** It should work with formatters, like Prettier. Which means the `bookmarks.useWorkaroundForFormatters` setting (created for #118) could be turned off.
* **Multi-cursor:** On basic scenarios, multi-cursor edits are working just fine

### Know issues

There are a few scenarios that still needs fixes and improvements, so yes, this is not a flawless solution (and probably never will). 

As noted above, formatters and multi-cursors are finally being supported so, _real world_ testing could find issues. Dealing with _empty lines_ still has some corner cases, and I still have some work to do.

### How to Use

As noted, the new engine will be turned on by default, so you don’t have to do anything. 

But, if you use formatters and have `bookmarks.useWorkaroundForFormatters` turned on, I would ask you to turn if off, to validate the new engine with your formatter.

### How to Turn it Off

A new setting was created, so simply turn it off:

```json
    “bookmarks.experimental.enableNewStickyEngine”: false
````

You will return to the _legacy_ engine.

### How to Report Issues

Issues related to Sticky are really tricky. Not only to fix, but also to detect what happened. Try to detect/create a step by step instructions to reproduce the issue, and if possible, record a video/gif. Doing so, will be easier for me to reproduce the error.

### How to Report Success

Just comment/react here, so I will know if the effort of the new engine was worth it.

**Comment by Skura23** [comment]
Finally. 👍
PS: seems still not working with beautify, I uninstall it and use prettier now. This one seem works well with bookmark
