### ISSUE TITLE
[FEATURE] - Ability to delete all bookmarks

### ISSUE THREAD

**Issue by vlkv** [alefragnani/vscode-bookmarks#466]

**Comment by alefragnani** [comment]
Hi @vlkv ,

You already can do that, both for files or entire workspace. 

There are two different commands available: 

- `Bookmarks: Clear`
- `Bookmarks: Clear from All Files`.

Hope this helps

**Comment by petar-dochev-f3** [comment]
Still it would be nice to have a button or menu item. For example in the search pane there is a button _Clear Search Results_.

**Comment by alefragnani** [comment]
Hi @petar-dochev-f3 ,

The Side Bar has `Buttons` and a `Context Menu` items, to delete a single bookmark and all bookmarks from a file. 

If you still think the Side Bar should have a new Menu Item to delete all bookmarks from the workspace, please feel free to open a new issue.

Hope this helps
