### ISSUE TITLE
[BUG] - Expand/Collapse all button doesn't toggle

### ISSUE THREAD

**Issue by lukepighetti** [alefragnani/vscode-bookmarks#469]
On v13.2.1 the expand/collapse all button does not expand/collapse all

<img width="559" alt="Screen Shot 2021-09-16 at 12 58 30 PM" src="https://user-images.githubusercontent.com/666539/133654264-939a740a-9afd-457d-996b-a8be41df4829.png">

**Comment by alefragnani** [comment]
Hi @lukepighetti ,

Expanding is not supported yet. It's being tracked in #267. This button only supports _collapsing_ for now.

Hope this helps
