### ISSUE TITLE
Saving Bookmarks

### ISSUE THREAD

**Issue by Sarfarazsajjad** [alefragnani/vscode-bookmarks#47]
currently when I close the project and reopen it, bookmarks are gone. is this a bug or I have to save bookmarks somehow that I don't know about

**Comment by alefragnani** [comment]
Hi @Sarfarazsajjad ,

Just add `"bookmarks.saveBookmarksBetweenSessions": true` in your user settings. Take a look at `README.md` for more options :+1: 

Hope this helps
