### ISSUE TITLE
Question, add message to the bookmarks?

### ISSUE THREAD

**Issue by fenghse** [alefragnani/vscode-bookmarks#48]
Does it support to add a message for each bookmark?

**Comment by alefragnani** [comment]
Hi @fenghse ,

No, it doesn't. It only supports navigation to lines (columns in the future), and if you use the `List` commands, it shows a line preview to easy identification.

I remember seeing some other extension that appeared to do something related to that (add notes to line/columns) but I don't remember if it has navigation commands.

Hope this helps

**Comment by fenghse** [comment]
It will be good if we can add comments/annotation to the bookmarked line for code reading. Do you think is that easy to add this? BTW, can you recall the plugins with this function? Thanks a lot!

**Comment by alefragnani** [comment]
Hi @fenghse ,

Another issue was recently added and now is on the backlog (#76). I don't know yet if it would be added (and presented) in the bookmark itself, or using a bookmarks panel (like a treeview). Let´s see 😄
