### ISSUE TITLE
[BUG] - Bookmark immediately disappears after I format my code using Prettier

### ISSUE THREAD

**Issue by bassamanator** [alefragnani/vscode-bookmarks#486]
**Environment/version**

- Extension version: 13.2.2
- VSCode version: 1.62.2
- OS version: 
>Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-1-rt11-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Steps to reproduce**

1. Add a bookmark.
2. Format code using Prettier.

**Comment by alefragnani** [comment]
Hi @bassamanator ,

Could you provide more details about _what_ is not working, preferably providing step by step and/or a video displaying the issue, and Prettier and Bookmarks extension settings too?

I don't use Prettier that much, but just like other formatters, the extension were working just fine.

Thank you

**Comment by bassamanator** [comment]
Hi @alefragnani,

My code formatter, Prettier, formats the code on save. I'm new to VSCode, so it's possible that this bookmarks behaviour is normal. My previous bookmarks plugin in atom would not delete bookmarks when the code was formatted.

This is what happens:

1. I make a change to the code.
2. I add a bookmark.
3. The bookmark is added.
4. I hit save.
5. The code formats.
6. The bookmark disappears.

Here's a video:
https://user-images.githubusercontent.com/61985779/143672908-b2e3abf9-1c5d-4c24-85bc-9d24eb143ce6.mp4

Thanks!

**Comment by alefragnani** [comment]
Hi @bassamanator ,

In this case, the Bookmark is working as expected.

I mean, you added a bookmark to an _empty line_, and the formatter removed that line. So the bookmark is removed as well.

On the other hand, if you add a bookmark to a line _with content_, the bookmark move with that line.

Hope this helps
