### ISSUE TITLE
Enhancement: Click in gutter on Icon to toggle bookmark

### ISSUE THREAD

**Issue by edesilets** [alefragnani/vscode-bookmarks#49]
The thought is to be able to set/toggle a bookmark by clicking in the gutter. When you click in the gutter for a line you could keep clicking and it would cycle between the break point and a bookmark or none.

**Comment by edesilets** [comment]
Didn't see that [Issue 24](https://github.com/alefragnani/vscode-bookmarks/issues/24) addresses this.

**Comment by alefragnani** [comment]
No problem :+1: 
I'm still waiting for the dependent issue...
