### ISSUE TITLE
[BUG] - System degrades when defining Bookmarks

### ISSUE THREAD

**Issue by vklann** [alefragnani/vscode-bookmarks#491]
**Environment/version**
Windows 10 and 11

- Extension version: 13.2.2
- VSCode version: 1.62.3
- OS version: Windows 10 and 11
**Steps to reproduce**
1. Open VS code in a directory containing many files / sub directories (in my case: about 6300 files in 1700 directories)
2. Define some Bookmarks
3. Try to jump to next / previous Bookmark

Issues:
Bookmarks cannot be defined and jumed to reliably. Bookmark icons do not appear or appear with delay of several seconds. The system consumes all available computation power.

Workround:
	Install Bookmark version 12.1.4

**Comment by alefragnani** [comment]
Hi @vklann ,

I have projects with similar sizes (~40k files and ~12k folders) and didn't notice performance issues, neither with v12 nor  after upgrading to v13. No memory/CPU bumps that could be noticed as well.

The _bookmark icons not appearing_ has been reported in #450, but I didn't have success reproducing the error. I'm not sure this is a rendering issue (I remember seeing people complaining about icons in Terminal).

Unfortunately VS Code does not provide any profiling about running extensions, so the only way to find out performance issues would be adding _logs_.

Hope this helps

**Comment by alefragnani** [comment]
Even without a profiling/log, pleas provide details about memory/CPU usage (Task Manager prints/log), because maybe something could be shown by VS Code itself.

**Comment by vklann** [comment]
Hello @alefragnani, I also cannot reproduce the issue (under the conditions described in my initial post). This is strange. I suggest you close this issue.
