### ISSUE TITLE
[BUG] - Bookmarks - Explorer side window stuck on infinite loading

### ISSUE THREAD

**Issue by phillipvillaver** [alefragnani/vscode-bookmarks#496]
**Environment/version**

- Extension version: 13.2.2
- VSCode version: 1.62.3
- OS version: Windows 10 21H1 OS Build 19043.1348

**Steps to reproduce**

1. Click on the Bookmark on the side panel
2. Witness infinite loading
![image](https://user-images.githubusercontent.com/46913159/144946915-721b4cf1-42c1-4179-9c3c-632661f403cd.png)

**Comment by phillipvillaver** [comment]
I just figured out that I had a bookmark on one of my logfiles open also in VS Code (~16k lines). I just removed the bookmark there and everything works snappy again.

**Comment by alefragnani** [comment]
Thanks for clarifying. I'm glad to know you could manage to find the reason.

I'll record that, in case someone else faces the same issue.
