### ISSUE TITLE
[FEATURE] - Add setting to choose viewport position on navigation

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [alefragnani/vscode-bookmarks#504]
Is it possible to add option to set position appear bookmark line (top / center / maybe bottom)?

Line with bookmark goes to middle of the screen after click on bookmark in navigate panel.
This is not a behavior that expect after navigate. I should to scroll every time I click on bookmark.

**Comment by alefragnani** [comment]
Hi @AmelianceSkyMusic ,

A similar request was made in the end of 2020 (#361), but ended up being closed because the user didn’t answer my question.

To summarize, VS Code provides the possibility to move to `Top` or `Center` only, but not `Bottom`. Today it moves to `Center` _if the current position is not visible_, otherwise it doesn’t do any scroll and only moves the cursor.

It works this way for both scenarios, using the Side Bar and the Command Palette.

Hope this helps

**Comment by AmelianceSkyMusic** [comment]
I think the bottom is not my case, but in my opinion, the bookmark top position only is the best design.
Is any option to set behavior like that?

18 January 2022, 18:45:05, by "Alessandro Fragnani" ***@***.***>:


Hi @AmelianceSkyMusic ,
A similar request was made in the end of 2020 (#361), but ended up being closed because the user didn’t answer my question.
To summarize, VS Code provides the possibility to move to Top or Center only, but not Bottom. Today it moves to Center if the current position is not visible, otherwise it doesn’t do any scroll and only moves the cursor.
It works this way for both scenarios, using the Side Bar and the Command Palette.
Hope this helps

**Comment by alefragnani** [comment]
No setting today, but VS Code provides API for that, so the extension could be updated to provide such setting in the future.

Just out of curiosity, which Editor/IDE do you use today, that has this top position design?

**Comment by AmelianceSkyMusic** [comment]
I use VSC only. It's just my thoughts.
I'm a UX/UI designer anyway. I am not always right, but I try to think how it should be better for use

18 January 2022, 18:54:54, by "Alessandro Fragnani" ***@***.***>:


No setting today, but VS Code provides API for that, so the extension could be updated to provide such setting in the future.
Just out of curiosity, which Editor/IDE do you use today, that has this top position design?

**Comment by AmelianceSkyMusic** [comment]
One good idea. I have tried another one plugin (no as good as your), and it has nice feature.
I think is good if we can see label inside code

18 January 2022, 18:54:54, by "Alessandro Fragnani" ***@***.***>:


No setting today, but VS Code provides API for that, so the extension could be updated to provide such setting in the future.
Just out of curiosity, which Editor/IDE do you use today, that has this top position design?

**Comment by gflujan** [comment]
Adding my vote/support for implementing this feature. I use vertical screens a lot and having the bookmark jump to the top would be great for being able to view more content below the mark. 

If it's also not too much trouble, another great addition to this idea could be to have two separate shortcuts/commands that do both. One jumps the mark to the middle, another jumps the mark to the top. 

But if this were to be just a dropdown setting, having the option to go top would be great. 

Thanks for all your hard work on this extension. I use it every day and it's an invaluable tool for my workflow.

**Comment by mark-hahn** [comment]
Can we add an option to set it X lines below the top?  Or just a fixed position of 4 lines from top?  I use top but it hides context.  It would be easy to implement.  Just scroll X lines after moving to top.  I have seen similar options in other operations in other UIs and it really works well.
