### ISSUE TITLE
bookmarks whether to accept PR？

### ISSUE THREAD

**Issue by yunying1** [alefragnani/vscode-bookmarks#510]
### Discussed in https://github.com/alefragnani/vscode-bookmarks/discussions/509

<div type='discussions-op-text'>

<sup>Originally posted by **yunying1** January 26, 2022</sup>
I hope show `Clear  From All Files` in side bar, I have some code give bookmarks, But i not have `bookmarks-core` so I can't test and i don't know bookmarks whether to accept PR, So i'll submit it first but it's up to you.
Thanks, Great job.

 [PR: https://github.com/alefragnani/vscode-bookmarks/pull/508](https://github.com/alefragnani/vscode-bookmarks/pull/508)</div>

**Comment by alefragnani** [comment]
As discussed in #509, a new issue to propose the new feature must be opened, and previously discussed.
