### ISSUE TITLE
[FEATURE] - Add an option to remove a bookmark from the bookmark list view

### ISSUE THREAD

**Issue by dipta10** [alefragnani/vscode-bookmarks#511]
If we need to remove a bookmark from the bookmark list view right now, we must first navigate to the bookmarked line. Then, for that line, toggle the bookmark status. We can currently delete all of the bookmarks from a file, however this is a bit inconvenient.

I might have 10 bookmarks in a file, but I just need to delete one from the list of bookmarks view.

![image](https://user-images.githubusercontent.com/20880432/151806010-a20f64c3-2fa3-45f9-8501-11144118b3eb.png)

Perhaps an option to delete the selected bookmark from the list by pressing Delete would be quite useful.

**Comment by alefragnani** [comment]
Hi @dipta10 ,

This is already being tracked in #498, which will use a _button_ at the right, in the Pick list.

BTW, If you use the Side Bar, you can already delete individual Bookmarks. You can use both, the Context Menu or the Inline button.

Hope this helps
