### ISSUE TITLE
Optionally turn Bookmarks into Sticky Notes

### ISSUE THREAD

**Issue by dseynhae** [alefragnani/vscode-bookmarks#513]
It would be nice to have similar functionality to [Sticky Notes](https://marketplace.visualstudio.com/items?itemName=PabloGaliano.StickyNotes-10958) from Microsoft Visual Studio.

👉 The current bookmark label would be the title of the sticky note, and then an extra field can capture a paragraph with reminders.

These reminders are more extensive than a simple label, helpful to the developer to update the code, without having to contaminate the code with "TODO Comments" (which we always forget to remove).

The sticky note can be simple ASCII text, with no need for fancy formatting or object insertion.

I have searched extensively, and to my surprise, there is no extension that already does this. It seems that the Bookmark extension, with its sticky engine, is in the ideal position to deliver this feature.

**Comment by alefragnani** [comment]
Hi @dseynhae ,

A similar request (with a bit more pieces) has been made a while ago #224. Some pieces were already released, like auto-labeling and others were not possible, like drag & drop. But this "additional details" is still on the backlog.

I wonder if a plain text content would be enough, or would end up requiring markdown support. 

I barely use **labels** on bookmarks, and I don't see myself using **comments/details** either, but that's just me. I see the value of such additional info for bookmarks 👍 .

Feel free upvote and add comments to #224. I'm starting to plan 2022 releases and this info will be important to decide the next releases.

Hope this helps
