### ISSUE TITLE
[BUG] - Side bar display nothing

### ISSUE THREAD

**Issue by farukonfly** [alefragnani/vscode-bookmarks#515]
**Environment/version**

- Extension version:
Name: Bookmarks
Id: alefragnani.Bookmarks
Description: Mark lines and jump to them
Version: 13.2.3
Publisher: Alessandro Fragnani
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

- VSCode version: 
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS version:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎2021/‎10/‎6
OS build	22000.527
Serial number	046865604353
Experience	Windows Feature Experience Pack 1000.22000.527.0

**Steps to reproduce**
The processing method of #280  has been referred to，but no effect
![image](https://user-images.githubusercontent.com/18646553/154445369-93c45410-181f-40e5-a0ec-6aeffe38735e.png)

**Comment by farukonfly** [comment]
> 

it does, it works，thanks a lot

**Comment by funduck** [comment]
Same thing here, 2 bugs:
* Ctrl+Alt+K adds a bookmark but it is displayed only after I switch to another tab and back
* Explorer is always empty

I tried to reinstall extension, restarted VSCode several times, called `Focus ..` as suggested, but nothing helpes
May be there are some logs from the extension, but I didn't find them in OUTPUT 
 
![image](https://user-images.githubusercontent.com/5364411/167295684-dbffe87d-1018-4216-a1e6-d7e2aefd5b38.png)
