### ISSUE TITLE
[FEATURE] - Display bookmarks for the currently active file only

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [alefragnani/vscode-bookmarks#517]
Display bookmarks for the currently active file only
Other bookmarks should not be displayed
Perhaps this is only for the list view

**Comment by alefragnani** [comment]
Hi @AmelianceSkyMusic ,

This is already being tracked in #238 . A new Bookmarks panel in the `Explorer` view, just like the `Outline` panel.

Hope this helps
