### ISSUE TITLE
[FEATURE] - Bookmarks: Toggle Labeled command should use labeded text as the default value

### ISSUE THREAD

**Issue by julee** [alefragnani/vscode-bookmarks#522]
When I  create a labeled bookmark with toggle labeled command, If this line is already created a labeld bookmark before. I expect the default text is the label of the current bookmark in the label input view. So I can modify the label according it.

However, it give me the text of the line currently, just the same with the situation this line has no labeled bookmark. It's sometimes troublesome to rename the label according the previous label. I mean when I kown one line have a bookmark, I use Toggle Labeled command is just because I want to known what the label of the bookmark, and may rename it accoding the label.

Expect this can be improve. Thank you.

**Comment by alefragnani** [comment]
Hi @julee ,

I suggest you to give a try the `bookmarks.label.suggestion` setting.

If I understand correctly, the `useWhenSelected` will probably work for you.

More information [in README](https://github.com/alefragnani/vscode-bookmarks#available-settings)

Hope this helps
