### ISSUE TITLE
[FEATURE] - Jump to next/previous on the same document 

### ISSUE THREAD

**Issue by epikgit** [alefragnani/vscode-bookmarks#532]
Indeed it's not the newest idea of the world, Visual Studio (the other one) has this feature since forever, but I think it would be very useful.
When you have a big source code file, the ideal use for the bookmarks is to jump from a point to another remaining on the same file. I know that I can use jump to next and then jump to previous but I like the option to continuosly cycle on the same document without the need to remember if I've alredy finished the bookmarks on the page.

**Comment by alefragnani** [comment]
Hi @epikgit ,

If you prefer navigation to remain in the same file, simply change the setting `bookmarks.navigateThroughAllFiles` to `false`.

You can also combine with `bookmarks.wrapNavigation`, to choose if it would stop at the beginning/end of the file, or cycle over and over.

Hope this helps
