### ISSUE TITLE
[FEATURE] - sort bookmarks alphabetically (by label)

### ISSUE THREAD

**Issue by Takakiriy** [alefragnani/vscode-bookmarks#534]
I want to reorder in side bar that is "View as List" mode.
It seems that we can't drag and drop in the side bar, so I will add numbers to the labels to organize them.
I usually not use "View as Tree" mode.

Organized list:
<img width="346" alt="スクリーンショット 2022-04-22 13 04 11" src="https://user-images.githubusercontent.com/51354765/164595759-efe17ba2-283e-491d-9331-4e0834ab23cc.png">

Not organized list:
<img width="340" alt="スクリーンショット 2022-04-22 12 56 34" src="https://user-images.githubusercontent.com/51354765/164593354-f7f472dc-812b-426b-9d0e-52cd90c016c8.png">

Related issue:
- https://github.com/alefragnani/vscode-bookmarks/issues/378
- https://github.com/alefragnani/vscode-bookmarks/issues/435

**Comment by alefragnani** [comment]
Hi @Takakiriy ,

Drag & drop, when available, won’t be designed for this scenario. Instead, the best match for your scenario is indeed, #435, as you related.

Closing as duplicate

Hope this helps
