### ISSUE TITLE
[FEATURE] - Add option to cycle through bookmarks inside the file you are currently in.

### ISSUE THREAD

**Issue by Zulupox** [alefragnani/vscode-bookmarks#535]
Many editors have the option "jump-to-next" bookmark either locally (within a file) or globally (within the project).
I usually prefer cycling between bookmarks in the current file I'm browsing. 
Would that be possible to add as an option?
Maybe either as a 2 new hot-keys for "jump-to-next-locally" / "jump-to-previous_locally" or a single on/off setting.

Cheers,
Joakim

**Comment by alefragnani** [comment]
Hi @Zulupox ,

There is already a setting for that. Just add it to your user settings

```json
 "bookmarks.navigateThroughAllFiles": false
```

Hope this helps

**Comment by Zulupox** [comment]
Oh! My bad thank you so  much!
