### ISSUE TITLE
[FEATURE] - Make suggestions for bookmarks

### ISSUE THREAD

**Issue by IceRevenge02** [alefragnani/vscode-bookmarks#539]
I have installed this extension for at least a year now and have not added one single bookmark. I installed it because I was sure that this could save me time and I am still very convinced that this is the case.
The reason I have not added any bookmarks is that I don't know which ones make sense. To help me with this decision nice would be either:
a)
an algorithm that detects which files were opened, searched for, etc. most often and adding these to a "most used code lines" section in the bookmarks extension. You can add actual bookmarks from this list.

Or b)
When searching for something actively show a notification (or an extra button for each search result) to add the search result as a bookmark (but in a way so that it isn't annoying).

What I hope this achieves is that I am either reminded while coding (more specifically probably while searching) that this would make sense as a bookmark or when I look at the extension some other time it tells me which files I searched for most often. While coding I don't think of bookmarks, when I am in the bookmarks extension I can't think of which files I used most often.

**Comment by alefragnani** [comment]
Hi @IceRevenge02 ,

The ideas you describe are interesting, but goes beyond the idea/concept of bookmark features I’ve seen in editors/IDEs throughout the years. To me, bookmarks are placed by users, on locations they choose.

What you describe is more like a _recent / most used_ approach, which in this case, can be automatically decided by user’s behavior.

I won’t change the extension to add this behavior, but I totally agree it could be a new extension. I dare to say some of these features are in fact, fairly easy to accomplish, like the most recent/used files. The most used code lines, on the other hand, I wonder what you call _most used code lines_ (focused, selected, changed, etc), but that’’s another question.

I suggest you to open this issue directly in VS Code repo. Maybe they are thinking to add such behavior themselves, or someone else share your ideas and could help help you with it.

Hope this helps
