### ISSUE TITLE
[FEATURE] - Numbered bookmarks + shortcuts

### ISSUE THREAD

**Issue by matt-winfield** [alefragnani/vscode-bookmarks#547]
I would like the ability to create a numbered bookmark using a keyboard shortcut such as `CTRL + SHIFT + (0-9)`, and navigate to those bookmarks using another shortcut such as `CTRL + (0-9)`.

This feature idea comes from IntelliJ Rider, and I use it quite a lot for quick navigation, it minimises the amount of typing required.

**Comment by alefragnani** [comment]
Hi @matt-winfield ,

For a numbered bookmarks feature, you should use my other [Numbered Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) extension

It is inspired on Delphi bookmarks, which was my main IDE/Language for a long time.

You can have both extensions installed, and use them on the same project at the same time. No conflicts.

Hope this helps
