### ISSUE TITLE
Warn: command 'bookmarks.toggle' not found

### ISSUE THREAD

**Issue by IgorLacik** [alefragnani/vscode-bookmarks#55]
I am suddenly encountering the following error:

command 'bookmarks.toggle' not found

Even though the bookmarks are installed and worked perfectly yesterday. Was there an update I did not notice?

Cheers.

IL

**Comment by IgorLacik** [comment]
After a 2nd VS Code restart it's working again - I suspect this was a VS Code, not yours. Closing the issue and thx for an excellent extension :)

**Comment by alefragnani** [comment]
Good to know its ok 😄

**Comment by IgorLacik** [comment]
Haha, it would definitely be a pain to debug :D

**Comment by timoreimann** [comment]
I started seeing this error consistently when trying to book-mark a line after a recent vscode update. Unfortunately, even a number of restarts didn't help. :(

At least for me, this is an ongoing issue. Can we reopen this issue, or shall I create a new one?

**Comment by alefragnani** [comment]
Hi @timoreimann ,

Which VSCode version are you using? I suggest you to _reinstall_ the extension if the error still occurs. 

I have seen similar erros when updating some extensions (not only mine), even after restarts, but only _fixed_ with one of these two steps:

* Close VS Code and then Reopen (not restart, but _really closing_)
* If the above don't work, uninstall the extension, Close VS Code, Reopen VS Code and then install the extension again.

I think the _error_ is related to VS Code keeping _both versions_ of the extension when you update them, until you _closes_ the app. If you only restart VS Code, both versions remains there, and probably something related to the _selection of the proper version_ may be failing.

Hope this helps

**Comment by timoreimann** [comment]
Hey @alefragnani,

thanks a ton -- closing VS Code alone didn't help, but fully uninstalling and reinstalling the extension did the trick! 👏 

All good again, I'm happy. 😃
