### ISSUE TITLE
[BUG] - Repeated gutter icon on line wrap

### ISSUE THREAD

**Issue by memeplex** [alefragnani/vscode-bookmarks#552]
This doesn't seem to be intended, at least I can't see the point of having that many bookmark icons in the gutter.

**Environment/version**

- Extension version: v13.3.1
- VSCode version: 1.70.2
- OS version: macOS Monterey

**Steps to reproduce**

1. Toggle line wrap on
2. Write a long line that wraps around
3. Bookmark it

<img width="825" alt="image" src="https://user-images.githubusercontent.com/2845433/185999846-5f126b89-e143-426c-9cdb-518f5c098f22.png">

**Comment by alefragnani** [comment]
Hi @memeplex ,

It's not intended, for sure, but it is how VS Code handles the drawing of icons in the gutter, when long lines wraps.

It was always this way, and I already saw a few extensions featuring the same behavior, so I never really bothered to find a solution/workaround, as I only see (myself) while editing markdown files, which I don't use Bookmarks that much. 

Anyway, I decided to take a look at their sample and noticed it didn't happened at first (weird ah)? But I could reproduce the exact same issue with a single line of code, in fact, a setting, and I'll open an issue in VS Code repo, looking for their solution/understanding to this behavior.

Thanks for reporting.

**Comment by alefragnani** [comment]
https://github.com/microsoft/vscode/issues/158837

**Comment by memeplex** [comment]
Cool, thanks!

**Comment by memeplex** [comment]
Thanks!
