### ISSUE TITLE
[FEATURE] - loop through bookmarks in the same file

### ISSUE THREAD

**Issue by sean1985zc** [alefragnani/vscode-bookmarks#556]
Could there be an option to loop through bookmarks in the same file, instead of jumping to other files, whenever I hit next or prev hotkeys?

**Comment by alefragnani** [comment]
Hi @sean1985zc ,

There is already a setting for that. Just add it to your user settings

```json
 "bookmarks.navigateThroughAllFiles": false
```

Hope this helps
