### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by bsevers** [alefragnani/vscode-bookmarks#557]
**Environment/version**
Windows 11, non-admin domain account.

- Extension version: 13.3.1
- VSCode Version: 
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

**Steps to reproduce**

1. Open Bookmarks side panel
2. Show that no bookmarks are displayed, looks to be "spinning".

![image](https://user-images.githubusercontent.com/32374434/192016782-76851ee1-0c9f-4816-83db-2b828f9deee5.png)

**Comment by bsevers** [comment]
I've also tried uninstalling the extension, reloading VSCode, and reinstalling it. If I run VSCode with admin privileges I cannot reproduce this issue.

**Comment by alefragnani** [comment]
Hi @bsevers ,

Being admin or not, should not make any difference for the extension, unless you had opened some folder/file that _non-admin users_ has no/limited access.

When you open the Side Bar, it will to load the bookmarks of that session (folder/workspace). And _if something goes wrong_, this spinning doesn't go away.

Please, right after opening VS Code, run the `Developer: Toggle Developer Tools` command and take a look at the `Console` tab. It could display some info about what the extension is doing, and which issue has happened.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
