### ISSUE TITLE
[FEATURE] - Support for generating bookmark dependency graph

### ISSUE THREAD

**Issue by bit-frozen** [alefragnani/vscode-bookmarks#561]
Is it possible to establish dependencies between bookmarks and then build graphs? 

Currently there seems to be only linear dependencies, and the hope is to achieve two-dimensional dependencies, that is, a bookmark can have multiple predecessors or multiple successors.

This will be useful for understanding more sophisticated code dependencies!

**Comment by alefragnani** [comment]
Hi @bit-frozen ,

Unfortunately no, this is not possible.

There is no connection/dependency between bookmarks. They are completely independent.

But, maybe the [CodeTour extension](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) would've a better alternative, as its gives you a steps approach between locations in your files.

Hope this helps
