### ISSUE TITLE
[FEATURE] - Bookmark Entire File

### ISSUE THREAD

**Issue by TheColorRed** [alefragnani/vscode-bookmarks#564]
I have a file that is in my `node_modules` (which has a bunch of css variables that I use to reference within my project), and I cannot seem find a way to added it to <kbd>Ctrl+P</kbd> which lists files. It would be nice if I could bookmark a file (One within my node_modules), and that file is accessible from the bookmarks sidebar and the "Go to File" command.

**Comment by alefragnani** [comment]
Hi @TheColorRed ,

I suppose you have a git repository and the `node_modules` folder is _grayed_ right? 

If that's the case, it is how VS Code works. It _disable_ the files/folders presented in `.gitignore`, so they won't be available in <kbd>Ctrl + P</kbd>. I'm not sure how to disable that, unfortunately.

The Bookmarks extension, on the other hand, won't block you from toggling bookmarks on any of those files. And if you do, the search/list will work as expected. So, the extension works just fine in that scenario.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
