### ISSUE TITLE
Sublime Keymap

### ISSUE THREAD

**Issue by outaTiME** [alefragnani/vscode-bookmarks#57]
Hi pal, 
awesome addon, it will great to have sublime keymap option, what do you think?

<img width="231" alt="screen shot 2017-03-13 at 8 24 46 pm" src="https://cloud.githubusercontent.com/assets/140472/23879331/23c21778-082b-11e7-8efb-c578fe83b3a5.png">

Thanks !!!

**Comment by alefragnani** [comment]
Thanks @outaTiME ,

Unfortunately, there is no way to define alternate keybindings in extensions, sorry...

However, you could create a new **Extension Pack** [(doc here)](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_extension-packs) containing **Sublime Text Keymap** and **Bookmarks**, and publish for others to use. I could help you if you want :+1:
