### ISSUE TITLE
[FEATURE] - Store line content along with line numbers when creating a bookmark.

### ISSUE THREAD

**Issue by azhar-path** [alefragnani/vscode-bookmarks#570]
Working in a large shared codebase, I like to bookmark certain points of interest in the code and revisit them later. The problem is the code can change since it is developed by many people, and now the bookmark points to a line number that no longer has the bookmarked line. I suggest storing the content of the line also in the bookmark so that even if the line number changes you can infer the new position of the code based on the content of the bookmark.

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question.

Thanks for your understanding
