### ISSUE TITLE
[BUG] - Bookmark marker interferes with debug breakpoints

### ISSUE THREAD

**Issue by umakantv** [alefragnani/vscode-bookmarks#573]
Bookmark marker beside the line number interferes with debug breakpoint

* Normal Usage of breakpoint  
<img width="627" alt="image" src="https://user-images.githubusercontent.com/41837826/207543413-5f39bb0a-770d-4490-9246-ed9331f84f24.png">

* Unable to add breakpoint if the bookmark is added
<img width="663" alt="image" src="https://user-images.githubusercontent.com/41837826/207542852-baa6a2bd-4060-41a2-a0ef-b50d05e6f90a.png">

* Unable to remove/edit breakpoint if the bookmark is added
<img width="605" alt="image" src="https://user-images.githubusercontent.com/41837826/207542446-52150c37-518d-49a5-9e14-7686509e239e.png">

**Environment/version**

- Extension version: v13.3.1
- VSCode version: 1.73.1
- OS version: MacOS 12.6

**Steps to reproduce**

1. Add a bookmark on a line
2. Try to add the breakpoint by clicking on the left of the line number
3. Remove bookmark to add the breakpoint
4. Add the breakpoint on the line
5. Try to remove/edit the breakpoint

**Comment by alefragnani** [comment]
Hi @umakantv ,

As @fade2gray commented above, this issue has already been reported. 

Unfortunately it depends on VS Code itself to fix the issue, as it fails to merge/combine decorations when presented in the same line as breakpoints.

Hope this helps

**Comment by umakantv** [comment]
Okay. I tried to search for issues with the keyword "breakpoint". Couldn't find one, that's why I created this.

Anyway, I hope it gets resolved soon.

Thanks
