### ISSUE TITLE
[FEATURE] - Toggle Label - Bookmark menu - autofill in select text to the input box

### ISSUE THREAD

**Issue by mishaxz** [alefragnani/vscode-bookmarks#579]
When you toggle a bookmark as a label, it would be great if it can automatically put the selected text in the input box as the suggestion for what to label it.

Often the bookmark window is not very wide but something important is on the line you want to bookmark but it won't be visible in the bookmark window because it is not wide enough, if you can select the text in the line that is important then sometimes this makes a very good bookmark label.

**Comment by alefragnani** [comment]
Hi @mishaxz ,

There is already a setting that you can play with `bookmarks.label.suggestion`. You should probably use `suggestWhenSelected` value.

It is documented in `README.md`

```
* Choose how labels are suggested when creating bookmarks (dontUse by default)

 * * `dontUse`: Don't use the selection (original behavior)
 * * `useWhenSelected`: Use the selected text (if available) directly, no confirmation required
 * * `suggestWhenSelected`: Suggests the selected text (if available). You still need to confirm.
 * * `suggestWhenSelectedOrLineWhenNoSelected`: Suggests the selected text (if available) or the entire line (when has no selection). You still need to confirm

```

Hope this helps
