### ISSUE TITLE
Bookmarks disappear

### ISSUE THREAD

**Issue by iskrenivanov** [alefragnani/vscode-bookmarks#58]
Last night I had a few bookmarks, but today after some crash message which I did not remember all bookmarks are missing.

**Comment by iskrenivanov** [comment]
oh, I have just remembered that after the crash message I  reloaded the program window. Now I have tried to close and then open the VS Code and my bookmarks are missing again, so the problem is that your extension does not save the bookmarks, they are saved only in runtime.

**Comment by alefragnani** [comment]
Hi @iskrenivanov ,

If you want bookmarks to be saved _between sessions_ you have to add `"bookmarks.saveBookmarksBetweenSessions": true` to your **User Settings**. 

Take a look at Readme page for more available settings.

Hope this helps.

**Comment by iskrenivanov** [comment]
Hi, thanks for the help, I think this option should be set up to true by
default.

2017-03-17 4:56 GMT+02:00 Alessandro Fragnani <notifications@github.com>:
