### ISSUE TITLE
[FEATURE] - Bookmarks sorting function

### ISSUE THREAD

**Issue by meijialun** [alefragnani/vscode-bookmarks#580]
In the bookmarks screen, the added bookmarks are sorted by the time they were added, and the user cannot adjust their order. I hope it is possible to adjust the order of a certain bookmark, otherwise it is rather messy when there are many bookmarks.

**Comment by alefragnani** [comment]
Hi @meijialun ,

There are 3 different issues requesting _sort of_ bookmark sorting (#217, #435 and #443). 

Feel free to upvote the one better suit your needs. I'm planning to add such features in upcoming releases.

Hope this helps
