### ISSUE TITLE
[FEATURE] - File&Directory Bookmarks

### ISSUE THREAD

**Issue by JonathanSoszka** [alefragnani/vscode-bookmarks#582]
Being able to bookmark an entire file or directory would be incredibly useful in some contexts.

**Example Use Case 1:**

Jonathan works at a company, which uses a large monorepo to organize their applications. Jonathan commits to this repo quite often but really only cares about a small subset of directories that his team is responsible for.

Jonathan would benefit from being able to bookmark the directories to his teams applications within the monorepo.

**Example Use Case 2:**

David is tasked with contributing to a large project that his team does not own, David digs into the system and identifies key modules that he will need to use within his work.

David would benefit from being able to bookmark these modules for later reference

** Possible User Experience **
* Right click file -> "Bookmark File"
* Right click directory -> "Bookmark Directory"

* Bookmarked directories & files are shown in a tree structure, if a bookmarked file falls under a bookmarked directory this should just be represented as a typical tree structure.

**Comment by alefragnani** [comment]
Hi @JonathanSoszka ,

The extension's idea is to mark _positions_ in files for easier navigation, not files or directories. Everything is designed for this purpose.

Doing a quick look in the marketplace, could find a few extensions that seems to do what you need. I would suggest you to give it a try:

* https://marketplace.visualstudio.com/items?itemName=UrosVujosevic.explorer-manager
* https://marketplace.visualstudio.com/items?itemName=FredJeck.fav
* https://marketplace.visualstudio.com/items?itemName=kdcro101.favorites

There is also the CodeTour extension, which has a different purpose (walkthroughs) but could be considered a mix between this and the other extensions.

Hope this helps
