### ISSUE TITLE
[BUG] - Bookmarks list is not working, bookmark in files are ok 

### ISSUE THREAD

**Issue by blagi** [alefragnani/vscode-bookmarks#583]
Bookmarks on the files are ok: I can see them, can toggle them and can go next and previous through them, but cannot see a bookmarks list when clicking on Bookmark icon in side bar. Just a BOOKMARKS: HELP AND FEEDBACK menu appears. Tried to reinstall extension, with no success. Bookmarks in files survived.
Commands 'Bookmarks: list' or 'Bookmarks: list from all files' are working but I'm not a fan of that interface.

**Environment/version**
Bookmark extension: v13.3.1
- Bookmarks Extension version:  v13.3.1
- VSCode version: 1.74.3
- OS version: Windows 10

**Steps to reproduce**

I cannot go back and solve a problem.  It's now a current state in my VS code. It appeared once, and I cannot get old Bookmarks way of working. It's same in the two workspaces I'm working on. 

![Screenshot 2023-01-24 134312](https://user-images.githubusercontent.com/1880252/214294717-060f9c8c-f614-4951-b22c-06e2780c5881.png)

**Comment by alefragnani** [comment]
Hi @blagi ,

For some reason, the `Explorer` view is _missing/hiden_, so I suggest you two alternatives:

* Use the `Bookmarks: Focus on Explorer View` command. It should make VS Code focus on Bookmarks view/panel, no matter where it is located. Maybe it is not where it should be.
* Use the `View: Reset View Locations` command. It will reset _all views_ and put them in the the original state.

Hope this helps

**Comment by blagi** [comment]
`Bookmarks: Focus on Explorer View` was missing. 
`View: Reset View Locations ` recovered a view and command `Bookmarks: Focus on Explorer View`.
Everything is ok now. 

Thanks!
