### ISSUE TITLE
[FEATURE] - Add manual grouping, drag and drop and coloring

### ISSUE THREAD

**Issue by manake** [alefragnani/vscode-bookmarks#594]
I have 20+ tabs open and I can't find the tab I need efficiently (it takes me 5-10 seconds to find the correct one).

Any chance that your extension could allow creating custom groups in the sidebar like Chrome does for tabs?

![unnamed](https://user-images.githubusercontent.com/6874031/222952348-eaf7b565-d1c3-4f16-8629-0762b0b8b038.jpg)

Such grouping is what would be really useful:

![TabGroups-Expand_Collapse](https://user-images.githubusercontent.com/6874031/222952422-69b17678-b0f7-4516-a0a4-8b169b2ee2c0.gif)

**Comment by alefragnani** [comment]
Hi @manake ,

Grouping and Colored bookmarks are already being tracked in (#225, #254 and #243). About drag and drop, there is a good possibility this to be part of the grouping, so I think this issue could be closed as _duplicate_ of the others I listed above.

Feel free to add comments and suggestions on those issues, in case you miss something on those topics.

Hope this helps
