### ISSUE TITLE
[BUG] - Expand selection to previous/next bookmark is not working anymore

### ISSUE THREAD

**Issue by dg00GT00** [alefragnani/vscode-bookmarks#598]
**Environment/version**

- Extension version: 13.3.1
- Version: 1.24.0
- OS: win32
- OS Release: 10.0.19045
- Product: Visual Studio Code
- Product Version: 1.76.2
- Language: en

**Steps to reproduce**
The correct behavior was working before but unfortunately I cannot recall the last version that it was happening.
1. Set a bookmark in the line of a document;
2. On the same document set another one either before or after the previous one.
3. Call the command "Expand selection to Next/Previous"

**Comment by alefragnani** [comment]
Hi @dg00GT00 ,

I couldn't reproduce the error. I followed the steps you provided, and the selection is being created correctly. I have tried a few different scenarios, with the cursor being placed before, after and between the bookmarks, and everything seems to be working as expected.

A _peculiar_ scenario (maybe the one you faced).

1. Toggle a bookmark on one place
2. Goes to another place (below)
3. Toggle a bookmark in this new place
4. _Then_, use the `Bookmarks (Selection): Expand Selection to Previous` command to select the range between both bookmarks
5. The selection will be created
6. _Now_, if you try to use the `Bookmarks (Selection): Expand Selection to Next`, expecting the selection to be _removed_, it won't be. You need to use the `Bookmarks (Selection): Shrink Selection` command instead

> The same happens if you use Up direction in selection/toggling

Hope this helps

**Comment by dg00GT00** [comment]
Hi @alefragnani,
I could not also reproduce the error anymore, in the next business day. Probably that was cause due some inconsistency on the VS Code side.

Thank you
