### ISSUE TITLE
[FEATURE] - A link to the marketplace would be useful for the Project (https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks)

### ISSUE THREAD

**Issue by schittli** [alefragnani/vscode-bookmarks#607]
Hello

**thanks a lot for sharing your great work!**

I have noted that the GitHub project has no link to the VS Code Marketplace:
https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

I think it would be useful for the project if someone drives by and is interested to see the marketplace 😃 

Thanks a lot, kind regards,
Thomas

**Comment by alefragnani** [comment]
Hi @schittli ,

It was added as project's website.

Thank you for you suggestion.
