### ISSUE TITLE
[FEATURE] - "View as tree": Please offer a button to open the complete tree

### ISSUE THREAD

**Issue by schittli** [alefragnani/vscode-bookmarks#608]
Hello

If one chooses "View as tree", then one normally has a screen with space for several dozen lines, but the tree view shows only one line per file and most of the screen space is usually unused.

One then has to additionally click a tree item to finally see the bookmarks.

It would be very useful if:
- if one could configure that "View as tree" is always shown expanded or collapsed.
- In general, it would be great to have two buttons in collapsible views: "Collapse all" and "Expand all".

Thanks a lot, kind regards,
Thomas

**Comment by alefragnani** [comment]
Hi @schittli ,

If you have enough space and would like the `Treeview` to be displayed expanded, you could simply update your user settings and add `"bookmarks.sideBar.expanded": true` to it. Doing so, when you switch from `View as List` to `View as Tree`, the `Treeview` will be always displayed expanded.

BTW, expanded trees are something that the VS Code API considers _expensive_, so the preference is to keep nodes collapsed, in most cases.

Hope this helps
