### ISSUE TITLE
Sidebar icon - show number of bookmarks

### ISSUE THREAD

**Issue by mlntr** [alefragnani/vscode-bookmarks#610]
Show how many bookmarks are in a project/page on the sidebar icon (so users don't need to open the sidebar to see). I believe this feature is now implemented in VS Code API.

![image](https://github.com/alefragnani/vscode-bookmarks/assets/17552475/683ca04f-26ba-45c4-ab20-47ca9f0275fa)

**Comment by alefragnani** [comment]
Hi @mlntr ,

This has been addressed in #153 , and should be available in the next release.

Hope this helps
