### ISSUE TITLE
[FEATURE] - Date Heatmap

### ISSUE THREAD

**Issue by SuzukaDev** [alefragnani/vscode-bookmarks#612]
I personally use a few bookmarks to jump between places I'm currently working (tend to have 3 to 5, maybe). And sometimes I wish to see at first glance which bookmark was the most recently added (its usually the bookmark I want to jump mostly, since tends to be the place Im currently working).

I just thought that would be cool feature that the bookmark icon colour could change depending on the time/date they were added.

I made a quick mockup:

![Mockup](https://i.imgur.com/PdS92J7.png)

(It could be replaced to other gradient color (maybe more noticeable). But that way, if I see a dark/bright one, I automatically can figure out when they were added.

This feature could be added as an option, not as default (I guess some other users use of bookmarks could be different than mine and they might want all bookmarks to look the same).

**Comment by alefragnani** [comment]
Hi @SuzukaDev ,

There is an open issue requesting for a **Stack** behavior #183 , but it will be limited to the _jumping_ commands, with no influence on the color of the icon/line decoration. Feel free to upvote if it fit your needs.

On the other hand, I remember an extension that does something similar to what you describe, that maybe would fit your scenario a bit more. It’s called **Footsteps**. https://marketplace.visualstudio.com/items?itemName=Wattenberger.footsteps . It has a gradient/heatmap display and also support jumping between locations. I guess it worth a try.

Hope this helps

**Comment by SuzukaDev** [comment]
@alefragnani Yes, jumping in date order is similar and would fit my needs :)
And thank you so much for suggesting me the extension! Is actually great, didn't know about it!
