### ISSUE TITLE
[FEATURE] - Add "Jump to label"

### ISSUE THREAD

**Issue by Straubm** [alefragnani/vscode-bookmarks#613]
Currently jumps can be to the next or previous bookmark. The feature request asks for a jump to a label, in the best case cross-file, but restricted to the current file would help as well.

Btw, good work, thanks. Will donate.

**Comment by alefragnani** [comment]
Hi @Straubm ,

I suppose you mean `Jump to Previous/Next Labeled Bookmark`, which should _ignore_ regular bookmarks, right? I don't use labeled bookmarks that much but it is a good idea.

About _restricted to current file_, this behavior already exists. Simply add the `bookmarks.navigateThroughAllFiles` setting to `true` and you are good to go.

Hope this helps

**Comment by Straubm** [comment]
Hi @alefragnani,

I meant Jump to Labeled Bookmark, not next/previous. Like bringing up a list of labaled bookmarks to choose from.
The list could by all labeled bookmarks or only the current file`s labeled bookmarks, but this feature is despensable.

**Comment by alefragnani** [comment]
Hi @Straubm ,

In this case, there is no need to create a new command. There are already two different commands to this: 

* `Bookmarks: List` List all bookmarks in the current file
* `Bookmarks: List from All Files` List all bookmarks from all files

The labeled bookmarks are displayed with an icon on its side, and you can filter them by the _label_.

Hope this help
