### ISSUE TITLE
[FEATURE] - Profiles

### ISSUE THREAD

**Issue by Jordan466** [alefragnani/vscode-bookmarks#619]
Enable users to group bookmarks into profiles. Users would be able to swap between profiles to load different bookmarks.

For example, suppose I'm working on feature A. I have a profile called Profile A that defines various bookmarks that are useful to me while working on that feature. 
I then decide I want to work on feature B. I switch to profile B, and all of my bookmarks are loaded up without needing to redefine them.

This could technically be achieved by saving bookmarks.json in source control and switching branches. But there's no solution for those who prefer to gitignore the bookmarks.json or save bookmarks in vscode

This feature request could also be a potential solution: #569

**Comment by alefragnani** [comment]
Hi @Jordan466 ,

The _profile_ behavior should be provided with the Tags feature described in https://github.com/alefragnani/vscode-bookmarks/issues/254#issuecomment-914523838. 

It was originally planned back then, but I had other priorities to deal with and it ended up freezed. I'm planning to go back to this in upcoming releases, and finally release it (if everything goes as expected 😁) .

Hope this helps
