### ISSUE TITLE
Sticky bookmark issue on working line (pressing return after indent doesn't move bookmark)

### ISSUE THREAD

**Issue by kercos** [alefragnani/vscode-bookmarks#62]
Hi, congrats for the library, and so nice to work with sticky bookmarks now 😄 

I've noticed a small glitch but not sure if intentional: if i set up a bookmark in the current working line and press return not from the beginning of the line (but for instance right after an indentation), the bookmark doesn't move to the following line.

**Comment by alefragnani** [comment]
Thanks @kercos ,

Yes, that's the expected behavior, because you are not in the beginning of the line. But I agree that  this case (indentations) is an exception, and would be better also move the bookmark. I'll take a look :+1:
