### ISSUE TITLE
[BUG] - Adding a bookmark, deleting it from the explorer menu and then right clicking where the bookmark was show "Remove Bookmark"

### ISSUE THREAD

**Issue by Gael-Lopes-Da-Silva** [alefragnani/vscode-bookmarks#627]
**Environment/version**

- Extension version: 13.4.1
- VSCode version: 1.80.0
- OS version: windows 11 22H2

**Steps to reproduce**

1. Adding a new bookmark anywhere in a file
2. Deleting it from the explorer Bookmark menu
3. Right click where the bookmark was

It seems to be a minor issue, but it's a good first issue for those who want to start investing their self in this project.

**Comment by alefragnani** [comment]
Hi @Gael-Lopes-Da-Silva ,

Good catch! I could reproduce the error. It should be fixed in the next release.

Thanks for reporting.
