### ISSUE TITLE
Pipe broken on French Keyboard with new Keymap

### ISSUE THREAD

**Issue by DavidBabel** [alefragnani/vscode-bookmarks#63]
Hey hello, this rule of keybinding :
```json
{
  "key": "shift+alt+l",
  "command": "bookmarks.expandSelectionToNext",
  "when": "editorTextFocus"
}
```

Broke the way to do the pipe character "|" on french keyboard.

Juste a warning, add this to your keybindings.json to solve the problem
```json
{
  "key": "shift+alt+l",
  "command": "-bookmarks.expandSelectionToNext",
  "when": "editorTextFocus"
}
```

**Comment by alefragnani** [comment]
Hi @DavidBabel ,

Thanks for reporting. Did it happened after VS Code update 1.11, or was happening before. I'm asking because I noticed some keybindings changes in  this new release.

Unfortunately there is no way to define different keybinding for different layouts/languages :disappointed: .

**Comment by DavidBabel** [comment]
Yes you are right, it's a new issue due to this update.
Broke most of french keybinding by the way.

**Comment by EmmanuelBeziat** [comment]
Same problem for me. Check here https://github.com/Microsoft/vscode/issues/24084

**Comment by alefragnani** [comment]
I had noted that a new VSCode release (1.11.1) has created a setting to _return to previous behavior_ for keybindings (`"keyboard.dispatch": "keyCode"`). 

Could you check if does it work?

**Comment by alefragnani** [comment]
Did you try to use `"keyboard.dispatch": "keyCode"` as suggested? Did it fix the problem?
