### ISSUE TITLE
[FEATURE] - Add option to disable "what's new" window

### ISSUE THREAD

**Issue by unikitty37** [alefragnani/vscode-bookmarks#632]
When Bookmarks is updated, it opens a "what's new" window.

This is distracting and disruptive to me when one extension does it — it will make VSCode unusable if multiple extensions start doing it, as I will never be able to keep track of what I'm actually doing because of the spam of update windows.

Please could you add an option so that we can disable this? (Ideally, prompt for the user's preference on first run, rather than just assuming everybody wants it…)

Thanks!

**Comment by waynebloss** [comment]
@unikitty37 This is probably not going to happen. The creator here *needs* everybody to know about every new release for reasons unknown, as detailed in the comments on this other issue - https://github.com/alefragnani/vscode-bookmarks/issues/175

One workaround is to install an old version which causes VS Code to stop updating the extension.

Perhaps someone will fork this repo and release a copy that doesn't show a welcome screen.

**Comment by unikitty37** [comment]
Not sure how I managed to miss that there was already an issue open for this! I'll close this and watch that one instead. Thanks!
