### ISSUE TITLE
[FEATURE] - Bookmark groups

### ISSUE THREAD

**Issue by eldiegocvl** [alefragnani/vscode-bookmarks#636]
Hi great extension!

Would be ideal to be able to group bookmarks with custom names, so in big code bases you can have multiple categories at will (intercom, APIs, codesmells, core, frontend, etc). And be able to see the list by groups instead of by filename as we have right now. 

The view by filename becomes cumbersome once you start having a lot of bookmars.

**Comment by alefragnani** [comment]
Hi @eldiegocvl ,

This is already being tracked in #254, and will be called **Tags**. More detailed at https://github.com/alefragnani/vscode-bookmarks/issues/254#issuecomment-914523838. With that, you will be able to apply a Tag to bookmarks and switch/activate sets whenever necessary.

Hope this helps
