### ISSUE TITLE
[FEATURE] - Help tracking linenumber changes after pulling new code

### ISSUE THREAD

**Issue by eldiegocvl** [alefragnani/vscode-bookmarks#637]
Hi great extension!

After you pull new code changes from colleagues most often the bookmarked linenumber is out of place since the code moved up/down a few lines when new code was added.

The bookmarks remain always in the same line and after a while they are no longer relevant since they are out of place.

Solution:
- I suggest storing the entire line of code as part of the bookmark (not as label but a value that is kept after user customizes the label).
- The extension marks with a color if the bookmark-stored-line is not matching what's currently in the file.
- The bookmark offers searching for the bookmark-stored-line withing that file with a simple click and if found ask confirmation to update/fix the bookmark.

Let me know your thoughts!

**Comment by alefragnani** [comment]
Hi @eldiegocvl ,

The extension doesn’t support/monitor external file changes, but edits made inside VS Code so, whenever you open a file, the bookmarks are restored to the previous location (line x column) where it was added inside VS Code.

#177 asks something similar to it, even tho I’m inclined not to do anything VCS related but instead, a regular file/content approach.

In the meantime, if you share your project with a team, and they also use VS Code, I would suggest you to try out `bookmarks.saveBookmarksInProject` setting. It will save the bookmarks within the project (in `.vscode/bookmarks.json` file) allowing you to add it to your repo and be automatically updated whenever your colleagues make changes

Hope this helps
