### ISSUE TITLE
[BUG] - Bookmark context menu in gutter is incorrect when removing bookmark from side bar

### ISSUE THREAD

**Issue by jakeparis** [alefragnani/vscode-bookmarks#639]
When you have a bookmark, you can right-click the icon in the gutter, and the context menu says "remove bookmark". If you remove the bookmark from there, the context menu in that location reverts to "add bookmark". However, if you delete the bookmark by clicking the "x" in the sidebar next to the bookmark, the gutter icon disappears, but the right-click menu does *not* revert to "add bookmark". Instead it continues to say "remove bookmark" 

**Environment/version**

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1. Create a bookmark
2. Use the "x" button in the side bar to delete the bookmark
3. right click that same line in the gutter
4. Instead of "add bookmark", the "remove bookmark" menu still shows

![2023-08-16_12-34-35 (1)](https://github.com/alefragnani/vscode-bookmarks/assets/7408985/f223ea7e-b94c-45ce-ace2-f763cdac6869)

**Comment by alefragnani** [comment]
Hi @jakeparis ,

This has already been reported in #627, and should be available in the next update later this week.

Hope this helps
