### ISSUE TITLE
Bookmarks TreeView

### ISSUE THREAD

**Issue by kms-ky-truong** [alefragnani/vscode-bookmarks#64]
Hi @alefragnani ,

It would be great if we can remove one bookmark from the list, similar to WebStorm.

Regards,
Ky

**Comment by alefragnani** [comment]
Hi @kms-ky-truong ,

I don't know WebStorm, but what I could find in printscreens is a _Bookmarks Panel_. To do something like that, it would be necessary to have [this feature](https://github.com/microsoft/vscode/issues/15485) available.

Thanks for your suggestion
