### ISSUE TITLE
[BUG] - Command `workbench.view.extension.bookmarks`

### ISSUE THREAD

**Issue by CAESIUS-TIM** [alefragnani/vscode-bookmarks#641]
![image](https://github.com/alefragnani/vscode-bookmarks/assets/60285058/c4719641-8e64-42df-b269-8e55682748a4)

Should open and focus bookmarks in the sidebar, but open the explorer and remain the focus in the editor.
Key bindings do not conflict.

**Environment/version**

- Extension version: v13.4.1
- VSCode version: 1.81.1
- OS version: Windows 10 Version 22H2 19045.3324 PF20FSKQ Windows Feature Experience Pack 1000.19041.1000.0

**Steps to reproduce**

1. bind key for `View: Show Bookmarks (workbench.view.extension.bookmarks)`
2. use the binding

**Comment by CAESIUS-TIM** [comment]
![image](https://github.com/alefragnani/vscode-bookmarks/assets/60285058/c6ba76d2-24c5-4f87-84d1-6394b65672a8)

`View: Show Bookmarks` isn't in commands picker. Maybe `workbench.view.extension.bookmarks` is a command belongs to the explorer of vscode itself, and the extension bookmarks has no the feature.

**Comment by CAESIUS-TIM** [comment]
https://github.com/alefragnani/vscode-bookmarks/blob/fbc289be97ca4d376a8c1d599c93b9d6b024f137/README.md?plain=1#L54-L67

Maybe it should be a feature request issue rather that a bug issue.

**Comment by CAESIUS-TIM** [comment]
`bookmarksExplorer.focus`

**Comment by ckx** [comment]
I'm also experiencing this issue on 1.85.1, Fedora 38.

This is a shot in the dark but I noticed in this repo's README the Bookmarks side bar looks like this, which I assume is macOS:

![image](https://github.com/alefragnani/vscode-bookmarks/assets/1069665/753ff28d-9264-426e-beeb-3302a17d1b84)

For me it's formatted this way:

![image](https://github.com/alefragnani/vscode-bookmarks/assets/1069665/580ba551-db1c-42d2-ac40-2f21e523f6fe)

This is a fairly weak assumption, but maybe the fact that on our operating systems, the side bar title having `EXPLORER` in it is the reason @CAESIUS-TIM and I keep having the VS code explorer open? I don't have a vscode development environment setup atm so I can't test, but if @alefragnani has time to do a simple string search/replace of "explorer" and send me over a vsix I can test the theory.

**Comment by ckx** [comment]
Fixed in latest insiders https://github.com/microsoft/vscode/issues/200889.
