### ISSUE TITLE
[BUG] - The label for the bookmark is not displayed.

### ISSUE THREAD

**Issue by mariogogo123** [alefragnani/vscode-bookmarks#646]
**Environment/version**

- Extension version:Bookmarks v13.4.1
- VSCode version: 1.82.0
- OS version:windows 10 ro

**Steps to reproduce**

after set bookmark
No bookmarks yet.
In order to use bookmrks,place the cursor in any location in the file and run the command:

my environbment is SSH connectoin to server

**Comment by mariogogo123** [comment]
![bb](https://github.com/alefragnani/vscode-bookmarks/assets/139105932/1d8011c5-4682-475d-9967-01c9b4e502d3)
I have set bookmarks, but they are not displayed in the tabs.

**Comment by alefragnani** [comment]
Hi @mariogogo123 ,

It seems you are dealing with the same issue as #630, as you already commented there. 

Hope this helps

**Comment by mariogogo123** [comment]
hello ok.
i think this plugin is very good.
