### ISSUE TITLE
[FEATURE] - Allow the option to see the file path only or put the icon of the file

### ISSUE THREAD

**Issue by TheElegantCoding** [alefragnani/vscode-bookmarks#659]
Current menu
![image](https://github.com/alefragnani/vscode-bookmarks/assets/70770072/95e3862e-8e83-41d5-a8be-697509fad1b8)

Icons in menu like this

![image](https://github.com/alefragnani/vscode-bookmarks/assets/70770072/d1c18307-b02e-4b95-bf0d-906c7b02e41a)

**Comment by alefragnani** [comment]
Hi @TheElegantCoding ,

This is an interesting feature, but unfortunatelly, this is not currently possible, as there is no API to allow extensions to use file icon themes. There is an open request in the VS Code repo (https://github.com/microsoft/vscode/issues/59826), but no ETA.

I'm subcribed to that issue, so any news, I'll be notified. In the meantime, I'm closing this issue.

Thanks for your undestanding.
