### ISSUE TITLE
Make path of bookmarks.json crossplatform

### ISSUE THREAD

**Issue by fzzr-** [alefragnani/vscode-bookmarks#66]
Currently the path of file looks like "for win only".

`.vscode\\bookmarks.json`

but should be

`.vscode\/bookmarks.json`

![vsc bookmarks fpath issue mov](https://cloud.githubusercontent.com/assets/888526/24972679/e9475d9a-1fc4-11e7-8424-105cca42c76e.gif)

**Comment by alefragnani** [comment]
Duplicate of #65
