### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by mjoe67886** [alefragnani/vscode-bookmarks#663]
**Environment/version**
python 3.12
- Extension version: 13.4.2
- VSCode version: 1.84.2
- OS version: Windows 11

**Steps to reproduce**

1.  No real steps i'm just constantly setting bookmarks and coming back the next day or even later in the day and they're just gone you know I love this ext so much but you know if there's any way to fix that I'd appreciate that
2.

**Comment by mjoe67886** [comment]
I just gave up and installed the other extension what you should do is just throw this into GPT and have it analyze it it has it could analyze large data sets now so you know it could get you set up in like no no time at all who's telling how good it is now that it can analyze large data sets.... GPT 4 only though don't try to do this on GPT 3.5

**Comment by alefragnani** [comment]
Hi @mjoe67886 ,

Sorry to hear that it wasn't working properly and you had to install other extension. But, if the other extension works for your scenarios, that´s ok. 

Thank you

**Comment by mjoe67886** [comment]
Hey wait a minute I am so sorry it turns out as is my normal design for keyboard shortcuts to when I install an extension to find the most interesting ones and organize them on my keyboard it so turns out that I left your default settings for control j control K and control L but I must have also thought that bookmark clear seemed like an interesting keyboard shortcut so obviously I made that be control : I really apologize that's obviously what has been happening you've made like the best extension in the world and I've been deleting and clearing all my bookmarks myself so just realize that this is a error on my part as this is closed i'm not sure you're gonna get this message so if I don't hear back by tomorrow i'll send it again so you don't go thinking that your extension was messed up when it was my fault...

**Comment by alefragnani** [comment]
Hi @mjoe67886 ,

That's great to hear it was just a keyboard shortcut issue, not only because you could detect and fix it, but it also means the extension itself has no issue to worry about 😬 .

Keep enjoying the extension

**Comment by mjoe67886** [comment]
I'm sorry I spoke too soon actually I thought it was that you know
logically it seemed like that's what I must have done but you know I closed
and reopened Visual Studio code maybe or It was something else...but today
you know after verifying my keyboard shortcuts you know this happened again
does it ever happen to you... I came up with a clever workaround I just
started putting you know text comment tags like three letters that identify
the function I'm working on and then you know so if it does happen I could
just go to the tag and then read out a bookmark it's still way better than
scrolling a file you know but I'd like to see if can fix

**Comment by mjoe67886** [comment]
So whatever you need to know just let me know if you could give me like an
itemized list and tomorrow when I'm not busy i'll just go ahead and workout
a scenario I could send screen recordings whatever..

**Comment by mjoe67886** [comment]
Thank you for your understanding.
