### ISSUE TITLE
[BUG] - extension removes ability to Ctrl+click to navigate to a function

### ISSUE THREAD

**Issue by thready** [alefragnani/vscode-bookmarks#664]
The extension, when enabled, prevents Ctrl+click to work when you want to navigate to a function definition.

**Environment/version**
python language mode

- Extension version: alefragnani.bookmarks v13.4.2

- VSCode version: 1.84.0
- OS version: ubuntu 22.04

**Steps to reproduce**

1. Ctrl + click on a fn name.
2. When extension is enabled, this doesn't work.

**Comment by thready** [comment]
It's working now.  Not sure what happened.  But it was reproducible more than once, but now it works. Bizarre. Maybe it's intermittent. Closing until I can reproduce.

**Comment by alefragnani** [comment]
Hi @thready ,

Not sure what has happened, but the extension shouldn't affect code navigation as you reported. It does not handle/intercept any _ctrl + click_ event anywhere in the source code, nor the icon and/or line background you can customize, should interact with it. Really weird.

Anyway, it is working now so, good to know.

Hope this helps
