### ISSUE TITLE
[BUG] - The previous bookmark will be deleted after the cell runs in vscode

### ISSUE THREAD

**Issue by Malibu351** [alefragnani/vscode-bookmarks#667]
VScode Version: 1.84.2

If a cell changes from In[1] to In[2] after running, all the bookmarks at the beginning are deleted. I hope the bookmarks can be retained after running. This should be marked in the cell's source as bookmarks, but after running, the same cell will display a new source. Is there a solution to this?

1: I have two cells, and the first one has written some code

![image](https://github.com/alefragnani/vscode-bookmarks/assets/57163565/31b56ae5-d859-43e8-8216-79050a70a22e)

2: Run first cell
![image](https://github.com/alefragnani/vscode-bookmarks/assets/57163565/6b5919ed-172f-41dd-afa3-80255d5640ab)

3: Place the cursor in the second cell
![image](https://github.com/alefragnani/vscode-bookmarks/assets/57163565/6932af65-7386-4863-9739-3f905830325c)

4: Return the cursor to the first cell and you can see that the bookmark has disappeared
![image](https://github.com/alefragnani/vscode-bookmarks/assets/57163565/8dca6b17-0b78-4e9b-81a0-3d88bd4cd338)

Here is the complete situation：
![test](https://github.com/alefragnani/vscode-bookmarks/assets/57163565/ceae0e97-1f8f-4903-ac1b-51c283b2df69)

**Comment by alefragnani** [comment]
Hi @Malibu351 ,

I'm sorry to say, but the extension still doesn't support Notebooks. 

There is already an open issue requesting this in #531 , and I'm planning to take a look at this in the near future. I don't use Notebooks that much and the API to deal with text and positions is a bit different, compared to regular documents, so it will require a bit of work to support it.

Feel free to upvote and add comments on that issue.

Hope this helps
