### ISSUE TITLE
[BUG] - Explorer view doesn't work

### ISSUE THREAD

**Issue by gmccullo** [alefragnani/vscode-bookmarks#672]
It's been a long time since I've seen the Bookmarks explorer work. It shows a count on the icon, but the explorer is empty except for the progress indicator which never stops.

**Environment/version**

- Extension version: 13.4.2
- VSCode version: 1.84.2
- OS version: win11

**Steps to reproduce**

1. add bookmarks
2. look at bookmarks explorer

**Comment by alefragnani** [comment]
Hi @gmccullo ,

You are probably facing the same issue as #630 , as the badge currently displays the number of registered bookmarks, but should display the number of _valid_ bookmarks. 

Another issue is related to some untitled files or files outside of the current worspace like #328 and #397, which I'm planning to handle together.

I'm closing this issue as duplicate of those. 

Hope this helps
