### ISSUE TITLE
[FEATURE] - More Accurate Names for Secondary Sidebar Context Menu

### ISSUE THREAD

**Issue by imperialmarch55** [alefragnani/vscode-bookmarks#674]
In the secondary sidebar in VS code the options for showing bookmarks appear as "Explorer" and "Help and Feedback". Neither of these names indicate they have anything to do with the bookmarks extension, and in fact sound very far from being part of the bookmarks extension. 

This caused a lot of confusion, and I thought something was wrong with my bookmarks extension installation or something. Please update the names to reflect what's actually going on.

**Comment by alefragnani** [comment]
Hi @imperialmarch55 ,

As you may notice, the Secondary Side Bar only displays the _icon_ of the extension's Activity Bar, no matter if it is from a built in Activity Bar, or from an extension. And unfortunately, it does not provide any setting to display the _name_ as well. 

The same limitation occurs on extension development, and there is no way to define an alternate name, based on which Side Bar the extension is docked.

Thanks for your understanding.

**Comment by imperialmarch55** [comment]
It looks like we're not talking about the same thing. In the attached screenshot, you can see that there are some very specific names in the context menu for different extensions. For example, you can see that "TODOs" in the context menu corresponds to "TODOS: Tree" in the Secondary Sidebar. There are also very specific names like "GitKraken Account" and "GitKraken Workspaces". 

In contrast the Bookmarks extension has "Explorer" corresponding to "BOOKMARKS: EXPLORER", and a similar thing is done with "Help and Feedback" for this extension. Updating these context menu names to be more explicit, for example just including the word "Bookmarks" in it, would help avoid needless confusion.

I apologize for the lack of clarification by not including a screenshot in my original message.

![sidebar_context_menu](https://github.com/alefragnani/vscode-bookmarks/assets/13725330/e2987559-67bb-4c1f-9422-b258bdd98f22)
