### ISSUE TITLE
[BUG] - Commands aren't found, Extension stuck "activating".

### ISSUE THREAD

**Issue by divinebeam** [alefragnani/vscode-bookmarks#687]
**Environment/version**

- Extension version: 13.4.2
- VSCode version: 1.85.1
- OS version:  Windows_NT x64 10.0.19045

**Steps to reproduce**

Install Bookmarks extension, CTRL + ALT + K to attempt to toggle a bookmark - error occurs saying the command was not found. OR "cannot read properties of undefined (reading activeFile)". 

Things I've tried: reinstalling the extension, disabling - re-enabling the extension, invoking the command with CTRL Shift P. 

https://puu.sh/JYxWL/09e5981198.png

**Comment by alefragnani** [comment]
Hi @divinebeam ,

Could you provide more details about the file and _folder/workspace_ you have opened? Is it a local folder, is the file from within the folder? Are you opening a single file with no active folder/workspace selected?

Thanks in advance

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
