### ISSUE TITLE
The `List from All Files` command doesn't work well with VSCode 1.12.1

### ISSUE THREAD

**Issue by cateyes99** [alefragnani/vscode-bookmarks#69]
>Bookmarks Version: 0.14.1
>VSCode Version: 1.12.1
>OS Version: OS X EI Capitan 10.11.3

1. Set up a bookmark in file `A.cs`, set up another one in `B.cs`
2. Now open `C.cs` which doesn't have any bookmarks in it and stay on this file
3. Run the command `List from All Files` in the command bar on the top of the editor window
4. Observed the behaviour is weird, it seemed like just freshing the current editor of `C.cs` in a flash and does nothing else, didn't show the drop list of all bookmarks.

**NOTE**: if staying on the editor of a file which has at least one bookmark and run this command, then it does show the drop list of all bookmarks.

**Comment by cateyes99** [comment]
i remember before I upgraded VSCode to 1.12.1 from 1.10.2, Bookmarks 0.14.1 worked fine in this case:
>Bookmarks Version: 0.14.1
>VSCode Version: 1.10.2
>OS Version: OS X EI Capitan 10.11.3

**Comment by alefragnani** [comment]
Yep, that's weird 😄 . 

Thanks for reporting. I will take a look...

**Comment by kms-ky-truong** [comment]
Same here.

> Bookmarks Version: 0.14.1
> VSCode version: 1.12.1  (f6868fce3eeb16663840eb82123369dec6077a9b)
> OS Version: macOS Sierra 10.12.4

**Comment by Joolz99** [comment]
Same for me. Just installed this very usefully looking extension. It works fine for bookmarks in the current file - but when using List from All Files, after selecting the command, the bookmark list flashes up and then disappears again.
VS Code version 1.12.2

**Comment by alefragnani** [comment]
This problem was caused by the latests VS Code updates. I just installed an older version and works just fine.

I will try to fix it tonight. otherwise I will remove the _preview_ feature, until properly fixed.

**Comment by Joolz99** [comment]
Thanks. I thought it probably was a VSCode issue since the extension has had such good feedback. Really looking forward to when you get a chance to fix things.

**Comment by alefragnani** [comment]
Confirmed and fixed :+1: 

I'll release version 0.15.0 with the fix later tonight... Stay tuned ...

**Comment by kms-ky-truong** [comment]
It works well now. Many thanks.

**Comment by Joolz99** [comment]
Brill! Many thanks.
