### ISSUE TITLE
[BUG] - It shows Error.

### ISSUE THREAD

**Issue by PythonYunfei** [alefragnani/vscode-bookmarks#691]
It shows this every time I add a bookmark in multi-folder workspace.
![image](https://github.com/alefragnani/vscode-bookmarks/assets/47076058/9ffcd118-5faa-489d-8477-b51c96b4e384)

**Comment by alefragnani** [comment]
Hi @PythonYunfei ,

First of all, sorry for the late reply.

About the issue, is it still ocurring? If yes, could you provide more details about this `E:\` drive the message is refering to? Is it a local or network drive? Is it the drive and folder you are opening in VS Code?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by PythonYunfei** [comment]
> Hi @PythonYunfei ,
> 
> First of all, sorry for the late reply.
> 
> About the issue, is it still ocurring? If yes, could you provide more details about this `E:\` drive the message is refering to? Is it a local or network drive? Is it the drive and folder you are opening in VS Code?
> 
> Thank you

I am sorry that I just realized your reply a minute ago.
`E:\` is just my local drive in which I store my code written by `AutoHotkey`. `AutoHotkey` is a script language, we also called it `AHK`. I opened folders of this drive in VSCode. Besides, the folder my workspace is named `AHK`, which contains multiple VSCode work folders.
