### ISSUE TITLE
[BUG] - Github Releases older than Microsoft Marketplace

### ISSUE THREAD

**Issue by TFWol** [alefragnani/vscode-bookmarks#692]
The GitHub Releases are much older than what's on the Microsoft Marketplace.
I wasn't sure if an automation or something was broken since the marketplace points back to this repo.

**Comment by alefragnani** [comment]
Hi @TFWol ,

Yes, they are different. There is no automation yet, but I'm planning to do so. When added, both should reflect the same version.

Hope this helps
