### ISSUE TITLE
[BUG] - bookmarks.label.suggestion doesn't take the selected text

### ISSUE THREAD

**Issue by manuel-jasso** [alefragnani/vscode-bookmarks#693]
First: thank you for such a useful extension! 👍🏼 

**Environment/version**

- Extension version: v13.4.2
- VSCode version: 1.86.0
- OS version: macOS Sonoma 14.3

**Steps to reproduce**

1. Configure bookmarks.label.suggestion to be useWhenSelected
2. Select some text
3. Toggle bookmark

Result: the bookmark is created, but it is not labeled with the selected text.

More info: I tried removing and reinstalling the extension, but no luck.

**Comment by alefragnani** [comment]
Hi @manuel-jasso ,

First of all, thank you for you kind words. I'm glad to know the extension is helpful.

About your issue, it seems you are using the wrong command. There is an specific command for _labeled bookmarks_, which is called `Bookmarks: Toggle Labeled`. This command is the one to be used when you want to work with bookmarks that contains commands. That setting is used only in this command.

Could you take a look and try out with this command instead? Thank you

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if you have more details

Thanks for your understanding
