### ISSUE TITLE
[FEATURE] - Only show on VISIBLE editors/files

### ISSUE THREAD

**Issue by seowner** [alefragnani/vscode-bookmarks#696]
The current way Bookmarks is implemented is that it shows the same bookmarks across all files, even when you're not editing the file.

Please add an option to show the file's dedicated bookmarks ONLY when you are editing that file. Having all of the other bookmarks open is really frustrating.

Also, I have a lot of bookmarks and my entire scrollbar is blue... I've looked everywhere and can't find a setting to disable this. Please add!

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if you have more details.

Thanks for your understanding
