### ISSUE TITLE
[BUG] - Problems with bookmarking in a network file 

### ISSUE THREAD

**Issue by MarByteBeep** [alefragnani/vscode-bookmarks#704]
Type: <b>Bug</b>

When trying to set a bookmark in for instance a file like:

```
\\192.168.1.102\source\test.z80
```

Bookmarks don't seem to appear. I don't have this problem with local files.

Extension version: 13.4.2
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.74GB (44.79GB free)|
|Process Argv|C:\\git\\finder\\tinder.code-workspace --crash-reporter-id 4a57f22c-da50-4f46-853f-d8ed15eb2489|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
dsvsc021:30996838

```

</details>

**Comment by alefragnani** [comment]
Hi @MarByteBeep ,

I suppose this file is not in the _workspace/folder_ you have opened in VS Code, right? I mean, you opened `C:\Temp\SomeProject` folder in VS Code, and in the same window decided to open this individual file, because you needed to access it. 

If that's the case, you may be facing #397.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by MarByteBeep** [comment]
Apologies for the delay. I think you are right; the files were outside the project.

**Comment by alefragnani** [comment]
Hi @MarByteBeep ,

That's ok, no need to be sorry. Good to know it may be the same issue as #197, because it is now one less to fix 😬 .

Thank you
