### ISSUE TITLE
[FEATURE] - Please add a new feature such as grouping bookmarks into groups

### ISSUE THREAD

**Issue by Mirocow** [alefragnani/vscode-bookmarks#714]
Please add ability like https://marketplace.visualstudio.com/items?itemName=czfadmin.bookmark-manager or like https://marketplace.visualstudio.com/items?itemName=bernardyip.simple-bookmarks 

- Add/edit/delete bookmarks & groups based on your own preferences
- Drag & drop bookmarks to sort and arrange to your liking

**Comment by alefragnani** [comment]
Hi @Mirocow ,

This is already being tracked in #254, and should be called Tags. I'm not sure there will be drag & drop support in the first release, but it's on the track (#655) as well.

Hope this helps
