### ISSUE TITLE
[FEATURE] - Add jumpToPreviousInCurrentEditor / jumpToNextInCurrentEditor

### ISSUE THREAD

**Issue by swinefeaster** [alefragnani/vscode-bookmarks#720]
This is the behavior a lot of former Visual Studio users are used to. It's very confusing when you get thrown into another file, so would be nice to be able to map to these more limited hotkeys.

Thanks!

**Comment by alefragnani** [comment]
Hi @swinefeaster ,

If you want the navigation to work only in the current file, simply add this to your user settings:

```json
    "bookmarks.navigateThroughAllFiles": false
```

Doing so, both `Bookmarks: Jump to Next` and `Bookmarks: Jump to Previous` commands will stay in the current file.

You can even combine with another setting, if you don't want the jumping to _wrap around_ at the first and last bookmarks. Simply add this to your user settings:

```json
    "bookmarks.wrapNavigation": false
```

Hope this helps

**Comment by swinefeaster** [comment]
This is great, thank you for the reply. This definitely unblocks my scenario. It would still be great though if there was a separate command i could use to cycle through all files. For example "ctrl+," to go to previous bookmark, and "shift+ctrl+," to go to the previous bookmark across all files.

________________________________
