### ISSUE TITLE
How to bookmark files between projects?

### ISSUE THREAD

**Issue by Aetet** [alefragnani/vscode-bookmarks#73]
Hello.
Thanks a lot for your extension. Is there possible to makes global bookmarks available between any open project? 

AFAIU property  `"bookmarks.saveBookmarksInProject": false"` must do this trick. But it has not. How to solve this issue?

**Comment by alefragnani** [comment]
Hi @Aetet ,

The bookmarks are saved _per session_ for the project that you are using. If you open another project (folder), it will be _another session_ and so, will be another set of bookmarks. This is how VSCode works for a lot of info, like the the opened files, text selection, cursor position, etc. The `bookmarks.saveBookmarksInProject` purpose is to allow you to store the bookmarks _inside the project_, so you could have it stored (and recovered) from git/svn repositories for instance.

Do you mean you would like to store the bookmarks no _matter the project you opened_ being related to the file itself?

**Comment by Aetet** [comment]
For example I have two projects:
web-server
front-project

And I have tasks.todo file which I use for my notes and as my todolist. I want to have access to it as from web-server and as front-project. 
Here is example what I'm talking about:
https://github.com/oleg-shilo/sublime-favorites

**Comment by Aetet** [comment]
Thanks a lot. It helps me.
