### ISSUE TITLE
[FEATURE] - Toggle bookmarks via the mouse when bookmarks exist

### ISSUE THREAD

**Issue by huangyxi** [alefragnani/vscode-bookmarks#731]
Version 13.5 supports toggling bookmarks via the mouse when no bookmarks are added, which is very convenient when the default shortcut ⌥⌘K is hard to trigger with one hand. However, to add a bookmark without using shortcuts after the first bookmark, it still requires three steps: right-click on the line -> Bookmarks -> Toggle. In this case, I suggest adding a permanent button to toggle bookmarks in the bookmarks explorer.

<img width="343" alt="image" src="https://github.com/alefragnani/vscode-bookmarks/assets/32028289/4824aa55-84a2-4c19-9eb0-f0011fefffbb">

**Comment by huangyxi** [comment]
I'd like to contribute to this feature if possible.

**Comment by alefragnani** [comment]
Hi @huangyxi ,

VS Code supports customization of any keybinding so, if you feeld <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>K</kbd> is hard to trigger with one hand, you are free to change to whatever keybinding you feel easier to use.

The _Add bookmark_ command in the Side Bar, on he other hand, is already being tracked in #319.

Hope this helps
