### ISSUE TITLE
[FEATURE] - Support Renaming a bookmark

### ISSUE THREAD

**Issue by guuzaa** [alefragnani/vscode-bookmarks#732]
Now, we can add and remove a vanilla bookmark or a labeled bookmark, as shown in the left part of the following picture. 
However, why not implement a renaming feature that allows us to change the label of a vanilla or labeled bookmark to another vanilla or labeled bookmark? As the right part of the following picture shows.

![image](https://github.com/alefragnani/vscode-bookmarks/assets/67539676/97defeca-05c9-47a0-9ab8-8bcd6e8a694b)

**Comment by alefragnani** [comment]
Hi @guuzaa ,

This is already possible, using the `Bookmarks: Toggle Labeled` command. 

* If you use it on a _vanilla_ bookmark, it allows you to define a label to it, becoming a _labeled_ bookmark.
* If you use it on a _labeled_ bookmark, it allows you to remove its label, becoming a _vanilla_ bookmark.

Hope this helps

**Comment by guuzaa** [comment]
Hi @alefragnani 
I've tried that, and it actually works. Thank you for your suggestion. 
However, I'm used to use the right button to toggle bookmarks. Is it possible to move this function to the right button, as follows? 
![image](https://github.com/alefragnani/vscode-bookmarks/assets/67539676/4c3fd935-0cb4-437c-a477-bae4fead56d2)

**Comment by alefragnani** [comment]
Hi @guuzaa ,

Good to know it works! And about the improvement, yes, something like it could be added.

Hope this helps
