### ISSUE TITLE
[FEATURE] - Define push / unshift behaviour in settings for newly created items

### ISSUE THREAD

**Issue by patrick-hertling** [alefragnani/vscode-bookmarks#740]
I loop back and forth trough my bookmarks with the shortcuts.
I would love to be able to decide if new bookmarks get pushed to the end of the list or at the beginning.
It could be a new setting: 

Bookmarks: Adding new bookmaks 
Defines where new bookmarks should be inserted
SelectOptions: ['beginning', 'end']

**Comment by alefragnani** [comment]
Hi @patrick-hertling ,

The bookmarks has no _order_ defined. It just refers to some location (line x column) within the file, and when displaying in the Side Bar and/or Command Palette, they are displayed sorted by line number.

There are however, open requests to allow sorting for some attributes, like label (for labeled bookmarks), path, and even drag & drop hability on the Side Bar. I guess these sort ideas is a good step forward to what you suggested, without more complexity than necessary for toggling bookmarks.

Hope this helps.
