### ISSUE TITLE
[BUG] - Keep showing generating nothing happens

### ISSUE THREAD

**Issue by ranjeet-rf** [alefragnani/vscode-bookmarks#745]
<img width="727" alt="Screenshot 2024-08-21 at 4 13 57 PM" src="https://github.com/user-attachments/assets/1d02e0bf-afc7-4a90-b9af-92ac252cab28">

**Environment/version**

- Extension version:
- VSCode version: 
- OS version:

**Steps to reproduce**

1.  Have some conversation.

2. Wait for 20 to 30 mins and the try to send message it keeps loading show generating. 

3. When we restart vscode it starts working normal for 20 30 mins

**Comment by alefragnani** [comment]
Hi @ranjeet-rf , 

I'm closing this issue because it is not relative to the Bookmarks extension. 

Thanks for your understanding
