### ISSUE TITLE
bookmark by find

### ISSUE THREAD

**Issue by luca1010** [alefragnani/vscode-bookmarks#75]
Hi,

It would be great to be able to set bookmark on lines that match a search (like Notepad++)

**Comment by alefragnani** [comment]
Hi @luca1010 ,

Do you mean something like #7? Or using the _Find_ command (find in current file) 

Unfortunately, in both cases, there is no API yet 😢 . But when released, that's something I would like to add to the extension.

Hope this help

**Comment by luca1010** [comment]
Hi, Yes, like #7

Grazie mille e buon lavoro.

Luca

**Comment by alefragnani** [comment]
Closing as duplicate of #7
