### ISSUE TITLE
[FEATURE] - save / import / export bookmarks

### ISSUE THREAD

**Issue by samzuercher** [alefragnani/vscode-bookmarks#752]
Use case: analyze code and write a summary on where in the code a variable is used.
1. search the variable
2. add bookmarks on relevant mentions
3. ideally: get all relative filenames of the bookmarks -> paste them in the summary
4. get the relevant code blocks from the bookmarks and paste them also in the summary

summary would then look similar to this:
variable is used in `{relative\path\tofile.js}` like 
```
// some code
```

As far as i know this is currently not possible because the bookmarks are stored in a hidden place. Why not store the bookmarks as .json in the `.vscode`-folder, so they are easily manageable and could also be read by other software to automate things and e.g. create stuff like https://github.com/alefragnani/vscode-bookmarks/issues/172.

---------------
similar items:
- https://github.com/alefragnani/vscode-bookmarks/issues/710
- https://github.com/alefragnani/vscode-bookmarks/issues/682
- https://github.com/alefragnani/vscode-bookmarks/issues/624
- https://github.com/alefragnani/vscode-bookmarks/issues/622
- https://github.com/alefragnani/vscode-bookmarks/issues/569
- https://github.com/alefragnani/vscode-bookmarks/issues/415
- https://github.com/alefragnani/vscode-bookmarks/issues/254
- https://github.com/alefragnani/vscode-bookmarks/issues/172

**Comment by alefragnani** [comment]
Hi @samzuercher ,

The bookmarks are, _by default_, stored in VS Code internals, which today is a SQLite database. 

The extension has however, the possibility to store the bookmarks exactly in the location you commented (the `.vscode` folder inside each project), in a filename called `bookmarks.json`. To do this, you just have to define `bookmarks. saveBookmarksInProject` setting to `true`. 

The file contains the relative file path, the bookmark location and its label (if available) but not the line content. To extract the line content you could use the `Bookmarks (Selection): Select Lines` command, followed by a `Copy` command. It will work on the current file only, not the entire folder/workspace.

Hope this helps

**Comment by alefragnani** [comment]
Btw, an export feature is already being tracked in #172
