### ISSUE TITLE
Add a label to a bookmark

### ISSUE THREAD

**Issue by bertolo1988** [alefragnani/vscode-bookmarks#76]
As soon as the bookmark list start growing i became a bit lost.

Adding a label to each bookmark could be really handy for people that have to deal with very messy code.

**Comment by Lixissimus** [comment]
I would love to see this feature! Thanks for the great work so far! :)

**Comment by drinktee** [comment]
+1.
When a project has many bookmarks, I can't remember why I add this bookmark.
It's helpful to add a description for every bookmark.

**Comment by zheeeng** [comment]
+1 Add custom labels with custom colors. We can ease jump to a specific label, such as TODO, DEBUG, FIX, OPT.

**Comment by alefragnani** [comment]
I'm currently updating the extension to support multi-root workspaces, and already _preparing_ to have *labels* and *column* in bookmarks. After releasing the multi-root workspaces, I would like to focus on these two enhancements.

**Comment by raffacabofrio** [comment]
+1

**Comment by t-ricci-molecle** [comment]
I totally need named/labeled bookmarks! +1 :+1:

**Comment by alefragnani** [comment]
Based on #100 comments, the feature should also have:

- [ ] Multiple tags for each bookmark
- [ ] Ability to filter/search bookmarks by tag

**Comment by t-ricci-molecle** [comment]
It would also be nice to jump beetween them with a command (ie. on OSX shortcut `command+shift+P`) and entering the label (with an incremental search dropdown).
That way we can navigate purely with the keyboard if we like, instead of having to open the UI and click with the mouse

**Comment by alefragnani** [comment]
@t-ricci-molecle you can already do that. Just define a `Keyboard Shortcut` for the `Bookmarks: List` and `Bookmar: List from All Files` commands. And the filter works for both, _line numbers_ and _contents_.

What is missing?

**Comment by t-ricci-molecle** [comment]
@alefragnani yes, but it's without label. With the label you could even start to type the label for the incremental search across multiple files, and press enter to load that searched label

**Comment by alefragnani** [comment]
Ah, do you mean "another command", like `Bookmakrs: List Labels/Tags from All Files`, because you would like to navigate/search using the bookmark's label, instead of its line number/content?

**Comment by t-ricci-molecle** [comment]
Yes, or the same command could search/show based on both label and/or number.
In any case even with the label/tag I would still show a preview of the content on the right after the label string

**Comment by alefragnani** [comment]
Unfortunately, there is no way to presente both (line preview and bookmark tag/label) because it wouldn't fit. It must be a new command 😢

**Comment by xucongli1989** [comment]
+1  Each mark should have a name by myself if I want.

**Comment by mbenkmann** [comment]
Looking forward to this issue being implemented. None of the existing TODO-List extensions scratches my itch, but if this issue was implemented, I could use bookmarks with "TODO" and "FIXME" labels.

**Comment by Orrison** [comment]
I am curious about this as well.

**Comment by alefragnani** [comment]
It means _it's implemented_ 😁 . 

There is no commit because I didn't pushed yet (neither associated it to any particular commit). 

I'm making the final steps to publish the new version, defined in [Milestone 9.0](https://github.com/alefragnani/vscode-bookmarks/milestone/18). Probably going until the end of the week.

Stay tuned.

**Comment by mbenkmann** [comment]
AWESOME! Looking forward to trying it out.
