### ISSUE TITLE
Question - Method to Add Bookmarks only

### ISSUE THREAD

**Issue by FrogmanL** [alefragnani/vscode-bookmarks#81]
I’ve been working on a script that can search through some of our data for certain issues. I thought I might leverage your extension to bookmark the issues when I find them. The code can find the issues and toggle the bookmark, but I don’t want the bookmark to turn off if I run the code again. 

Does your code support only adding bookmarks? Or, is there a way to clear a single bookmark before toggling it on?

**Comment by alefragnani** [comment]
Hi @FrogmanL ,

When you `Toggle`  the bookmark, it will _mark_ or _unmark_ the line, depending on the line already having a bookmark. If you change the file's content _outsize VSCode_, the bookmarks will be out of sync, but will not be removed (unless the updated file has less lines, and the removed lines had bookmarks)

Do you mean that?

Hope this helps

**Comment by FrogmanL** [comment]
That's not quite what I meant. I wondered if there was any exposed method which adds bookmarks only (not toggle). 

I have script that jumps to lines and toggles the bookmark (using your code). My problem is if I jump to a the same line more than once, the bookmark toggles off rather than remaining latched on.  Maybe I can peek in the vscode gutter to see if it's already bookmarked.

**Comment by alefragnani** [comment]
Hm, I understand... Unfortunately, the `Toggle` command is meant to turn on and off bookmarks in lines. There is no command as you need, at least not yet.

**Comment by alefragnani** [comment]
Hi @FrogmanL , do you still need this?

**Comment by FrogmanL** [comment]
We found a workaround for now. If you implement this in the future, I’d love to know, but our workaround will be fine.

Thank you for your help!

**Comment by alefragnani** [comment]
Currently, there is no intention to _split_ the `Toggle` command in `Mark` and `Unmark` (or anything like that). 

I'll keep it simple.
