### ISSUE TITLE
Multi root workspace - bookmarks not displayed on side side bar

### ISSUE THREAD

**Issue by zenyuk** [alefragnani/vscode-bookmarks#84]
After updating to VS Code 1.18.0 bookmarks are not displayed on the left- side Bookmark bar when opening multiple root folders in the workspace.

Repro steps:
- open vs code
- open any folder (file->open folder)
- add another root folder (file->add folder to workspace)
- in any file set a bookmark (ctrl+alt+k)

Result: 
- bookmark side bar is empty

**Comment by PixelT** [comment]
For me it also doesn't work when I have only one folder in the workspace.
This bookmark functionality break after update to 1.18

**Comment by alefragnani** [comment]
Hi @zenyuk ,

I could reproduce the problem. But right after reloading the window (`Window: Reload` command), the bookmarks appeared and I was able to add others as well.

Could you confirm this?

**Comment by alefragnani** [comment]
Hi,

I just tested the described scenario with the current releases, and couldn't reproduce the error anymore. The bookmarks are appearing, just as expected.

Could you confirm that?

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
