### ISSUE TITLE
installation crashes

### ISSUE THREAD

**Issue by hotaru355** [alefragnani/vscode-bookmarks#85]
I am using the latest version of VsCode and tried to install the extension through the extensions marketplace (CTRL+SHIFT+P, "Extensions: Install Extensions")

The green "Install" button changes to a blue "Installing", but never finishes. After a period of time, VsCode shows an empty error message as a pop-up:

```
XHR failed:
```

This is my Help>About:
```
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

I am happy to further troubleshoot. Please advise. Thanks!

**Comment by alefragnani** [comment]
Hi @hotaru355 ,

There are some reports in VS Code repo about this error (https://github.com/Microsoft/vscode/issues?q=is%3Aissue+XHR+is%3Aclosed) and some of them tells about _proxies_, _instability_, etc. The https://github.com/Microsoft/vscode/issues/34385 issue in special has a great thread about it.

Is this your scenario? If yes, you could take a look at the proposed solutions?

Hope this helps.

**Comment by hotaru355** [comment]
Thanks for the links. I just tried again installing the extension and now it works. Network issue? Closing this.
