### ISSUE TITLE
[Suggestion] Is it possible to auto-bookmark based on a list of keywords

### ISSUE THREAD

**Issue by jmeier** [alefragnani/vscode-bookmarks#86]
I use this extension to navigate large log files. First step is often to seach for keywords and bookmark them by hand (see also #7). There are several searches  necessary due to the fact I need a certain set of keywords ("***warning", "***error", "***exception", ...). It would be very handy to automaticly set bookmarks based on a list of keywords.

**Comment by alefragnani** [comment]
HI @jmeier ,

#7 still depends on VS Code API, so there is nothing I can do about it, sorry. And I think that even the _Search in active document_ has limits on how I could interact with. 

But maybe _creating my own search_ would do the trick. I open a field to the user _type the word he/shee wants to bookmark_, and I search that word in the active document and bookmark the line where it is. The downside in this solution is that you would lose some _search functionalities_ like RegEx, Case Sensitivity, etc.

What do you think?

**Comment by jmeier** [comment]
Hi @alefragnani 

I see your problem on #7. A (temporary) workaround would surely be to provide your own search box. And hoping the API gets extended in the future so you can then get rid of it. 
For my suggestion above it would actually better to give the keywords to auto-bookmark in a more permanent way. Maybe in a settings-file? Of course one had to give a little more than just keywords: also the file types must be given (something like: auto-bookmark "***warning", "***error", "***exception" in *.log files -andalso- auto-bookmark "ToDo:" in *.js, *.cs, *.vb, *.txt).

**Comment by alefragnani** [comment]
I think a better solution would be to support toggling bookmark with _multi cursor_. Doing so, you would be free to search for any word/regex, select all occurrences (like using `Cmd + D`) and toggle a bookmark. Then, each line that contains the located word/sentence, would be bookmarked.

This is something that I would like to have too 😄

**Comment by jmeier** [comment]
Hi @alefragnani 

I agree, this sounds very nice and seem to be a "clean" solution. One may combine this with a multi-command-tool (e.g. ryuta46.multi-command) to ease re-occuring tasks.

**Comment by dbarciela** [comment]
Agreed #77  is the practical solution for this. This is one of the most important features I use in notepad++ when analyzing logs  (bookmark specific threads or log categories)

**Comment by alefragnani** [comment]
I'm closing this in favor of #77, which is broader.
