### ISSUE TITLE
Organize Bookmarks in Folder

### ISSUE THREAD

**Issue by MizuBishi** [alefragnani/vscode-bookmarks#88]
Hi, 
I love this extension and I use it every day. Nevertheless it would be great to have:
- organize bookmarks with customized folders to get a better overview (I have a lot of bookmarks :))
- sort bookmarks in the tree view alphabetically

If not, I will still use this because it is awesome! 
Thank you so much

Best, 
Michelle

**Comment by alefragnani** [comment]
Hi @MizuBishi ,

Thanks, I'm glad you like it 👍 .

I think that to accomplish both of your requests, it should be necessary to have #76 first. I mean, bookmarks are only _marked lines_ today, and to be able to sort alphabetically, I guess you are talking about _its name_ instead of the _contents_, am I right?

What do you think?

Happy New Year, BTW 😄

**Comment by WasabiFan** [comment]
I'm also interested in this.

I use bookmarks to track areas of note when looking into a bug in code I'm unfamiliar with; as I find pertinent lines I bookmark them so I they don't get lost as I drill into the call stack. For me, I'll often be investigating a bug, then push that for a code review before switching to a different branch and working on a different bug or feature. In this case, I still want those bookmarks from my original bug investigation available if I need to go back to it and remind myself where things were, but at the same time I largely want to ignore them until I return to looking into that bug. Being able to put bookmarks relating to a particular bug/feature/area would be extremely helpful here to keep things organized.

**Comment by alefragnani** [comment]
**Version 9** has been released almost 3 months ago. It incorporates #76 which allows you to search bookmarks not only based on line number or content, but also _labels_). Combined with #109 , it's now easier to locate bookmarks. 

Based on this new features, I'm closing this issue.
