### ISSUE TITLE
Question: Where is the information store for the bookmarks?  

### ISSUE THREAD

**Issue by LordHog** [alefragnani/vscode-bookmarks#89]
Hello,

  Where is the information for the bookmarks stored?  I needed to uninstall VSC and remove all extensions, but I keep most of the data in another directory as backup to restore the bookmarks.  I hope that I saved the right file, but I can't find that info.

Mark

**Comment by alefragnani** [comment]
Hi @LordHog ,

By default, the bookmarks are stored in the `Local Storage` used by VSCode/Electron/Chrome. I don't know if there is a way to _backup/restore_ that file (I don't know Chrome tools that much) but if you know how to do this, the file is located in `%APPDATA\\Roaming\\Code\\User\\Local Storage\\file__0.localstorage` (in Windows).

But, if you change the setting `bookmarks.saveBookmarksInProject` to true, then the bookmarks will be stored _with the project_, in `.vscode\bookmarks.json` file.

Hope this helps

**Comment by LordHog** [comment]
Mr. Alefragnani, sweet!!!  I got all my bookmarks back.  Thanks for the information and the quick response.   I might use the bookmarks.saveBookmarksInProject feature going forward.

**Comment by Otiel** [comment]
For reference, seems that it's stored in `AppData\Roaming\Code\Local Storage`.
