### ISSUE TITLE
Add `Collapse All` command in the Side Bar

### ISSUE THREAD

**Issue by wduminy** [alefragnani/vscode-bookmarks#92]
When there are a few bookmarks per file, and you have a few files with bookmarks in them, you have to expand one file at a time (in the __tree view__) while looking for a specific bookmark.  

What do you think about having an __expand all__ action that expands all the items in the tree?  It could be placed in the toolbar next to the __refresh__ action.

**Comment by alefragnani** [comment]
Hi @wduminy ,

That's a good idea 👍

**Comment by alefragnani** [comment]
For now, only `Collapse All` command will be available...
