### ISSUE TITLE
Running the contributed command:'bookmarks.toggle' failed.

### ISSUE THREAD

**Issue by LordHog** [alefragnani/vscode-bookmarks#93]
Hello,

  Just today I started seeing the message "Running the contributed command:'bookmarks.toggle' failed." when trying to toggle a bookmark in Visual Studio Code (v1.20.0) with Bookmarks 0.18.1.  This feature was previously working, not sure what is driving the error now.  I can edit the bookmarks.json directory in the program folder to manually add/remove a bookmark with shifting focus to another tab then back will "generally" show the bookmark or remove the bookmark. I am running on a Linux machine (CentOS Linux release 7.1.1503).  

  I am using Remote Desktop Connection from Windows 10 to access the CentOS machine.

Regards.

**Comment by alefragnani** [comment]
Hi @LordHog ,

Aside from some error has occurred while installing/updating the extension, I already saw this message if the file is _too large_. There is an known limitation in VS Code for large files as you can see in #31 .

If your file is not large, then try to reinstall the extension to see if the error remains.

Hope this helps.

**Comment by alefragnani** [comment]
Hi @LordHog ,

Any news after reinstallation?

**Comment by LordHog** [comment]
Mr. @alefragnani , sorry, I haven't had the chance to go through this process.  I don't want to waste too much time trying to get the tool working until I complete some of my JIRAs at work.  I should be able to try this coming week.  Will report back once I have some info for you.

**Comment by LordHog** [comment]
Okay, so I recently updated Visual Studio Code to 1.21.0 and now the bookmarks seem to be working again.  Not sure something during the install process or changes in the build release that effected the bookmarks.

**Comment by VipSaran** [comment]
Stopped working for me: `command 'bookmarks.toggle' not found`
VSC 1.34.0
Reinstalled the extension with no effect...

**Comment by alefragnani** [comment]
Hi @VipSaran ,

Just a tip, be sure the _reinstallation process_ is made following the steps below. 

1. Uninstall the extension
1. Close all VS Code instances
1. Reopen VS Code
1. Reinstall the extension

> This is not an _official process_ but I had different issues just uninstalling and installing again without fully unloading VS Code

Another chance is you are opening a _large file_ as described in the [comment above](https://github.com/alefragnani/vscode-bookmarks/issues/93#issuecomment-366517346).

If still not working, I would ask you to check `Toggle Developer Tools / Console`, looking for _error messages_. Please also add your current OS.

Hope this helps

**Comment by VipSaran** [comment]
@alefragnani I've repeated the process to the letter (even deleted the leftover `.vscode\extensions\alefragnani.bookmarks-10.4.3` folder), but with no effect.

This is the output of the console:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
workbench.main.js:3272 [Extension Host] debugger listening on port 26761
workbench.main.js:238 [Extension Host] [vscode-icons] v8.6.0 activated!
workbench.main.js:3855 Activating extension 'alefragnani.Bookmarks' failed: Cannot read property 'uri' of undefined.
_logMessageInConsole @ workbench.main.js:3855
workbench.main.js:238 [Extension Host] Activating extension `alefragnani.Bookmarks` failed:  Cannot read property 'uri' of undefined
t.log @ workbench.main.js:238
workbench.main.js:238 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'uri' of undefined
	at loadFrom (c:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:24981)
	at c:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:5668
	at module.exports.t.activate (c:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:6016)
	at Function._callActivateOptional (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:731:936)
	at Function._callActivate (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:731:625)
	at define._doActivateExtension.Promise.all.then.e (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:635)
```

I hope it helps :)

**Comment by VipSaran** [comment]
The plot thickens: it only fails for existing workspaces.

When an editor is opened in a New Window (ctrl+shift+n), the extension works fine.

**Comment by VipSaran** [comment]
Another way to reproduce it is to open VSC without a workspace (in which case the Bookmarks extension works fine), then "Save Workspace As...". At that point -- once the file/editor is in the Workspace -- the extension stops working.

This is the console output just after the "Save Workspace As..." operation:
```
08:59:46.927 workbench.main.js:3272 [Extension Host] debugger listening on port 27931
08:59:48.032 workbench.main.js:238 [Extension Host] [vscode-icons] v8.7.0 activated!
08:59:48.047 workbench.main.js:3855 Activating extension 'alefragnani.Bookmarks' failed: Cannot read property 'uri' of undefined.
_logMessageInConsole @ workbench.main.js:3855
_logOrShowMessage @ workbench.main.js:3855
(anonymous) @ workbench.main.js:3205
(anonymous) @ workbench.main.js:34
n @ workbench.main.js:34
$onExtensionActivationError @ workbench.main.js:3205
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
08:59:48.048 workbench.main.js:238 [Extension Host] Activating extension `alefragnani.Bookmarks` failed:  Cannot read property 'uri' of undefined
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
08:59:48.048 workbench.main.js:238 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'uri' of undefined
	at loadFrom (C:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:24981)
	at C:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:5668
	at module.exports.t.activate (C:\Users\rsa\.vscode\extensions\alefragnani.bookmarks-10.4.3\dist\extension.js:1:6016)
	at Function._callActivateOptional (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:731:936)
	at Function._callActivate (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:731:625)
	at define._doActivateExtension.Promise.all.then.e (c:\Users\rsa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:635)
```

**Comment by VipSaran** [comment]
It also fails for new workspaces, e.g. when an editor is opened w/o being saved to a workspace, the bookmarks work fine. But, once that editor is saved to a workspace ("Save Workspace As..."), the extension starts throwing errors. But, it only happens when there are no folders added to the workspace (which is a valid scenario).

So, **the bug comes when working in a workspace that has no folders added to it**.

Please fix this.

**Comment by alefragnani** [comment]
Hi @VipSaran ,

Thanks for the investigation. It helps a lot!

Can you confirm this scenario _stopped working_ in recent releases (VS Code and/or Bookmarks), or is are you a new VS Code/Bookmarks user? I don’t use Workspaces that much, so never had this issue before (also, never used and empty workspace)

I’all move your comments to a new issue, so it should be properly tracked.

Thank you

**Comment by alefragnani** [comment]
Oops, just noted comment https://github.com/alefragnani/vscode-bookmarks/issues/93#issuecomment-494318035, which you say “stopped working “... that’s weird, because nothing has changed in the extension in the current extension’s releases which could cause that.

Are you using VS Code Insiders?

**Comment by VipSaran** [comment]
> Oops, just noted comment [#93 (comment)](https://github.com/alefragnani/vscode-bookmarks/issues/93#issuecomment-494318035), which you say “stopped working “... that’s weird, because nothing has changed in the extension in the current extension’s releases which could cause that.
> 
What has changed is that I have started using workspace w/o a folder added to it.

> Are you using VS Code Insiders?

Still the same answer as in https://github.com/alefragnani/vscode-bookmarks/issues/93#issuecomment-494318035

**Comment by alefragnani** [comment]
Tracked in #212
