### ISSUE TITLE
When Bookmarks is enabled VS code working indicator never goes away.

### ISSUE THREAD

**Issue by prlyons** [alefragnani/vscode-bookmarks#97]
Recently I noticed that VS Code's working indicator was never going away. I tracked this down to the Bookmarks extension.  If I disable it and reload the working indicator goes away. Here's a screenshot. 

![2018-03-14](https://user-images.githubusercontent.com/5412104/37430258-fe8d8eea-27a7-11e8-8e40-e9c838ed462e.png)

I am using Windows 10 and VS Code 1.21.0. 
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by alefragnani** [comment]
Hi @prlyons ,

At first sight, I don't see why the extension could be doing that. When you open a folder/workspace, the extension will look for bookmarks registered for that folder/workspace, in VS Code internal repo or in `vscode\bookmarks.json` file inside your project (depending on `saveBookmarksInProject` setting). Then, it will _connect_ to the opened file (if any) and check for bookmarks for that file. If has any, it will _decorate_ the bookmarks in that file. Everytime you change the active file in VS Code, it will _check_ and _decorate_ the bookmarks for that file.

To better understand you issue:

1. How is defined your `bookmarks.saveBookmarksInProject` setting?
2. How many  bookmarks do you have for this particular folder/workspace? Use `Bookmarks: List From All Files` command to check, or the `Bookmarks` treeview in `Explorer` panel
3. Is there anything visible in `Console`. Use `Toggle Developer Tools` command to check

Hope this helps

**Comment by alefragnani** [comment]
Hi @prlyons , any news about it?

**Comment by prlyons** [comment]
Hi @alefragnani, I re-enabled the extension and no longer see the issue.  I believe there was a VS Code update in between.
